Repository wikimedia/apps-android-wikipedia, pull requests merged in 2019-08, with the labels that each got.

#527 Remove pre-beta flag for suggested edits cards
  app/src/main/java/org/wikipedia/feed/FeedContentType.java
Labels: High Priority

#528 Fix: Feedback message after edit from Suggested Edits cards
  app/src/main/java/org/wikipedia/feed/FeedFragment.java
Labels: High Priority

#525 Simplify and speed up the call-to-action on top of lead image.
  app/src/main/java/org/wikipedia/page/leadimages/LeadImagesHandler.java
Labels: High Priority

#534 Fix support for switching to be-tarask language.
  app/src/main/java/org/wikipedia/dataclient/WikiSite.java
  app/src/main/java/org/wikipedia/language/AppLanguageLookUpTable.java
Labels: Minor

#526 Bridge interactions
  app/src/main/java/org/wikipedia/bridge/JavaScriptActionHandler.kt
  app/src/main/java/org/wikipedia/page/PageFragment.java
  app/src/main/java/org/wikipedia/page/PageFragmentLoadState.java
  app/src/main/java/org/wikipedia/page/leadimages/LeadImagesHandler.java
  app/src/main/res/values-qq/strings.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/strings_no_translate.xml
Labels: WIP, mobile-html

#497 Remove deprecated bridge sendMessage()
  app/src/main/java/org/wikipedia/edit/preview/EditPreviewFragment.java
  app/src/main/java/org/wikipedia/page/PageFragment.java
  app/src/main/java/org/wikipedia/page/PageFragmentLoadState.java
  app/src/main/java/org/wikipedia/page/ToCHandler.java
  app/src/main/java/org/wikipedia/page/shareafact/ShareHandler.java
  app/src/main/java/org/wikipedia/util/L10nUtil.java
Labels: mobile-html

#538 Add "edit description" support
  app/src/main/java/org/wikipedia/edit/EditHandler.java
  app/src/main/java/org/wikipedia/views/ObservableWebView.java
Labels: mobile-html

#541 Minor follow-up to toc
  app/src/main/java/org/wikipedia/bridge/JavaScriptActionHandler.kt
  app/src/main/java/org/wikipedia/page/ToCHandler.java
Labels: Minor

#543 Use proper Kotlin access syntax in JavaScriptActionHandler.kt
  app/src/main/java/org/wikipedia/bridge/JavaScriptActionHandler.kt
Labels: Minor

#545 Fix the issue of a crash when loading article offline
  app/src/main/java/org/wikipedia/page/PageFragment.java
Labels: mobile-html

#557 Remove unused logic of loading local CSS assets
  app/src/main/java/org/wikipedia/dataclient/okhttp/OkHttpWebViewClient.java
Labels: mobile-html

#555 Mobile-html: fix the logic of showing ToC
  app/src/main/java/org/wikipedia/page/PageFragment.java
Labels: mobile-html

#556 Encode the page title to prevent showing page with error codes
  app/src/main/java/org/wikipedia/bridge/CommunicationBridge.java
Labels: mobile-html

#561 Tweak: update bottom sheet button height and use correct parent style on Transparent buttons
  app/src/main/res/layout/view_link_preview_overlay.xml
  app/src/main/res/values/styles.xml
Labels: Minor

#568 Hygiene: remove redundant parameter and use suggested Charset value
  app/src/main/java/org/wikipedia/util/StringUtil.java
Labels: Minor

#565 Fix: make sure the "go back" button work properly on WikiErrorView
  app/src/main/java/org/wikipedia/language/LangLinksActivity.java
  app/src/main/java/org/wikipedia/notifications/NotificationActivity.java
  app/src/main/java/org/wikipedia/search/SearchResultsFragment.java
Labels: Minor

#569 Fix possible crash on TabActivity
  app/src/main/java/org/wikipedia/page/tabs/TabActivity.java
Labels: Minor

#575 Prevent possible crash on videoView in GalleryItemFragment
  app/src/main/java/org/wikipedia/gallery/GalleryActivity.java
  app/src/main/java/org/wikipedia/gallery/GalleryItemFragment.java
Labels: Minor

#586 Hygiene: fix import error, remove unused resource and update naming
  app/src/main/java/org/wikipedia/views/LanguageScrollView.java
Labels: Minor

#584 Fix: possible crash when showing undo snackbar in TabActivity
  app/src/main/java/org/wikipedia/page/tabs/TabActivity.java
Labels: Minor

#587 Restore ability to view single SVG images in Gallery.
  app/src/main/java/org/wikipedia/gallery/GalleryActivity.java
  app/src/main/java/org/wikipedia/page/PageFragment.java
  app/src/main/java/org/wikipedia/page/leadimages/LeadImagesHandler.java
Labels: High Priority

#590 Tweak: use fadingEdge on LanguageScrollView and minor code clean up
  app/src/main/java/org/wikipedia/search/SearchFragment.java
  app/src/main/java/org/wikipedia/views/LanguageScrollView.java
  app/src/main/res/layout/fragment_search.xml
  app/src/main/res/layout/view_language_scroll.xml
Labels: Minor

#592 Fix possible crash when entering Gallery.
  app/src/main/java/org/wikipedia/gallery/GalleryActivity.java
Labels: High Priority

#615 Very minor string tweak
  app/src/main/res/values/strings.xml
Labels: Minor
