Repository wikimedia/apps-android-wikipedia, pull requests merged in 2019-06, with the labels that each got.

#330 Fix possible crash on Tab screen
  app/src/main/java/org/wikipedia/page/tabs/TabActivity.java
Labels: Bug

#331 Fix the deep link does not work properly on /zh/ pattern
  app/src/main/AndroidManifest.xml
Labels: Bug

#335 Tweak how suggested edit targets are counted.
  app/src/main/java/org/wikipedia/dataclient/mwapi/EditorTaskCounts.java
  app/src/main/java/org/wikipedia/notifications/NotificationEditorTasksHandler.java
Labels: Minor

#339 Use correct text color for Suggested edits "ADD" button
  app/src/main/res/layout-land/fragment_suggested_edits_add_descriptions.xml
  app/src/main/res/layout/fragment_suggested_edits_add_descriptions.xml
Labels: Minor

#340 Retain the added description when changing the orientation
  app/src/main/java/org/wikipedia/descriptions/DescriptionEditFragment.java
Labels: Minor

#341 Hygiene: removed unused code in ViewUtil
  app/src/main/java/org/wikipedia/views/ViewUtil.java
Labels: Minor

#348 Simplified code logic and use forEach loop in Suggested edits
  app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsCardsFragment.kt
  app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsCardsItemFragment.kt
Labels: Minor

#365 Fix: the translation button visibility in GalleryActiviy
  app/src/main/java/org/wikipedia/gallery/GalleryActivity.java
Labels: Minor

#370 Remove unused string resources and fix typo of resource name
  app/src/main/java/org/wikipedia/feed/suggestededits/SuggestedEditsCardView.kt
  app/src/main/res/values-qq/strings.xml
  app/src/main/res/values/strings.xml
Labels: Minor

#372 Upgrade androidx-test JUnit library version to 1.2.0
  app/build.gradle
Labels: Minor

#373 Hygiene: remove unused resources
  app/src/main/res/anim/page_exit_transition.xml
  app/src/main/res/anim/page_exit_transition_rtl.xml
  app/src/main/res/drawable/ic_action_feed_edit.xml
  app/src/main/res/drawable/ic_dialog_image_title_descriptions.xml
  app/src/main/res/drawable/ic_icon_swap.xml
  app/src/main/res/drawable/tab_item_shape_dark.xml
  app/src/main/res/drawable/tab_item_shape_light.xml
  app/src/main/res/layout/view_my_contributions_progress.xml
  app/src/main/res/menu/menu_action_mode_search.xml
Labels: Minor

#369 Fix the issue of showing error card when image does not have description in Suggested edits
  app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsCardsItemFragment.kt
  app/src/main/res/values-qq/strings.xml
  app/src/main/res/values/strings.xml
Labels: Minor

#367 Fix: use correct language code to avoid the variant issue
  app/src/main/java/org/wikipedia/feed/suggestededits/SuggestedEditsFeedClient.kt
  app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsCardsItemFragment.kt
Labels: Minor

#371 Show correct license notice for image caption review screen
  app/src/main/java/org/wikipedia/descriptions/DescriptionEditLicenseView.kt
  app/src/main/java/org/wikipedia/descriptions/DescriptionEditReviewView.kt
Labels: Minor

#360 Fix: use correct color for status bar, progress bar and error view
  app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsCardsActivity.kt
  app/src/main/res/layout-land/fragment_suggested_edits_cards_item.xml
  app/src/main/res/layout/fragment_suggested_edits_cards_item.xml
Labels: Minor

#377 Fix: translate caption in Gallery should be editable if it hosts in Commons
  app/src/main/java/org/wikipedia/gallery/GalleryActivity.java
Labels: Minor

#379 Use thumbnail URL for image caption review screen
  app/src/main/java/org/wikipedia/descriptions/DescriptionEditReviewView.kt
Labels: Minor

#385 Remove unnecessary cast and use suggested math method.
  app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsCardsFragment.kt
  app/src/main/java/org/wikipedia/views/ImagePreviewDialog.kt
  app/src/main/java/org/wikipedia/views/SwipeableListView.kt
Labels: Minor

#389 Prevent division by zero.
  app/src/main/java/org/wikipedia/feed/FeedContentType.java
Labels: High Priority

#390 Minor : code review comment incorporated
  app/src/main/res/values/styles.xml
Labels: Minor

#395 Fix tallying of suggested edit milestones.
  app/src/main/java/org/wikipedia/dataclient/mwapi/EditorTaskCounts.java
Labels: High Priority

#401 Fix: Update Date string for Suggested edits feed cards
  app/src/main/java/org/wikipedia/feed/suggestededits/SuggestedEditsCard.kt
  app/src/main/java/org/wikipedia/feed/suggestededits/SuggestedEditsFeedClient.kt
Labels: Minor

#408 Update kotlin gradle plugin version to 1.3.40
  build.gradle
Labels: Minor

#407 Remove unused test method
  app/src/main/java/org/wikipedia/settings/Prefs.java
  app/src/main/res/values/preference_keys.xml
  app/src/main/res/xml/developer_preferences.xml
Labels: Minor

#409 Fix the /zh/ deep link always shows error page
  app/src/main/java/org/wikipedia/util/UriUtil.java
Labels: Minor

#413 Tweak: adjust the lineSpacing to align to the left column text
  app/src/main/res/layout/view_image_detail_horizontal.xml
Labels: Minor

#414 Tweak: make the edit description input layout align to the summary text view
  app/src/main/res/layout/view_description_edit.xml
Labels: Minor
