Repository wikimedia/apps-android-wikipedia, pull requests merged in 2019-03, with the labels that each got.

#62 Tweak of "find text" feature in the editor screen
  app/src/main/java/org/wikipedia/edit/FindInEditorActionProvider.java
  app/src/main/java/org/wikipedia/edit/richtext/SyntaxHighlighter.java
  app/src/main/java/org/wikipedia/views/FindInPageActionProvider.java
Labels: Tweak

#63 Tweak of Add sepia theme ticket
  app/src/main/res/color/color_state_nav_tab_light.xml
  app/src/main/res/drawable/ic_image_gray_dark_24dp.xml
  app/src/main/res/drawable/ic_image_gray_light_24dp.xml
  app/src/main/res/drawable/ic_image_gray_opaque_24dp.xml
  app/src/main/res/drawable/ic_image_gray_transparent_24dp.xml
  app/src/main/res/drawable/ic_text_placeholder.xml
  app/src/main/res/layout/activity_page.xml
  app/src/main/res/layout/dialog_link_preview.xml
  app/src/main/res/layout/group_captcha.xml
  app/src/main/res/layout/item_on_this_day_pages.xml
  app/src/main/res/layout/item_page_list_entry.xml
  app/src/main/res/layout/item_search_result.xml
  app/src/main/res/layout/item_tab_contents.xml
  app/src/main/res/layout/view_description_edit.xml
  app/src/main/res/layout/view_floating_queue.xml
  app/src/main/res/layout/view_list_card_item.xml
  app/src/main/res/values/attrs.xml
  app/src/main/res/values/styles.xml
  app/src/main/res/values/styles_black.xml
  app/src/main/res/values/styles_dark.xml
  app/src/main/res/values/styles_light.xml
  app/src/main/res/values/styles_sepia.xml
Labels: Tweak

#68 Change inactive nav tab color to white50 for the dark/black mode
  app/src/main/res/color/color_state_nav_tab_dark.xml
Labels: Minor

#64 Tweaks: enhancing reading lists search
  app/build.gradle
  app/proguard-rules-debug.pro
  app/src/main/java/org/wikipedia/history/HistoryFragment.java
  app/src/main/java/org/wikipedia/history/SearchActionModeCallback.java
  app/src/main/java/org/wikipedia/language/LangLinksActivity.java
  app/src/main/java/org/wikipedia/language/LanguagesListActivity.java
  app/src/main/java/org/wikipedia/notifications/NotificationActivity.java
  app/src/main/java/org/wikipedia/readinglist/ReadingListActivity.java
  app/src/main/java/org/wikipedia/readinglist/ReadingListBehaviorsUtil.kt
  app/src/main/java/org/wikipedia/readinglist/ReadingListFragment.java
  app/src/main/java/org/wikipedia/readinglist/ReadingListsFragment.java
  app/src/main/java/org/wikipedia/views/PageItemView.java
  app/src/main/java/org/wikipedia/views/SearchActionProvider.java
  app/src/main/res/layout/group_search.xml
  app/src/main/res/layout/item_reading_list.xml
  app/src/main/res/values/styles.xml
Labels: Tweak

#88 Use proper margin values on list item views
  app/src/main/res/layout/item_reading_list.xml
  app/src/main/res/layout/view_list_card_item.xml
Labels: Minor

#89 Use themed drawable for the base style of DraweeViewPlaceholder
  app/src/main/res/layout/dialog_link_preview.xml
  app/src/main/res/layout/group_captcha.xml
  app/src/main/res/layout/item_on_this_day_pages.xml
  app/src/main/res/layout/item_page_list_entry.xml
  app/src/main/res/layout/item_search_result.xml
  app/src/main/res/layout/view_description_edit.xml
  app/src/main/res/layout/view_floating_queue.xml
  app/src/main/res/layout/view_list_card_item.xml
  app/src/main/res/values/styles.xml
Labels: Bug, Minor

#91 Follow up of update Info/help screen concept
  app/src/main/java/org/wikipedia/editactionfeed/EditTasksFragment.java
  app/src/main/res/drawable/ic_info_outline_themed_24dp.xml
  app/src/main/res/menu/menu_edit_tasks.xml
Labels: Minor

#102 Hide find in editor button in preview screen.
  app/src/main/java/org/wikipedia/edit/EditSectionActivity.java
Labels: Bug, Minor

#109 Fix: master branch build failed
  app/src/main/java/org/wikipedia/descriptions/DescriptionEditActivity.java
  app/src/main/java/org/wikipedia/descriptions/DescriptionEditFragment.java
  app/src/main/java/org/wikipedia/descriptions/DescriptionEditView.java
  app/src/main/java/org/wikipedia/editactionfeed/AddTitleDescriptionsFragment.kt
  app/src/main/java/org/wikipedia/page/PageFragment.java
Labels: Bug

#125 Expand the width of "More like this" view
  app/src/main/res/layout/view_list_card.xml
Labels: Minor

#124 Add RTL support for views
  app/src/main/java/org/wikipedia/feed/becauseyouread/BecauseYouReadCardView.java
  app/src/main/java/org/wikipedia/feed/mostread/MostReadFragment.java
  app/src/main/java/org/wikipedia/feed/news/NewsFragment.java
  app/src/main/java/org/wikipedia/page/ReferenceDialog.java
  app/src/main/java/org/wikipedia/page/tabs/TabActivity.java
  app/src/main/java/org/wikipedia/search/SearchFragment.java
  app/src/main/java/org/wikipedia/search/SearchResultsFragment.java
Labels: Minor

#131 Minor follow-up to API call
  app/src/main/java/org/wikipedia/dataclient/Service.java
Labels: Minor
