Repository wikimedia/apps-android-wikipedia, pull requests merged in 2019-05, with the labels that each got.

#244 Clean up unused floating queue view resources
  app/src/main/res/values-qq/strings.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
Labels: Minor

#254 Hygiene: remove unused attritubes and resources
  app/src/main/res/drawable/tab_counts_shape_border_dark.xml
  app/src/main/res/drawable/tab_counts_shape_border_light.xml
  app/src/main/res/drawable/tab_item_bottom_gradient_light.xml
  app/src/main/res/drawable/tab_item_selector_dark.xml
  app/src/main/res/drawable/tab_item_selector_light.xml
  app/src/main/res/drawable/tab_item_shape_selected_dark.xml
  app/src/main/res/drawable/tab_item_shape_selected_light.xml
  app/src/main/res/drawable/toc_item_background_dark.xml
  app/src/main/res/drawable/toc_item_background_light.xml
  app/src/main/res/values/attrs.xml
  app/src/main/res/values/styles_dark.xml
  app/src/main/res/values/styles_light.xml
  app/src/main/res/values/styles_sepia.xml
Labels: Minor

#253 Hygiene: use correct default bookmark icon and clean up ReadMore task
  app/src/main/java/org/wikipedia/page/bottomcontent/MainPageReadMoreTopicTask.java
  app/src/main/res/drawable/ic_favorite_white_24dp.xml
  app/src/main/res/layout/item_page_list_entry.xml
Labels: Minor

#272 Fix ability to build app while offline.
  app/build.gradle
  build.gradle
  project.properties
Labels: High Priority

#283 Set scale type for CAPTCHA image to avoid image being cut off
  app/src/main/res/layout/group_captcha.xml
Labels: Bug

#282 Fix: incorrect toolbar opacity in PageActivity
  app/src/main/java/org/wikipedia/page/PageToolbarHideHandler.java
Labels: Bug

#274 Fix: first list item of BottomContentView is not clickable
  app/src/main/java/org/wikipedia/page/bottomcontent/BottomContentView.java
Labels: Bug, Minor

#300 Fix possible crash after submitting successful description edit.
  app/src/main/java/org/wikipedia/descriptions/DescriptionEditFragment.java
Labels: High Priority

#299 Replace negated isEmpty() to isNotEmpty() in ReadingListBehaviorsUtil
  app/src/main/java/org/wikipedia/readinglist/ReadingListBehaviorsUtil.kt
Labels: Minor

#303 Tweaks: use local variable and reorder the companion object
  app/src/main/java/org/wikipedia/onboarding/SuggestedEditsOnboardingActivity.kt
  app/src/main/java/org/wikipedia/onboarding/SuggestedEditsOnboardingFragment.kt
Labels: Minor

#302 Update the Gallery item XML layout format
  app/src/main/res/layout/fragment_gallery_item.xml
Labels: Minor

#313 Fix app shortcuts, which are currently broken.
  app/src/main/java/org/wikipedia/main/MainActivity.java
  app/src/main/java/org/wikipedia/search/SearchActivity.java
Labels: High Priority

#314 Correctly use static app shortcuts.
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/wikipedia/Constants.java
  app/src/main/java/org/wikipedia/activity/BaseActivity.java
  app/src/main/java/org/wikipedia/appshortcuts/AppShortcuts.kt
  app/src/main/java/org/wikipedia/main/MainFragment.java
  app/src/main/java/org/wikipedia/search/SearchActivity.java
  app/src/main/res/xml-v25/shortcuts.xml
Labels: High Priority

#323 Tweak: update tabBackgroundColor in TabActivity
  app/src/main/res/layout/activity_tabs.xml
Labels: Minor

#326 Fix: update unlock suggested edits preferences correctly.
  app/src/main/java/org/wikipedia/notifications/NotificationEditorTasksHandler.java
Labels: Minor

#327 Don't auto-capitalize sentences in the Description Edit box.
  app/src/main/res/layout/view_description_edit.xml
Labels: Minor

#325 Tweak: align voice input button to top, instead of bottom.
  app/src/main/res/layout/view_description_edit.xml
Labels: Minor
