Repository wikimedia/apps-android-wikipedia, pull requests merged in 2019-04, with the labels that each got.

#136 Add/update developer preference
  app/src/main/res/xml/developer_preferences.xml
Labels: Minor

#140 Remove onboarding dialogs and unused strings.
  app/src/main/java/org/wikipedia/editactionfeed/AddTitleDescriptionsFragment.kt
  app/src/main/java/org/wikipedia/settings/Prefs.java
  app/src/main/res/values-qq/strings.xml
  app/src/main/res/values/preference_keys.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/xml/developer_preferences.xml
Labels: Minor

#141 Tweak the logic of login/logout for SuggestedEdits
  app/src/main/java/org/wikipedia/editactionfeed/AddTitleDescriptionsActivity.kt
  app/src/main/java/org/wikipedia/editactionfeed/EditTasksFragment.java
  app/src/main/java/org/wikipedia/login/LoginActivity.java
  app/src/main/java/org/wikipedia/main/MainActivity.java
  app/src/main/java/org/wikipedia/main/MainDrawerView.java
  app/src/main/java/org/wikipedia/notifications/NotificationEditorTasksHandler.java
  app/src/main/java/org/wikipedia/settings/Prefs.java
  app/src/main/res/values/preference_keys.xml
  app/src/main/res/xml/developer_preferences.xml
Labels: Minor

#142 Update strings for suggested edits and remove unused strings
  app/src/main/java/org/wikipedia/descriptions/DescriptionEditLicenseView.kt
  app/src/main/java/org/wikipedia/descriptions/DescriptionEditReviewView.kt
  app/src/main/java/org/wikipedia/editactionfeed/EditTasksFragment.java
  app/src/main/java/org/wikipedia/editactionfeed/provider/MissingDescriptionProvider.kt
  app/src/main/res/values-qq/strings.xml
  app/src/main/res/values/strings.xml
Labels: Minor

#143 Tweak analytics funnel resetting logic in the correct place.
  app/src/main/java/org/wikipedia/analytics/SuggestedEditsFunnel.java
  app/src/main/java/org/wikipedia/editactionfeed/AddTitleDescriptionsFragment.kt
  app/src/main/java/org/wikipedia/editactionfeed/EditTasksActivity.java
Labels: Minor

#145 Remove PreBeta flag from suggested edits feature.
  app/src/main/java/org/wikipedia/main/MainActivity.java
  app/src/main/java/org/wikipedia/main/MainDrawerView.java
Labels: Minor

#144 Tiny design tweaks: elevation clipping and swipe refresh color.
  app/src/main/java/org/wikipedia/editactionfeed/EditTasksFragment.java
  app/src/main/java/org/wikipedia/editactionfeed/MyContributionsFragment.kt
  app/src/main/res/layout-land/fragment_add_title_descriptions.xml
  app/src/main/res/layout/fragment_add_title_descriptions.xml
Labels: Minor

#148 Update notification string and line height of dialog title for SuggestedEdits
  app/src/main/java/org/wikipedia/notifications/NotificationEditorTasksHandler.java
  app/src/main/res/layout/view_dialog_title_with_image.xml
Labels: Minor

#149 Update image resources for SuggestedEdits dialogs
  app/src/main/java/org/wikipedia/editactionfeed/AddTitleDescriptionsActivity.kt
  app/src/main/java/org/wikipedia/settings/DeveloperSettingsPreferenceLoader.java
  app/src/main/res/drawable/ic_illustration_description_edit_trophy.xml
  app/src/main/res/drawable/ic_unlock_illustration_add.xml
  app/src/main/res/drawable/ic_unlock_illustration_translate.xml
Labels: Minor

#150 Minor margin adjustment on 'Call to action' layout - Suggested Edits Translation
  app/src/main/res/layout-land/fragment_add_title_descriptions_item.xml
Labels: High Priority, Minor

#151 Capitalize descriptions in the card view and summary view of SuggestedEdits
  app/src/main/java/org/wikipedia/descriptions/DescriptionEditView.java
  app/src/main/java/org/wikipedia/editactionfeed/AddTitleDescriptionsItemFragment.kt
Labels: Minor

#156 Design tweaks: elevation clipping on Randomizer
  app/src/main/res/layout-land/fragment_random.xml
  app/src/main/res/layout/fragment_random.xml
Labels: Minor

#158 Changing dropdown caret tint - Suggested Edits Translation
  app/src/main/res/layout/fragment_add_title_descriptions.xml
Labels: High Priority, Minor

#161 Fix correct auto-launching of suggested editing subtasks.
  app/src/main/java/org/wikipedia/editactionfeed/EditTasksActivity.java
Labels: High Priority

#163 Fix clipping of buttons in theme picker and login / create account.
  app/src/main/res/layout/activity_create_account.xml
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/dialog_theme_chooser.xml
Labels: High Priority

#162 Fix image dimming in dark mode(s).
  app/src/main/assets/bundle.js
  app/src/main/java/org/wikipedia/page/PageFragmentLoadState.java
  www/js/sections.js
Labels: High Priority

#167 Show local language names in My Contributions.
  app/src/main/java/org/wikipedia/editactionfeed/MyContributionsFragment.kt
Labels: Minor

#168 Update OkHttp to 3.14.0.
  app/build.gradle
  app/src/main/java/org/wikipedia/dataclient/okhttp/OfflineCacheInterceptor.java
Labels: Minor

#170 Update margin above the divider - Suggested Edits
  app/src/main/res/layout-land/fragment_add_title_descriptions_item.xml
  app/src/main/res/layout/fragment_add_title_descriptions_item.xml
Labels: Minor

#172 Follow up: network interceptors to Kotlin
  app/src/main/java/org/wikipedia/WikipediaApp.java
  app/src/main/java/org/wikipedia/alphaupdater/AlphaUpdateChecker.java
  app/src/main/java/org/wikipedia/analytics/EventLoggingService.java
  app/src/main/java/org/wikipedia/dataclient/ServiceFactory.java
  app/src/main/java/org/wikipedia/dataclient/okhttp/OkHttpConnectionFactory.kt
  app/src/main/java/org/wikipedia/dataclient/okhttp/OkHttpWebViewClient.java
  app/src/main/java/org/wikipedia/savedpages/SavedPageSyncService.java
  app/src/main/java/org/wikipedia/settings/RemoteConfigRefreshTask.java
  app/src/test/java/org/wikipedia/test/MockWebServerTest.java
Labels: Minor

#85 Styles audit
  app/src/main/res/values/styles.xml
Labels: Minor

#176 Optimization: cache SimpleDateFormat objects.
  app/src/main/java/org/wikipedia/analytics/Funnel.java
  app/src/main/java/org/wikipedia/feed/announcement/Announcement.java
  app/src/main/java/org/wikipedia/notifications/Notification.java
  app/src/main/java/org/wikipedia/page/PageProperties.java
  app/src/main/java/org/wikipedia/readinglist/sync/ReadingListSyncAdapter.java
  app/src/main/java/org/wikipedia/util/DateUtil.java
  app/src/test/java/org/wikipedia/util/DateUtilTest.java
Labels: Minor

#177 Optimization: improve xml layout of OnThisDay card.
  app/src/main/java/org/wikipedia/feed/onthisday/OnThisDayCardView.java
  app/src/main/java/org/wikipedia/feed/view/HorizontalScrollingListCardView.java
  app/src/main/res/layout/view_card_on_this_day.xml
  app/src/main/res/layout/view_events_layout.xml
Labels: Minor

#178 Convert OnThisDay to Rx.
  app/src/main/java/org/wikipedia/dataclient/RestService.java
  app/src/main/java/org/wikipedia/feed/onthisday/OnThisDayFragment.java
Labels: Minor

#179 Convert feed availability client to Rx.
  app/src/main/java/org/wikipedia/dataclient/RestService.java
  app/src/main/java/org/wikipedia/feed/configure/ConfigureFragment.java
  app/src/main/java/org/wikipedia/feed/configure/FeedAvailability.java
  app/src/main/java/org/wikipedia/feed/configure/FeedAvailabilityClient.java
Labels: Minor

#183 Follow up of importing Android X libraries
  app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsAddDescriptionsFragment.kt
  app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsContributionsFragment.kt
Labels: Minor

#173 Fix: use the "redirected" text to request correct section data
  app/src/main/java/org/wikipedia/dataclient/mwapi/page/MwMobileViewPageLead.java
  app/src/main/java/org/wikipedia/edit/wikitext/WikitextClient.java
Labels: Minor

#194 Remove unused methods of showing tool bar in PageActivity/PageFragment
  app/src/main/java/org/wikipedia/page/PageActivity.java
  app/src/main/java/org/wikipedia/page/PageFragment.java
Labels: Minor

#193 Remove old app language code logic
  app/src/main/java/org/wikipedia/language/AppLanguageState.java
Labels: Minor

#192 Update and clean up the TODO comments in Gallery
  app/src/main/java/org/wikipedia/gallery/GalleryActivity.java
  app/src/main/java/org/wikipedia/gallery/GalleryItem.java
  app/src/main/java/org/wikipedia/gallery/GalleryThumbnailScrollView.java
Labels: Minor

#199 Use correct way of testing observable calls in GalleryClientTest
  app/src/test/java/org/wikipedia/gallery/GalleryClientTest.java
Labels: Minor

#201 Follow up of SuggestedEdits feed card
  app/src/main/java/org/wikipedia/feed/FeedFragment.java
  app/src/main/java/org/wikipedia/feed/suggestededits/SuggestedEditsCardView.kt
  app/src/main/java/org/wikipedia/feed/suggestededits/SuggestedEditsFeedClient.kt
Labels: Minor

#203 Follow up #2 of SuggestedEdits feed card
  app/src/main/java/org/wikipedia/Constants.java
  app/src/main/java/org/wikipedia/feed/FeedContentType.java
  app/src/main/java/org/wikipedia/feed/suggestededits/SuggestedEditsCard.kt
  app/src/main/java/org/wikipedia/feed/suggestededits/SuggestedEditsCardView.kt
  app/src/main/res/values-qq/strings.xml
  app/src/main/res/values/strings.xml
Labels: Minor

#210 Remove preBeta cards from Customize settings
  app/src/main/java/org/wikipedia/feed/FeedContentType.java
  app/src/main/java/org/wikipedia/feed/configure/ConfigureFragment.java
Labels: High Priority

#211 Follow-up to pre-beta feed cards.
  app/src/main/java/org/wikipedia/feed/FeedContentType.java
  app/src/main/java/org/wikipedia/feed/configure/ConfigureFragment.java
Labels: High Priority

#206 Remove unused views in fragment_page.xml
  app/src/main/res/layout/fragment_page.xml
Labels: Minor

#214 Use Constants.InvokeSource in RandomActivity
  app/src/main/java/org/wikipedia/Constants.java
  app/src/main/java/org/wikipedia/analytics/RandomizerFunnel.java
  app/src/main/java/org/wikipedia/feed/FeedFragment.java
  app/src/main/java/org/wikipedia/main/MainFragment.java
  app/src/main/java/org/wikipedia/random/RandomActivity.java
  app/src/main/java/org/wikipedia/random/RandomFragment.java
Labels: Minor, Tweak

#221 Update metrhods access level and add SupressLint for RTL settings in ToC
  app/src/main/java/org/wikipedia/page/ToCHandler.java
Labels: Minor

#224 Rename related layouts file names to suggested_edits
  app/src/main/java/org/wikipedia/feed/suggestededits/SuggestedEditsCardView.kt
  app/src/main/java/org/wikipedia/onboarding/SuggestedEditsOnboardingFragment.kt
  app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsAddDescriptionsFragment.kt
  app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsAddDescriptionsItemFragment.kt
  app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsContributionsFragment.kt
  app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsTaskView.java
  app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsTasksFragment.java
  app/src/main/res/layout-land/fragment_suggested_edits_add_descriptions.xml
  app/src/main/res/layout-land/fragment_suggested_edits_add_descriptions_item.xml
  app/src/main/res/layout/fragment_suggested_edits_add_descriptions.xml
  app/src/main/res/layout/fragment_suggested_edits_add_descriptions_item.xml
  app/src/main/res/layout/fragment_suggested_edits_contributions.xml
  app/src/main/res/layout/fragment_suggested_edits_onboarding.xml
  app/src/main/res/layout/fragment_suggested_edits_tasks.xml
  app/src/main/res/layout/view_suggested_edits_task.xml
Labels: Minor

#225 Add Suggested edits onboarding preference into developer preferences settings screen
  app/src/main/res/xml/developer_preferences.xml
Labels: Minor

#230 Use view click listener to solve the conflict of actions in SearchResultsFragment
  app/src/main/java/org/wikipedia/search/SearchResultsFragment.java
Labels: Minor

#223 Update string values "Editor tasks" to "Suggested edits"
  app/src/main/res/values-qq/strings.xml
  app/src/main/res/values/strings.xml
Labels: Minor

#200 Use Constants.InvokeSource instead of SearchInvokeSource
  app/src/main/java/org/wikipedia/Constants.java
  app/src/main/java/org/wikipedia/analytics/SearchFunnel.java
  app/src/main/java/org/wikipedia/appshortcuts/AppShortcuts.kt
  app/src/main/java/org/wikipedia/main/MainFragment.java
  app/src/main/java/org/wikipedia/page/PageActivity.java
  app/src/main/java/org/wikipedia/search/SearchActivity.java
  app/src/main/java/org/wikipedia/search/SearchFragment.java
  app/src/main/java/org/wikipedia/search/SearchInvokeSource.java
  app/src/main/java/org/wikipedia/widgets/WidgetProviderSearch.java
Labels: Tweak

#236 Fix: apply theme to preview HTML correctly
  app/src/main/assets/preview.html
Labels: Bug, Minor

#237 Update preview HTML in /www folder.
  www/preview.html
Labels: Minor
