Repository wikimedia/apps-android-wikipedia, pull requests merged in 2019-12, with the labels that each got.

#799 Setting footer properly on mobile-html
  app/src/main/java/org/wikipedia/bridge/JavaScriptActionHandler.kt
Labels: mobile-html

#803 Collapse table correction
  app/src/main/java/org/wikipedia/bridge/JavaScriptActionHandler.kt
Labels: Minor, mobile-html

#810 Hygiene: update deprecated code and methods access level
  app/src/main/java/org/wikipedia/random/RandomFragment.java
  app/src/main/java/org/wikipedia/random/RandomItemFragment.java
Labels: Minor

#812 Hygiene: reduce redundant code and use StringBuilder to build summary string in EditPreviewFragment
  app/src/main/java/org/wikipedia/edit/preview/EditPreviewFragment.java
Labels: Minor

#809 Hygiene: replace old codes and add null checks to Gallery classes
  app/src/main/java/org/wikipedia/gallery/GalleryActivity.java
  app/src/main/java/org/wikipedia/gallery/GalleryItemFragment.java
Labels: Minor

#811 Remove unused parameter in CommunicationBridge
  app/src/main/java/org/wikipedia/bridge/CommunicationBridge.java
  app/src/main/java/org/wikipedia/edit/preview/EditPreviewFragment.java
  app/src/main/java/org/wikipedia/page/PageFragment.java
Labels: mobile-html

#816 Show link preview dialog title correctly
  app/src/main/java/org/wikipedia/page/linkpreview/LinkPreviewDialog.java
Labels: mobile-html

#800 Handle read more links properly on mobile-html
  app/src/main/java/org/wikipedia/bridge/JavaScriptActionHandler.kt
  app/src/main/java/org/wikipedia/page/LinkHandler.java
  app/src/main/java/org/wikipedia/page/Page.java
Labels: mobile-html

#805 Pre settings
  app/src/main/java/org/wikipedia/bridge/CommunicationBridge.java
  app/src/main/java/org/wikipedia/bridge/JavaScriptActionHandler.kt
  app/src/main/java/org/wikipedia/edit/preview/EditPreviewFragment.java
  app/src/main/java/org/wikipedia/page/PageFragment.java
  app/src/main/java/org/wikipedia/page/PageFragmentLoadState.java
  app/src/main/java/org/wikipedia/page/leadimages/LeadImagesHandler.java
Labels: mobile-html

#817 Fix table-of-contents link to "About this article" footer.
  app/src/main/java/org/wikipedia/bridge/JavaScriptActionHandler.kt
  app/src/main/java/org/wikipedia/page/ToCHandler.java
Labels: mobile-html

#818 Don't hide the WebView while loading the article.
  app/src/main/java/org/wikipedia/page/PageFragment.java
Labels: mobile-html

#819 Animate layout changes in Lead Image container.
  app/src/main/res/layout/view_page_header.xml
Labels: mobile-html

#820 Reformat the JS string in setUp() and use Kotlin string template
  app/src/main/java/org/wikipedia/bridge/JavaScriptActionHandler.kt
Labels: mobile-html

#823 Use Gson for deserializing bridge messages.
  app/src/main/java/org/wikipedia/bridge/CommunicationBridge.java
  app/src/main/java/org/wikipedia/edit/EditHandler.java
  app/src/main/java/org/wikipedia/page/LinkHandler.java
  app/src/main/java/org/wikipedia/page/PageFragment.java
Labels: mobile-html

#825 User proper article title to request reset html
  app/src/main/java/org/wikipedia/page/PageFragmentLoadState.java
Labels: mobile-html

#836 Hygiene: remove unused class and its layout
  app/src/main/java/org/wikipedia/page/IssuesListAdapter.java
  app/src/main/res/layout/item_issue.xml
Labels: Minor

#834 Hygiene: suppress unused warning, remove empty line and add NonNull annotation
  app/src/main/java/org/wikipedia/bridge/CommunicationBridge.java
Labels: Minor, mobile-html

#838 Fix: don't scroll Feed to the top every time the fragment resumes.
  app/src/main/java/org/wikipedia/main/MainFragment.java
Labels: High Priority

#832 Add Pre-setting parameters for Lead image and user groups
  app/src/main/java/org/wikipedia/bridge/JavaScriptActionHandler.kt
  app/src/main/java/org/wikipedia/page/PageFragment.java
Labels: mobile-html

#550 POST call for rendering Preview html
  app/src/main/java/org/wikipedia/dataclient/RestService.java
  app/src/main/java/org/wikipedia/dataclient/okhttp/OkHttpWebViewClient.java
  app/src/main/java/org/wikipedia/edit/preview/EditPreviewFragment.java
Labels: mobile-html

#829 Add .svg image url support for mobile-html
  app/src/main/java/org/wikipedia/edit/preview/EditPreviewFragment.java
  app/src/main/java/org/wikipedia/notifications/NotificationItemActionsDialog.java
  app/src/main/java/org/wikipedia/page/LinkHandler.java
  app/src/main/java/org/wikipedia/page/PageFragment.java
Labels: mobile-html

#842 Fix: press back causes a crash on GalleryActivity while the image is loading
  app/src/main/java/org/wikipedia/gallery/GalleryActivity.java
Labels: High Priority

#835 Hygiene: add annotations and remove redundent logic
  app/src/main/java/org/wikipedia/page/ExtendedBottomSheetDialogFragment.java
  app/src/main/java/org/wikipedia/page/GeoUnmarshaller.java
  app/src/main/java/org/wikipedia/page/ViewHideHandler.java
Labels: Minor

#849 Show article title HTML tag properly on the feature article card
  app/src/main/java/org/wikipedia/feed/featured/FeaturedArticleCardView.java
Labels: mobile-html

#848 Use the same method on opening GalleryActivity
  app/src/main/java/org/wikipedia/page/PageFragment.java
Labels: mobile-html

#850 Sending proper title object to the resetHTML()
  app/src/main/java/org/wikipedia/bridge/CommunicationBridge.java
  app/src/main/java/org/wikipedia/page/PageFragmentLoadState.java
Labels: mobile-html

#854 Use encodeURL to encode special strings
  app/src/main/java/org/wikipedia/bridge/CommunicationBridge.java
Labels: mobile-html

#855 Use Kotlin getter on getting resources
  app/src/main/java/org/wikipedia/bridge/JavaScriptActionHandler.kt
Labels: Minor, mobile-html
