Repository wikimedia/apps-android-wikipedia, pull requests merged in 2019-11, with the labels that each got.

#737 Treat timeout as recoverable error when saving offline articles.
  app/src/main/java/org/wikipedia/savedpages/SavedPageSyncService.java
Labels: High Priority

#738 Fix further native linking errors in Fresco.
  app/build.gradle
  app/src/main/java/org/wikipedia/WikipediaApp.java
Labels: High Priority

#740 Show date above the fundraising card on Explore feed
  app/src/main/java/org/wikipedia/feed/FeedCoordinatorBase.java
Labels: Minor

#749 Prevent showing the error page when the user has no edits
  app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsTasksFragment.kt
Labels: Minor

#752 Hygiene: move clear history logic into callback method
  app/src/main/java/org/wikipedia/history/HistoryFragment.java
  app/src/main/java/org/wikipedia/main/MainFragment.java
Labels: Minor

#753 Remove deprecated setUserVisibleHint()
  app/src/main/java/org/wikipedia/feed/FeedFragment.java
  app/src/main/java/org/wikipedia/history/HistoryFragment.java
  app/src/main/java/org/wikipedia/readinglist/ReadingListsFragment.java
Labels: Minor

#562 Fix language variants issue on LinkHandler
  app/src/main/java/org/wikipedia/page/LinkHandler.java
Labels: mobile-html

#762 Fix: properly set tint on menu icons.
  app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsCardsActivity.kt
  app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsTasksFragment.kt
  app/src/main/java/org/wikipedia/util/ResourceUtil.java
Labels: High Priority

#763 Use displayTitle on the title view to prevent the variant issue in Randomizer card
  app/src/main/java/org/wikipedia/random/RandomItemFragment.java
Labels: Minor

#544 Mobile html: Attempt to Render page better
  app/src/main/java/org/wikipedia/page/PageFragment.java
  app/src/main/java/org/wikipedia/page/leadimages/LeadImagesHandler.java
  app/src/main/java/org/wikipedia/page/shareafact/ShareHandler.java
Labels: Minor, mobile-html

#766 Minor string update
  app/src/main/java/org/wikipedia/dataclient/okhttp/HttpStatusException.java
  app/src/main/java/org/wikipedia/page/linkpreview/LinkPreviewContents.java
  app/src/main/java/org/wikipedia/readinglist/sync/ReadingListSyncAdapter.java
Labels: Minor

#558 Show the ErrorView if received a bad response from the endpoint
  app/src/main/java/org/wikipedia/dataclient/okhttp/OkHttpWebViewClient.java
  app/src/main/java/org/wikipedia/page/PageFragment.java
Labels: mobile-html

#775 Fix: adding HTML support on the "read more" item title
  app/src/main/java/org/wikipedia/page/bottomcontent/BottomContentView.java
Labels: Minor

#777 Display HTML-converted title in Randomizer cards.
  app/src/main/java/org/wikipedia/dataclient/restbase/page/RbPageSummary.java
  app/src/main/java/org/wikipedia/random/RandomItemFragment.java
Labels: High Priority

#786 Increase onboarding snackbar time to 7 seconds.
  app/src/main/java/org/wikipedia/main/MainFragment.java
Labels: High Priority

#785 Check whether the user is blocked on Wikidata and Commons.
  app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsUserStats.kt
Labels: High Priority

#789 Final minor verbiage tweaks.
  app/src/main/java/org/wikipedia/main/MainFragment.java
  app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsTasksFragment.kt
  app/src/main/java/org/wikipedia/util/FeedbackUtil.java
  app/src/main/res/values/strings.xml
Labels: High Priority

#784 Change pagelib to pcs for mobile html interaction requests
  app/src/main/java/org/wikipedia/bridge/JavaScriptActionHandler.kt
Labels: mobile-html

#795 Wire up the AnnouncementDialog to feed eventlogging.
  app/src/main/java/org/wikipedia/feed/model/CardType.java
  app/src/main/java/org/wikipedia/page/AnnouncementDialog.kt
Labels: High Priority
