Repository wikimedia/apps-android-wikipedia, pull requests merged in 2019-09, with the labels that each got.

#619 Minor unwanted code removal
  app/src/main/java/org/wikipedia/page/PageActivity.java
  app/src/main/java/org/wikipedia/settings/Prefs.java
  app/src/main/res/values/preference_keys.xml
Labels: Minor

#627 Quick follow-up to varianttitles.
  app/src/main/java/org/wikipedia/dataclient/mwapi/MwQueryPage.java
Labels: Minor

#629 Hygiene: fix manifest warnings.
  app/src/main/AndroidManifest.xml
Labels: Minor

#634 Snackbar for Suggested Edits survey
  app/src/main/java/org/wikipedia/Constants.java
  app/src/main/java/org/wikipedia/WikipediaApp.java
  app/src/main/java/org/wikipedia/descriptions/DescriptionEditFragment.java
  app/src/main/java/org/wikipedia/feed/FeedFragment.java
  app/src/main/java/org/wikipedia/main/MainFragment.java
  app/src/main/java/org/wikipedia/settings/Prefs.java
  app/src/main/java/org/wikipedia/util/DateUtil.java
  app/src/main/java/org/wikipedia/util/FeedbackUtil.java
  app/src/main/res/drawable/ic_open_in_new_accent_24.xml
  app/src/main/res/values-qq/strings.xml
  app/src/main/res/values/preference_keys.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/strings_no_translate.xml
Labels: High Priority

#638 Minor design changes
  app/src/main/java/org/wikipedia/WikipediaApp.java
  app/src/main/res/values-sw600dp/dimens.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/styles.xml
Labels: High Priority, Minor

#655 Fix incorrect button backgrounds in Lollipop.
  app/src/main/res/values/styles.xml
Labels: High Priority

#656 Improve fix of WebView loading on Lollipop.
  app/src/main/java/org/wikipedia/page/PageActivity.java
  app/src/main/java/org/wikipedia/views/ObservableWebView.java
Labels: High Priority
