Repository wikimedia/apps-android-wikipedia, pull requests merged in 2019-07, with the labels that each got.

#435 Fix: make sure the button on the Suggested edit dialogs lead to the correct screens
  app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsTasksActivity.java
Labels: Minor

#332 Fix: deep link action will open a new tab
  app/src/main/java/org/wikipedia/page/PageActivity.java
Labels: Minor

#438 Upgrade wikimedia-page-library version to 8.0.0
  app/src/main/assets/bundle.js
  app/src/main/assets/preview.js
  app/src/main/assets/wikimedia-page-library.css
  www/package-lock.json
  www/package.json
Labels: DO NOT MERGE

#443 Fix: use landscape specific layout for proper imageView aspect ratio in Randomizer
  app/src/main/java/org/wikipedia/random/RandomItemFragment.java
Labels: Minor

#456 Remove the method of importing old reading lists
  app/src/main/java/org/wikipedia/readinglist/database/ReadingListPageTable.java
Labels: Minor

#455 Fix: incorrect empty image position for default list in the reading list page
  app/src/main/res/layout/item_reading_list.xml
Labels: Minor

#461 Make the text with external link icon in imagePreviewDialog unselectable
  app/src/main/java/org/wikipedia/views/ImagePreviewDialog.kt
Labels: Minor

#468 Update SuggestedEditItem from Java to Kotlin
  app/src/main/java/org/wikipedia/suggestededits/provider/SuggestedEditItem.java
  app/src/main/java/org/wikipedia/suggestededits/provider/SuggestedEditItem.kt
Labels: Minor

#466 Fix: click on chips in reading list search results should be able to go to the list
  app/src/main/java/org/wikipedia/history/HistoryFragment.java
  app/src/main/java/org/wikipedia/page/bottomcontent/BottomContentView.java
  app/src/main/java/org/wikipedia/readinglist/ReadingListFragment.java
  app/src/main/java/org/wikipedia/readinglist/ReadingListsFragment.java
  app/src/main/java/org/wikipedia/views/PageItemView.java
Labels: Minor

#476 Fix error info that comes from LoginClient.
  app/src/main/java/org/wikipedia/login/LoginClient.java
Labels: High Priority

#478 Fix possible crash when launching from VIEW intent.
  app/src/main/java/org/wikipedia/page/PageActivity.java
Labels: High Priority

#496 No more GruntFile and related js files
  www/.eslintrc.json
  www/.jsonlintignore
  www/Gruntfile.js
  www/index.html
  www/js/actions.js
  www/js/bridge.js
  www/js/editaction.js
  www/js/issues.js
  www/js/main.js
  www/js/preview.js
  www/js/rtlsupport.js
  www/js/sections.js
  www/js/transformer.js
  www/js/transforms/collapseTables.js
  www/js/transforms/fixAudio.js
  www/js/transforms/hideImages.js
  www/js/transforms/hideRefs.js
  www/js/transforms/service/anchorPopUpMediaTransforms.js
  www/js/transforms/service/relocateFirstParagraph.js
  www/js/transforms/widenImages.js
  www/js/utilities.js
  www/package-lock.json
  www/package.json
  www/preview.html
  www/tests/index.html
  www/tests/inject.js
  www/tests/pingback.js
Labels: DO NOT MERGE

#504 Use Kotlin string template and unify the styles in JavaScriptActionHandler.setFooter()
  app/src/main/java/org/wikipedia/bridge/JavaScriptActionHandler.kt
Labels: Minor

#508 Show helper text when editing article description
  app/src/main/java/org/wikipedia/descriptions/DescriptionEditView.java
  app/src/main/res/values-qq/strings.xml
  app/src/main/res/values/strings.xml
Labels: High Priority

#509 Update old codes and simplify methods in GalleryActivity
  app/src/main/java/org/wikipedia/gallery/GalleryActivity.java
Labels: Minor

#513 Show progress bar when loading page summary in DescriptionEditFragment
  app/src/main/java/org/wikipedia/descriptions/DescriptionEditFragment.java
Labels: Minor

#242 Integrate with References endpoint
  app/src/main/java/org/wikipedia/dataclient/RestService.java
  app/src/main/java/org/wikipedia/page/PageFragment.java
  app/src/main/java/org/wikipedia/page/ReferenceHandler.java
  app/src/main/java/org/wikipedia/page/references/ReferenceDialog.java
  app/src/main/java/org/wikipedia/page/references/References.java
Labels: mobile-html

#515 Tweak: hide description view after added the caption
  app/src/main/java/org/wikipedia/descriptions/DescriptionEditView.java
  app/src/main/java/org/wikipedia/page/leadimages/LeadImagesHandler.java
Labels: High Priority

#516 Fix crash and refresh page if an image caption has been added in Gallery
  app/src/main/java/org/wikipedia/gallery/GalleryActivity.java
  app/src/main/java/org/wikipedia/page/PageActivity.java
Labels: High Priority

#517 Fix: check "redirected" filename correctly in GalleryActivity
  app/src/main/java/org/wikipedia/gallery/GalleryActivity.java
Labels: High Priority

#518 CTA consistency between article and galley
  app/src/main/java/org/wikipedia/gallery/GalleryActivity.java
  app/src/main/res/layout/activity_gallery.xml
Labels: High Priority
