Repository wikimedia/apps-android-wikipedia, pull requests merged in 2020-09, with the labels that each got.

#1632 Fix: crash when clicking on the "More like this" button in the trending card
  app/src/main/java/org/wikipedia/feed/featured/FeaturedArticleCard.java
  app/src/main/java/org/wikipedia/feed/image/FeaturedImageCard.java
  app/src/main/java/org/wikipedia/feed/mostread/MostReadListCard.java
  app/src/main/java/org/wikipedia/feed/news/NewsListCard.java
  app/src/main/java/org/wikipedia/feed/onthisday/OnThisDayCard.java
  app/src/main/java/org/wikipedia/feed/suggestededits/SuggestedEditsCard.kt
Labels: High Priority

#1639 Fix icon colors in Notification preferences.
  app/src/main/java/org/wikipedia/settings/NotificationSettingsPreferenceLoader.java
Labels: Minor

#1638 Improve query of local language names.
  app/src/main/res/values/languages_list.xml
  scripts/generate_wiki_languages.py
Labels: Minor

#1643 Fix crash when zooming image in Image Tags interface.
  app/src/main/res/layout/fragment_suggested_edits_cards_item.xml
  app/src/main/res/layout/fragment_suggested_edits_image_tags_item.xml
Labels: High Priority

#1644 Remove unwanted log from MediaListItem.java
  app/src/main/java/org/wikipedia/gallery/MediaListItem.java
Labels: Minor

#1657 Fix: properly set up PageTitle from ReadingListPage object
  app/src/main/java/org/wikipedia/readinglist/database/ReadingListDbHelper.java
Labels: High Priority

#1647 Pulse animation
  app/src/main/java/org/wikipedia/feed/onthisday/OnThisDayFragment.java
  app/src/main/res/anim/pulse.xml
  app/src/main/res/layout/view_on_this_day_event.xml
Labels: Experimental

#1670 Unused code
  app/src/main/java/org/wikipedia/page/PageActivity.java
Labels: Minor

#1671 Tweak: remove unwanted dividers in ListCardView
  app/src/main/java/org/wikipedia/feed/view/ListCardView.java
Labels: Minor
