Repository wikimedia/apps-android-wikipedia, pull requests merged in 2020-01, with the labels that each got.

#862 Remove namespace when setting new API text to PageTitle in LinkPreviewDialog
  app/src/main/java/org/wikipedia/page/linkpreview/LinkPreviewDialog.java
Labels: Minor

#867 Properly internationalize strings sent via Setup and Footer.
  app/src/main/java/org/wikipedia/bridge/CommunicationBridge.java
  app/src/main/java/org/wikipedia/bridge/JavaScriptActionHandler.kt
  app/src/main/java/org/wikipedia/edit/preview/EditPreviewFragment.java
  app/src/main/java/org/wikipedia/page/PageFragment.java
Labels: mobile-html

#868 Remove unused parameter from setFooter()
  app/src/main/java/org/wikipedia/bridge/JavaScriptActionHandler.kt
  app/src/main/java/org/wikipedia/page/PageFragmentLoadState.java
Labels: Minor, mobile-html

#864 Set up the footer license text and URL action properly
  app/src/main/java/org/wikipedia/bridge/JavaScriptActionHandler.kt
  app/src/main/java/org/wikipedia/page/PageFragment.java
  app/src/main/res/values-qq/strings.xml
  app/src/main/res/values/strings.xml
Labels: mobile-html

#875 Remove style tags from HTML text
  app/src/main/java/org/wikipedia/page/references/ReferenceDialog.java
  app/src/main/java/org/wikipedia/util/StringUtil.java
Labels: mobile-html

#877 Remove unused variables and class from PageFragmentLoadState
  app/src/main/java/org/wikipedia/page/PageFragment.java
  app/src/main/java/org/wikipedia/page/PageFragmentLoadState.java
Labels: mobile-html

#680 Handle page revision to get correct resposes from endpoints
  app/src/main/java/org/wikipedia/bridge/JavaScriptActionHandler.kt
  app/src/main/java/org/wikipedia/dataclient/RestService.java
  app/src/main/java/org/wikipedia/dataclient/page/PageSummary.java
  app/src/main/java/org/wikipedia/gallery/GalleryActivity.java
  app/src/main/java/org/wikipedia/page/PageFragment.java
  app/src/main/java/org/wikipedia/page/leadimages/LeadImagesHandler.java
  app/src/main/java/org/wikipedia/page/linkpreview/LinkPreviewDialog.java
  app/src/test/java/org/wikipedia/gallery/GalleryClientTest.java
Labels: mobile-html

#879 Hygiene: reformat and remove unused variables
  app/src/main/java/org/wikipedia/createaccount/CreateAccountSuccessResult.kt
  app/src/main/java/org/wikipedia/feed/suggestededits/SuggestedEditsCard.kt
  app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsTask.kt
Labels: Minor

#883 Analytics fix: use updated FindInPage schema.
  app/src/main/java/org/wikipedia/analytics/FindInPageFunnel.java
Labels: High Priority

#882 Design tweak: reading list onboarding button style.
  app/src/main/res/layout/view_onboarding.xml
Labels: Minor

#881 Fix: suggested Edits analytics not working
  app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsTasksFragment.kt
Labels: High Priority

#874 Add pop-up list of references.
  app/src/main/java/org/wikipedia/bridge/JavaScriptActionHandler.kt
  app/src/main/java/org/wikipedia/page/PageActivity.java
  app/src/main/java/org/wikipedia/page/PageFragment.java
  app/src/main/java/org/wikipedia/page/references/ReferenceListDialog.kt
  app/src/main/res/drawable/ic_arrow_up_alt_24px.xml
  app/src/main/res/drawable/ic_arrow_upward_black_24dp.xml
  app/src/main/res/drawable/ic_oojs_references.xml
  app/src/main/res/layout/dialog_reference_list.xml
  app/src/main/res/layout/item_reference.xml
Labels: mobile-html

#878 No longer load Main Page in empty tabs.
  app/src/main/java/org/wikipedia/Constants.java
  app/src/main/java/org/wikipedia/page/PageActivity.java
  app/src/main/java/org/wikipedia/page/PageFragment.java
  app/src/main/java/org/wikipedia/page/PageFragmentLoadState.java
  app/src/main/java/org/wikipedia/page/tabs/TabActivity.java
  app/src/main/res/layout/fragment_page.xml
  app/src/main/res/values-qq/strings.xml
  app/src/main/res/values/strings.xml
Labels: mobile-html

#802 Page load without PageLead
  app/src/main/java/org/wikipedia/bridge/JavaScriptActionHandler.kt
  app/src/main/java/org/wikipedia/dataclient/RestService.java
  app/src/main/java/org/wikipedia/dataclient/page/PageClient.java
  app/src/main/java/org/wikipedia/dataclient/page/PageSummary.java
  app/src/main/java/org/wikipedia/dataclient/page/Protection.java
  app/src/main/java/org/wikipedia/descriptions/DescriptionEditFragment.java
  app/src/main/java/org/wikipedia/feed/suggestededits/SuggestedEditsFeedClient.kt
  app/src/main/java/org/wikipedia/page/GeoUnmarshaller.java
  app/src/main/java/org/wikipedia/page/Page.java
  app/src/main/java/org/wikipedia/page/PageFragment.java
  app/src/main/java/org/wikipedia/page/PageFragmentLoadState.java
  app/src/main/java/org/wikipedia/page/PageProperties.java
  app/src/main/java/org/wikipedia/page/Section.java
  app/src/main/java/org/wikipedia/page/ToCHandler.java
  app/src/main/java/org/wikipedia/page/linkpreview/LinkPreviewDialog.java
  app/src/main/java/org/wikipedia/savedpages/SavedPageSyncService.java
  app/src/main/java/org/wikipedia/settings/DeveloperSettingsPreferenceLoader.java
  app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsCardsItemFragment.kt
  app/src/main/java/org/wikipedia/suggestededits/provider/MissingDescriptionProvider.kt
Labels: mobile-html

#885 Follow-up to Page Load without PageLead.
  app/src/main/java/org/wikipedia/bridge/JavaScriptActionHandler.kt
  app/src/main/java/org/wikipedia/dataclient/RestService.java
  app/src/main/java/org/wikipedia/dataclient/page/PageClient.java
  app/src/main/java/org/wikipedia/descriptions/DescriptionEditFragment.java
  app/src/main/java/org/wikipedia/feed/suggestededits/SuggestedEditsFeedClient.kt
  app/src/main/java/org/wikipedia/page/PageFragmentLoadState.java
  app/src/main/java/org/wikipedia/page/linkpreview/LinkPreviewDialog.java
  app/src/main/java/org/wikipedia/savedpages/SavedPageSyncService.java
  app/src/main/java/org/wikipedia/settings/DeveloperSettingsPreferenceLoader.java
  app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsCardsItemFragment.kt
  app/src/main/java/org/wikipedia/suggestededits/provider/MissingDescriptionProvider.kt
Labels: mobile-html

#887 Show higher resolution for the lead image
  app/src/main/java/org/wikipedia/page/PageProperties.java
Labels: mobile-html

#546 Fetching and caching infrastructure for mobile-html
  app/src/main/java/org/wikipedia/dataclient/RestService.java
  app/src/main/java/org/wikipedia/gallery/MediaListItem.java
  app/src/main/java/org/wikipedia/page/PageCacher.java
  app/src/main/java/org/wikipedia/page/PageFragmentLoadState.java
  app/src/main/java/org/wikipedia/savedpages/PageComponentsUrlParser.java
  app/src/main/java/org/wikipedia/savedpages/SavedPageSyncService.java
Labels: mobile-html

#894 Prevent crashes when loading page
  app/src/main/java/org/wikipedia/page/PageFragment.java
  app/src/main/java/org/wikipedia/page/PageFragmentLoadState.java
Labels: High Priority
