Repository wikimedia/apps-android-wikipedia, pull requests merged in 2020-11, with the labels that each got.

#1752 Minor: design change of OTD card view
  app/src/main/res/layout/item_on_this_day_pages.xml
Labels: Minor

#1761 Search ui fix - Redesign
  app/src/main/java/org/wikipedia/history/HistoryFragment.java
  app/src/main/res/layout/view_history_header_with_search.xml
Labels: High Priority

#1763 Tweak: optimize ripple effect in black theme
  app/src/main/java/org/wikipedia/feed/featured/FeaturedArticleCardView.java
  app/src/main/java/org/wikipedia/feed/suggestededits/SuggestedEditsCardItemFragment.kt
  app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsTaskView.kt
  app/src/main/java/org/wikipedia/views/WikiCardView.kt
  app/src/main/res/drawable/ripple_background.xml
  app/src/main/res/drawable/ripple_background_borderless.xml
  app/src/main/res/layout-sw600dp/view_suggested_edits_task_item.xml
  app/src/main/res/layout/fragment_suggested_edits_card_item.xml
  app/src/main/res/layout/item_on_this_day_pages.xml
  app/src/main/res/layout/view_card_featured_article.xml
  app/src/main/res/layout/view_card_featured_image.xml
  app/src/main/res/layout/view_horizontal_scroll_list_item_card.xml
  app/src/main/res/layout/view_list_card.xml
  app/src/main/res/layout/view_suggested_edits_task_item.xml
  app/src/main/res/values/styles.xml
Labels: High Priority

#1762 Feed reDesign: Rearrange cards
  app/src/main/java/org/wikipedia/feed/FeedContentType.java
Labels: High Priority

#1767 Use proper suffix for pageviews in the top read list items
  app/src/main/java/org/wikipedia/feed/view/ListCardItemView.java
  app/src/main/res/values-qq/strings.xml
  app/src/main/res/values/strings.xml
Labels: Minor

#1720 Add Event Platform Client
  app/build.gradle
  app/src/main/java/org/wikipedia/WikipediaApp.java
  app/src/main/java/org/wikipedia/analytics/eventplatform/DestinationEventService.java
  app/src/main/java/org/wikipedia/analytics/eventplatform/Event.java
  app/src/main/java/org/wikipedia/analytics/eventplatform/EventPlatformClient.java
  app/src/main/java/org/wikipedia/analytics/eventplatform/EventPlatformClientIntegration.java
  app/src/main/java/org/wikipedia/analytics/eventplatform/EventService.java
  app/src/main/java/org/wikipedia/analytics/eventplatform/EventServiceResponse.java
  app/src/main/java/org/wikipedia/analytics/eventplatform/SamplingConfig.java
  app/src/main/java/org/wikipedia/analytics/eventplatform/StreamConfig.java
  app/src/main/java/org/wikipedia/connectivity/NetworkConnectivityReceiver.java
  app/src/main/java/org/wikipedia/dataclient/Service.java
  app/src/main/java/org/wikipedia/dataclient/mwapi/MwStreamConfigsResponse.java
  app/src/main/java/org/wikipedia/settings/DeveloperSettingsPreferenceLoader.java
  app/src/main/java/org/wikipedia/settings/Prefs.java
  app/src/main/res/values/dev_settings_strings.xml
  app/src/main/res/values/preference_keys.xml
  app/src/main/res/xml/developer_preferences.xml
  app/src/test/java/org/wikipedia/analytics/eventplatform/EventPlatformClientIntegrationTest.java
  app/src/test/java/org/wikipedia/analytics/eventplatform/EventPlatformClientTest.java
  app/src/test/java/org/wikipedia/analytics/eventplatform/SamplingConfigTest.java
  app/src/test/java/org/wikipedia/analytics/eventplatform/StreamConfigTest.java
  app/src/test/java/org/wikipedia/connectivity/NetworkConnectivityReceiverTest.java
  app/src/test/res/raw/streamconfigs_response.json
Labels: WIP

#1780 Fix possible silent crash when filtering reading lists.
  app/src/main/java/org/wikipedia/readinglist/ReadingListsFragment.java
Labels: High Priority

#1783 Fix: reset margins to zero in the Announcement dialog on the article screen
  app/src/main/java/org/wikipedia/feed/announcement/AnnouncementCardView.java
Labels: High Priority

#1808 Fix possible crash from tab removal conditions.
  app/src/main/java/org/wikipedia/page/PageFragment.java
Labels: High Priority

#1811 Simplify and reduce jankiness of feed-to-page transition animation.
  app/src/main/java/org/wikipedia/Constants.java
  app/src/main/java/org/wikipedia/main/MainFragment.java
  app/src/main/java/org/wikipedia/page/PageActivity.java
  app/src/main/java/org/wikipedia/page/PageFragment.java
  app/src/main/java/org/wikipedia/views/WikiArticleCardView.kt
  app/src/main/res/layout/activity_page.xml
Labels: High Priority

#1812 Fix: prevent in the news card item text being cut off.
  app/src/main/res/layout/view_horizontal_scroll_list_item_card.xml
Labels: High Priority

#1819 Follow-up to overflow menu changes: Minor renaming
  app/src/main/res/menu/menu_tabs.xml
  app/src/main/res/values-qq/strings.xml
  app/src/main/res/values/strings.xml
Labels: Minor

#1826 Update Login and CreateAccount schema revisions.
  app/src/main/java/org/wikipedia/analytics/CreateAccountFunnel.java
  app/src/main/java/org/wikipedia/analytics/LoginFunnel.java
Labels: High Priority

#1825 Follow-up to creating "Saved" list.
  app/src/main/java/org/wikipedia/page/PageFragment.java
  app/src/main/java/org/wikipedia/readinglist/AddToReadingListDialog.java
Labels: High Priority
