Repository wikimedia/apps-android-wikipedia, pull requests merged in 2022-11, with the labels that each got.

#3664 Update kotlin to 1.7.20.
  build.gradle
Labels: Minor

#3642 Add option to delete multiple lists
  app/src/main/java/org/wikipedia/readinglist/ReadingListBehaviorsUtil.kt
  app/src/main/java/org/wikipedia/readinglist/ReadingListsFragment.kt
  app/src/main/res/menu/menu_action_mode_reading_lists.xml
  app/src/main/res/values-qq/strings.xml
  app/src/main/res/values/strings.xml
Labels: Design review

#3667 Hygiene: use getOrNull() for tabs in PageFragmentLoadState.kt
  app/src/main/java/org/wikipedia/page/PageFragmentLoadState.kt
Labels: Minor

#3672 Use correct invokeSource in UserContribListActivity.
  app/src/main/java/org/wikipedia/history/HistoryEntry.kt
  app/src/main/java/org/wikipedia/usercontrib/UserContribListActivity.kt
Labels: Minor

#3665 Survey for sharing reading lists.
  app/src/main/java/org/wikipedia/activity/BaseActivity.kt
  app/src/main/java/org/wikipedia/readinglist/ReadingListsShareHelper.kt
  app/src/main/java/org/wikipedia/readinglist/ReadingListsSurveyHelper.kt
  app/src/main/java/org/wikipedia/settings/Prefs.kt
  app/src/main/res/values-qq/strings.xml
  app/src/main/res/values/preference_keys.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/xml/developer_preferences.xml
Labels: WIP

#3681 Use ActivityResultContracts in LinkPreviewDialog
  app/src/main/java/org/wikipedia/page/linkpreview/LinkPreviewDialog.kt
Labels: Minor

#3683 Revision id update for Schema:MobileWikiAppReadingLists
  app/src/main/java/org/wikipedia/analytics/ReadingListsFunnel.kt
Labels: Minor

#3682 Follow-up to latency logging.
  app/src/main/java/org/wikipedia/analytics/SessionFunnel.kt
  app/src/main/java/org/wikipedia/dataclient/okhttp/OkHttpWebViewClient.kt
Labels: Minor

#3686 Improve retrieving rich-text displayTitles from API calls.
  app/src/main/java/org/wikipedia/dataclient/Service.kt
  app/src/main/java/org/wikipedia/util/StringUtil.kt
Labels: Minor

#3685 Fix searching for keywords within displayTitles.
  app/src/main/java/org/wikipedia/history/db/HistoryEntryWithImageDao.kt
  app/src/main/java/org/wikipedia/readinglist/db/ReadingListPageDao.kt
  app/src/main/java/org/wikipedia/search/SearchResultsFragment.kt
  app/src/main/java/org/wikipedia/util/StringUtil.kt
Labels: High Priority

#3690 Strip html styles when inserting links in editor.
  app/src/main/java/org/wikipedia/edit/WikiTextKeyboardView.kt
Labels: Minor

#3694 Factor out a string constant.
  app/src/main/java/org/wikipedia/dataclient/SharedPreferenceCookieManager.java
  app/src/main/java/org/wikipedia/dataclient/WikiSite.kt
  app/src/main/java/org/wikipedia/main/MainActivity.kt
  app/src/main/java/org/wikipedia/util/UriUtil.kt
Labels: Minor

#3693 Fix: don't check for explicit storage permission in API 33+.
  app/src/main/java/org/wikipedia/gallery/GalleryItemFragment.kt
  app/src/main/java/org/wikipedia/main/MainFragment.kt
Labels: Minor

#3698 Split off Reading Lists surveys into two independent surveys.
  app/src/main/java/org/wikipedia/activity/BaseActivity.kt
  app/src/main/java/org/wikipedia/readinglist/ReadingListsFragment.kt
  app/src/main/java/org/wikipedia/readinglist/ReadingListsReceiveSurveyHelper.kt
  app/src/main/java/org/wikipedia/readinglist/ReadingListsShareHelper.kt
  app/src/main/java/org/wikipedia/readinglist/ReadingListsShareSurveyHelper.kt
  app/src/main/java/org/wikipedia/settings/Prefs.kt
  app/src/main/res/values/preference_keys.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/xml/developer_preferences.xml
Labels: High Priority
