Repository wikimedia/apps-android-wikipedia, pull requests merged in 2022-06, with the labels that each got.

#3370 Fix API call for edit history forward/back navigation.
  app/src/main/java/org/wikipedia/dataclient/Service.kt
Labels: High Priority

#3375 Fix deduplication of search results.
  app/src/main/java/org/wikipedia/search/SearchResultsFragment.kt
Labels: Minor

#3373 Add a bit of horizontal padding to PageActionTab items.
  app/src/main/java/org/wikipedia/page/PageActionTabLayout.kt
Labels: Minor

#3377 Tweak style of "add languages" button in Recent Searches.
  app/src/main/res/layout/fragment_search_recent.xml
Labels: Minor

#3379 Fix placement of Contribution History circle button.
  app/src/main/res/layout/fragment_suggested_edits_tasks.xml
Labels: Minor

#3380 Follow-up to breadcrumbs.
  app/src/main/java/org/wikipedia/activity/BaseActivity.kt
  app/src/main/java/org/wikipedia/analytics/eventplatform/BreadCrumbLogEvent.kt
  app/src/main/java/org/wikipedia/analytics/eventplatform/BreadCrumbViewUtil.kt
  app/src/main/java/org/wikipedia/navtab/MenuNavTabDialog.kt
  app/src/main/java/org/wikipedia/onboarding/OnboardingFragment.kt
  app/src/main/java/org/wikipedia/page/PageActivity.kt
  app/src/main/java/org/wikipedia/settings/LogoutPreference.kt
  app/src/main/java/org/wikipedia/settings/PreferenceMultiLine.kt
  app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsTasksFragment.kt
  app/src/main/java/org/wikipedia/util/FeedbackUtil.kt
  app/src/main/java/org/wikipedia/views/ViewUtil.kt
  app/src/main/res/values/strings_no_translate.xml
Labels: High Priority

#3391 Don't display Undo button on the initial revision.
  app/src/main/java/org/wikipedia/diff/ArticleEditDetailsFragment.kt
Labels: Minor

#3389 Add a couple of missing usages of fromHtml().
  app/src/main/java/org/wikipedia/language/LangLinksActivity.kt
  app/src/main/java/org/wikipedia/page/leadimages/LeadImagesHandler.kt
Labels: Minor

#3399 Follow-up to updated contribution icons.
  app/src/main/java/org/wikipedia/userprofile/Contribution.kt
  app/src/main/java/org/wikipedia/userprofile/ContributionsFragment.kt
  app/src/main/java/org/wikipedia/userprofile/ContributionsItemView.kt
Labels: Minor

#3405 Blue reply button only on the first top-level talk topic.
  app/src/main/java/org/wikipedia/dataclient/discussiontools/ThreadItem.kt
  app/src/main/java/org/wikipedia/talk/TalkThreadItemView.kt
  app/src/main/java/org/wikipedia/talk/TalkTopicViewModel.kt
Labels: Minor

#3406 Fix RTL consistency in Talk activities, and menu order.
  app/src/main/java/org/wikipedia/talk/TalkReplyActivity.kt
  app/src/main/java/org/wikipedia/talk/TalkTopicActivity.kt
  app/src/main/java/org/wikipedia/talk/TalkTopicsActivity.kt
  app/src/main/res/layout/activity_talk_topics.xml
  app/src/main/res/menu/menu_talk.xml
  app/src/main/res/values/styles.xml
Labels: Minor

#3403 Fix association of Talk topic by ID.
  app/src/main/java/org/wikipedia/talk/TalkTopicActivity.kt
  app/src/main/java/org/wikipedia/talk/TalkTopicHolder.kt
  app/src/main/java/org/wikipedia/talk/TalkTopicViewModel.kt
  app/src/main/java/org/wikipedia/talk/TalkTopicsActivity.kt
Labels: Minor

#3402 Remove extraneous style tags when parsing Talk topics.
  app/src/main/java/org/wikipedia/talk/TalkThreadItemView.kt
Labels: Minor

#3410 Fix: make sure fontSize can be changed correctly
  app/src/main/java/org/wikipedia/WikipediaApp.kt
Labels: High Priority

#3414 Fix one more broken case of PageTitle equality.
  app/src/main/java/org/wikipedia/page/PageFragment.kt
  app/src/main/java/org/wikipedia/search/SearchResultsFragment.kt
Labels: High Priority

#3413 Follow-up to ConcatAdapter.
  app/src/main/java/org/wikipedia/page/SidePanelHandler.kt
  app/src/main/java/org/wikipedia/talk/TalkTopicHolder.kt
  app/src/main/java/org/wikipedia/talk/TalkTopicsActivity.kt
Labels: High Priority

#3415 Fix incorrect stream name of BreadcrumbEvent object.
  app/src/main/java/org/wikipedia/analytics/eventplatform/BreadCrumbLogEvent.kt
Labels: High Priority

#3417 Increase overflow button size to 48dp in talk page thread view
  app/src/main/res/layout/item_talk_thread_item.xml
Labels: Minor

#3423 Fix breadcrumbs schema, for real.
  app/src/main/java/org/wikipedia/analytics/eventplatform/BreadCrumbLogEvent.kt
Labels: Minor, High Priority

#3422 Fix warnings about multiple content roots.
  app/build.gradle
  app/src/test/java/org/wikipedia/test/TestWebServer.java
  app/src/testlib/java/org/wikipedia/testlib/TestConstants.java
  app/src/testlib/java/org/wikipedia/testlib/TestLatch.java
  gradle/src/checkstyle.gradle
Labels: Minor

#3420 Log different interface types when logging edit attempts.
  app/src/main/java/org/wikipedia/analytics/eventplatform/EditAttemptStepEvent.kt
  app/src/main/java/org/wikipedia/descriptions/DescriptionEditFragment.kt
  app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsImageTagsFragment.kt
Labels: Minor

#3425 Simplify flow of bumping versionCode.
  scripts/bump-version-code.py
Labels: Minor

#3445 Fix: load recent search content correctly when only one app langauge
  app/src/main/java/org/wikipedia/search/SearchFragment.kt
Labels: High Priority

#3446 Add marginEnd to the talk topics footer
  app/src/main/res/layout/view_talk_topics_footer.xml
Labels: Minor

#3450 Fix playback of timestamped WebM videos.
  app/src/main/java/org/wikipedia/dataclient/okhttp/OkHttpWebViewClient.kt
Labels: Minor
