Repository wikimedia/apps-android-wikipedia, pull requests merged in 2022-07, with the labels that each got.

#3454 Put Undo dialog contents in a ScrollView.
  app/src/main/res/layout/dialog_undo_edit.xml
Labels: Minor

#3458 Consolidate and prepare UserInfo model classes.
  app/src/main/java/org/wikipedia/createaccount/CreateAccountActivity.kt
  app/src/main/java/org/wikipedia/dataclient/Service.kt
  app/src/main/java/org/wikipedia/dataclient/mwapi/ListUserResponse.kt
  app/src/main/java/org/wikipedia/dataclient/mwapi/MwQueryResult.kt
  app/src/main/java/org/wikipedia/dataclient/mwapi/UserInfo.kt
  app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsTasksFragment.kt
Labels: Minor

#3463 Whoops: fix breadcrumbs serialization.
  app/src/main/java/org/wikipedia/analytics/eventplatform/BreadCrumbLogEvent.kt
Labels: Minor, High Priority

#3462 Fix detection and display of coffee-roll talk topics.
  app/src/main/java/org/wikipedia/talk/TalkTopicActivity.kt
Labels: Minor, High Priority

#3468 Fix minor inconsistencies in handling be-tarask language.
  app/src/main/java/org/wikipedia/language/AppLanguageLookUpTable.kt
  app/src/main/java/org/wikipedia/language/LangLinksActivity.kt
Labels: Minor

#3478 Improve/fix error handling when posting DiscussionTools edits.
  app/src/main/java/org/wikipedia/dataclient/discussiontools/DiscussionToolsEditResponse.kt
Labels: Minor

#3481 Rip out onboarding survey.
  app/src/main/java/org/wikipedia/onboarding/OnboardingSurveyHelper.kt
  app/src/main/java/org/wikipedia/page/PageActivity.kt
  app/src/main/java/org/wikipedia/settings/Prefs.kt
  app/src/main/res/values-ar/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-hi/strings.xml
  app/src/main/res/values-in/strings.xml
  app/src/main/res/values-ja/strings.xml
  app/src/main/res/values-mk/strings.xml
  app/src/main/res/values-qq/strings.xml
  app/src/main/res/values/preference_keys.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/xml/developer_preferences.xml
Labels: Minor, High Priority

#3495 Fix crash due to MEP sampling configuration.
  app/src/main/java/org/wikipedia/analytics/eventplatform/EventPlatformClient.kt
Labels: High Priority

#3500 Fix lint warnings in gradle file.
  app/build.gradle
Labels: Minor

#3499 Security fix: don't cache network replies with private CacheControl.
  app/src/main/java/org/wikipedia/dataclient/okhttp/CacheControlInterceptor.kt
Labels: Minor

#3501 Fix: talk page sorting function does not work properly
  app/src/main/java/org/wikipedia/views/TalkTopicsSortOverflowView.kt
Labels: Minor

#3503 Properly adjust displayTitle when setting namespace.
  app/src/main/java/org/wikipedia/page/PageTitle.kt
Labels: Minor

#3504 Fix crash when tapping certain Settings items.
  app/src/main/java/org/wikipedia/settings/PreferenceMultiLine.kt
Labels: High Priority
