Repository wikimedia/apps-android-wikipedia, pull requests merged in 2023-08, with the labels that each got.

#4108 Fix display of non-public revisions in Diff view.
  app/src/main/java/org/wikipedia/dataclient/Service.kt
  app/src/main/java/org/wikipedia/diff/ArticleEditDetailsFragment.kt
  app/src/main/java/org/wikipedia/diff/ArticleEditDetailsViewModel.kt
  app/src/main/res/layout/fragment_article_edit_details.xml
  app/src/main/res/values-qq/strings.xml
  app/src/main/res/values/strings.xml
Labels: Minor

#4111 Fix layout of edit history filter popup.
  app/src/main/res/layout/view_edit_history_filter_overflow.xml
Labels: Minor

#4112 Follow up: minor update of type definition in LangLinksViewModel
  app/src/main/java/org/wikipedia/language/LangLinksViewModel.kt
Labels: Minor

#4120 Hygiene: remove unused class and add private to some properties
  app/src/main/java/org/wikipedia/search/PrefixSearchResponse.kt
  app/src/main/java/org/wikipedia/search/SearchResultsViewModel.kt
Labels: Minor

#4090 Design tweaks: Image recs fullscreen onboarding
  app/src/main/res/layout/view_onboarding_page.xml
Labels: Design review

#4123 API underpinnings for Patroller tasks.
  app/src/main/java/org/wikipedia/dataclient/Service.kt
  app/src/main/java/org/wikipedia/dataclient/mwapi/MwQueryResult.kt
Labels: Minor

#4128 Fix background color and style of popup menus.
  app/src/main/res/menu/menu_category.xml
  app/src/main/res/menu/menu_edit_details.xml
  app/src/main/res/menu/menu_notifications.xml
  app/src/main/res/menu/menu_settings.xml
  app/src/main/res/menu/menu_talk.xml
  app/src/main/res/menu/menu_talk_thread_item.xml
  app/src/main/res/menu/menu_talk_topic.xml
  app/src/main/res/menu/menu_talk_topic_overflow.xml
  app/src/main/res/menu/menu_text_select.xml
  app/src/main/res/menu/menu_user_talk_popup.xml
  app/src/main/res/values/styles.xml
Labels: Minor

#4129 Use proper Toolbar in activitites that have overflow menus.
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/wikipedia/categories/CategoryActivity.kt
  app/src/main/java/org/wikipedia/edit/EditSectionActivity.kt
  app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsCardsFragment.kt
  app/src/main/java/org/wikipedia/suggestededits/SuggestionsActivity.kt
  app/src/main/res/layout/activity_category.xml
  app/src/main/res/layout/activity_edit_section.xml
  app/src/main/res/layout/fragment_suggested_edits_cards.xml
Labels: Minor

#4132 Update ktlint to 0.5.0.
  .editorconfig
  app/src/androidTest/java/org/wikipedia/TestUtil.kt
  app/src/androidTest/java/org/wikipedia/main/LoggedInTests.kt
  app/src/androidTest/java/org/wikipedia/main/SmokeTests.kt
  app/src/main/java/org/wikipedia/analytics/eventplatform/DestinationEventService.kt
  app/src/main/java/org/wikipedia/dataclient/okhttp/OkHttpWebViewClient.kt
  app/src/main/java/org/wikipedia/history/HistoryEntry.kt
  app/src/main/java/org/wikipedia/readinglist/ReadingListsShareHelper.kt
  gradle/src/ktlint.gradle
Labels: Minor

#4133 Update a few dependencies.
  app/build.gradle
  build.gradle
Labels: dependencies

#4135 Don't use MaterialDialogBuilder for announcement dialogs.
  app/src/main/java/org/wikipedia/page/AnnouncementDialog.kt
Labels: Minor, High Priority

#4136 Don't reload article unnecessarily when returning from Tabs.
  app/src/main/java/org/wikipedia/page/PageActivity.kt
  app/src/main/java/org/wikipedia/page/PageFragment.kt
  app/src/main/java/org/wikipedia/page/PageFragmentLoadState.kt
Labels: Minor

#4130 Update Snackbar styles per design.
  app/src/main/res/values/styles.xml
Labels: Minor

#4137 Fix sending of ReadingLists receive_start event.
  app/src/main/java/org/wikipedia/main/MainFragment.kt
Labels: High Priority

#4139 Set input field hint properly in TextInputDialog
  app/src/main/java/org/wikipedia/views/TextInputDialog.kt
Labels: Minor

#4140 Generalize composing feedback email.
  app/src/main/java/org/wikipedia/settings/AboutActivity.kt
  app/src/main/java/org/wikipedia/util/FeedbackUtil.kt
  app/src/main/res/values-qq/strings.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/strings_no_translate.xml
Labels: Minor

#4141 Correctly strip rich-text pasting on all API levels.
  app/src/main/java/org/wikipedia/views/PlainPasteEditText.kt
Labels: Minor

#4147 Change in edit comment tag naming order for IR
  app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsImageRecsFragment.kt
Labels: Minor

#4149 String resources for sending Report emails.
  app/src/main/res/values-qq/strings.xml
  app/src/main/res/values/strings.xml
Labels: Minor

#4148 Update gradle to 8.1.1.
  build.gradle
Labels: dependencies

#4150 Minor fix for notification lists in tests
  app/src/androidTest/java/org/wikipedia/database/AppDatabaseTests.kt
Labels: Minor

#4156 Remove unused views in the user contribution layout
  app/src/main/res/layout/activity_user_contrib.xml
Labels: Minor

#4159 Add additional required string for patroller tasks
  app/src/main/res/values-qq/strings.xml
  app/src/main/res/values/strings.xml
Labels: Minor

#4163 Upgrade target SDK to 34.
  app/build.gradle
  app/src/main/java/org/wikipedia/edit/SyntaxHighlightableEditText.kt
  app/src/main/java/org/wikipedia/views/SwipeableListView.kt
Labels: dependencies
