Repository wikimedia/apps-android-wikipedia, pull requests merged in 2023-12, with the labels that each got.

#4313 Fix playback of videos in Gallery.
  app/src/main/java/org/wikipedia/gallery/GalleryItemFragment.kt
  app/src/main/java/org/wikipedia/gallery/ImageInfo.kt
  app/src/main/java/org/wikipedia/gallery/MediaDownloadReceiver.kt
Labels: Minor, High Priority

#4311 Fix: make sure getting the coordinates from the page/summary endpoint
  app/src/main/java/org/wikipedia/bridge/JavaScriptActionHandler.kt
  app/src/main/java/org/wikipedia/dataclient/page/PageSummary.kt
  app/src/main/java/org/wikipedia/page/PageFragment.kt
  app/src/main/java/org/wikipedia/page/PageProperties.kt
  app/src/test/java/org/wikipedia/test/ParcelableTest.kt
Labels: High Priority

#4317 Further fix video playback!
  app/src/main/java/org/wikipedia/gallery/ImageInfo.kt
Labels: Minor, High Priority

#4325 Update gradle plugin to 8.2.0.
  app/build.gradle
  app/src/main/java/org/wikipedia/random/BottomViewBehavior.kt
  app/src/main/java/org/wikipedia/util/GeoUtil.kt
  build.gradle
Labels: Minor, dependencies

#4326 Fix showing link previews in EditSectionActivity.
  app/src/main/java/org/wikipedia/edit/EditSectionActivity.kt
Labels: Minor

#4333 Update donation URL to standardize utm_source parameter.
  app/src/main/java/org/wikipedia/navtab/MenuNavTabDialog.kt
  app/src/main/res/values/strings_no_translate.xml
Labels: Minor

#4309 Places: Clustering
  app/src/main/java/org/wikipedia/places/PlacesFragment.kt
Labels: Design review

#4337 No longer use `page/related` endpoint for Feed cards.
  app/src/main/java/org/wikipedia/dataclient/RestService.kt
  app/src/main/java/org/wikipedia/dataclient/Service.kt
  app/src/main/java/org/wikipedia/feed/becauseyouread/BecauseYouReadClient.kt
  app/src/test/java/org/wikipedia/search/RelatedPagesSearchClientTest.kt
Labels: Minor

#4339 Fix incorrect logic for showing Patroller Tasks feedback dialog.
  app/src/main/java/org/wikipedia/activity/FragmentUtil.kt
  app/src/main/java/org/wikipedia/diff/ArticleEditDetailsFragment.kt
  app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsCardsFragment.kt
Labels: High Priority

#4340 Patroller tasks: improve and update algorithm for fetching new changes.
  app/src/main/java/org/wikipedia/dataclient/Service.kt
  app/src/main/java/org/wikipedia/dataclient/mwapi/MwQueryResult.kt
  app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsRecentEditsViewModel.kt
  app/src/main/java/org/wikipedia/suggestededits/provider/EditingSuggestionsProvider.kt
Labels: High Priority

#4341 Tiny tweak: hide back/forward arrows while loading.
  app/src/main/java/org/wikipedia/diff/ArticleEditDetailsFragment.kt
Labels: Minor

#4342 Fix warning from gradle build variable.
  app/build.gradle
  gradle.properties
Labels: Minor

#4345 Remove unnecessary callbacks from LinkPreviewDialog.
  app/src/main/java/org/wikipedia/categories/CategoryActivity.kt
  app/src/main/java/org/wikipedia/descriptions/DescriptionEditActivity.kt
  app/src/main/java/org/wikipedia/diff/ArticleEditDetailsFragment.kt
  app/src/main/java/org/wikipedia/edit/EditSectionActivity.kt
  app/src/main/java/org/wikipedia/gallery/GalleryActivity.kt
  app/src/main/java/org/wikipedia/main/MainFragment.kt
  app/src/main/java/org/wikipedia/page/PageActivity.kt
  app/src/main/java/org/wikipedia/page/linkpreview/LinkPreviewDialog.kt
  app/src/main/java/org/wikipedia/talk/TalkReplyActivity.kt
  app/src/main/java/org/wikipedia/talk/TalkTopicActivity.kt
  app/src/main/java/org/wikipedia/talk/template/AddTemplateActivity.kt
Labels: Minor

#4346 Remove even more unnecessary callbacks from LinkPreviewDialog.
  app/src/main/java/org/wikipedia/categories/CategoryActivity.kt
  app/src/main/java/org/wikipedia/descriptions/DescriptionEditActivity.kt
  app/src/main/java/org/wikipedia/diff/ArticleEditDetailsFragment.kt
  app/src/main/java/org/wikipedia/edit/EditSectionActivity.kt
  app/src/main/java/org/wikipedia/gallery/GalleryActivity.kt
  app/src/main/java/org/wikipedia/main/MainFragment.kt
  app/src/main/java/org/wikipedia/page/PageActivity.kt
  app/src/main/java/org/wikipedia/page/linkpreview/LinkPreviewDialog.kt
  app/src/main/java/org/wikipedia/talk/TalkReplyActivity.kt
  app/src/main/java/org/wikipedia/talk/TalkTopicActivity.kt
  app/src/main/java/org/wikipedia/talk/template/AddTemplateActivity.kt
Labels: Minor
