Repository wikimedia/apps-android-wikipedia, pull requests merged in 2023-03, with the labels that each got.

#3860 Fix usage of non-default / beta base URL for MediaWiki.
  app/src/main/java/org/wikipedia/dataclient/ServiceFactory.kt
Labels: Minor

#3865 Update alias of releases server.
  upload-all.sh
Labels: Minor

#3866 Follow-up to revision API slots.
  app/src/main/java/org/wikipedia/dataclient/mwapi/MwQueryPage.kt
  app/src/main/java/org/wikipedia/descriptions/DescriptionEditFragment.kt
  app/src/main/java/org/wikipedia/edit/EditSectionActivity.kt
  app/src/main/java/org/wikipedia/page/edithistory/EditHistoryListViewModel.kt
  app/src/test/java/org/wikipedia/edit/wikitext/WikitextClientTest.kt
Labels: Minor

#3878 Update LeakCanary to 2.10.
  app/build.gradle
Labels: Minor

#3882 Extend survey dates for Reading Lists by 30 days.
  app/src/main/java/org/wikipedia/readinglist/ReadingListsReceiveSurveyHelper.kt
  app/src/main/java/org/wikipedia/readinglist/ReadingListsShareSurveyHelper.kt
Labels: Minor, High Priority

#3875 Machine generated article descriptions baseline data wiring
  app/src/main/java/org/wikipedia/analytics/eventplatform/MachineGeneratedArticleDescriptionsAnalyticsHelper.kt
  app/src/main/java/org/wikipedia/descriptions/DescriptionEditFragment.kt
Labels: High Priority

#3879 Analytics wiring for ReadingListSharing
  app/src/main/java/org/wikipedia/analytics/eventplatform/ReadingListsSharingAnalyticsHelper.kt
  app/src/main/java/org/wikipedia/main/MainFragment.kt
  app/src/main/java/org/wikipedia/readinglist/ReadingListActivity.kt
  app/src/main/java/org/wikipedia/readinglist/ReadingListFragment.kt
  app/src/main/java/org/wikipedia/readinglist/ReadingListsFragment.kt
  app/src/main/java/org/wikipedia/readinglist/ReadingListsReceiveSurveyHelper.kt
  app/src/main/java/org/wikipedia/readinglist/ReadingListsShareHelper.kt
  app/src/main/java/org/wikipedia/readinglist/ReadingListsShareSurveyHelper.kt
Labels: High Priority

#3884 Correctly respect user option to add edited pages to watchlist.
  app/src/main/java/org/wikipedia/dataclient/Service.kt
  app/src/main/java/org/wikipedia/dataclient/mwapi/UserInfo.kt
  app/src/main/java/org/wikipedia/edit/summaries/EditSummaryFragment.kt
Labels: Minor

#3885 Update imports and minor code clean up in AboutActivity
  app/src/main/java/org/wikipedia/settings/AboutActivity.kt
Labels: Minor

#3890 Fix potential minor crash when drawing Tab bitmap.
  app/src/main/java/org/wikipedia/page/tabs/TabActivity.kt
Labels: Minor

#3897 Fix ActionMode for reference backlinks.
  app/src/main/java/org/wikipedia/bridge/JavaScriptActionHandler.kt
  app/src/main/java/org/wikipedia/page/PageFragment.kt
Labels: High Priority

#3904 Fix/improve thumbnail URL transforming for certain URLs.
  app/src/main/java/org/wikipedia/util/ImageUrlUtil.kt
  app/src/test/java/org/wikipedia/util/ImageUriUtilTest.kt
Labels: Minor, High Priority

#3907 Remove HTML from Subject when sharing images.
  app/src/main/java/org/wikipedia/gallery/GalleryItemFragment.kt
Labels: Minor

#3915 Add special hash codes to edit summary when submitting machine suggestions.
  app/src/main/java/org/wikipedia/descriptions/DescriptionEditFragment.kt
  app/src/main/java/org/wikipedia/descriptions/DescriptionEditView.kt
Labels: Minor, High Priority

#3905 Onboarding data wiring and clean-up
  app/src/main/java/org/wikipedia/analytics/eventplatform/MachineGeneratedArticleDescriptionABCTest.kt
  app/src/main/java/org/wikipedia/analytics/eventplatform/MachineGeneratedArticleDescriptionsAnalyticsHelper.kt
  app/src/main/java/org/wikipedia/descriptions/DescriptionEditFragment.kt
  app/src/main/java/org/wikipedia/descriptions/DescriptionEditTutorialFragment.kt
  app/src/main/java/org/wikipedia/descriptions/DescriptionEditView.kt
  app/src/main/java/org/wikipedia/views/SuggestedArticleDescriptionsDialog.kt
  app/src/main/java/org/wikipedia/views/SuggestedArticleDescriptionsReportDialog.kt
  app/src/main/res/layout/view_description_edit.xml
Labels: High Priority

#3921 Follow-up to machine suggestion analytics.
  app/src/main/java/org/wikipedia/analytics/eventplatform/MachineGeneratedArticleDescriptionABCTest.kt
  app/src/main/java/org/wikipedia/analytics/eventplatform/MachineGeneratedArticleDescriptionsAnalyticsHelper.kt
  app/src/main/java/org/wikipedia/dataclient/wikidata/Entities.kt
  app/src/main/java/org/wikipedia/descriptions/DescriptionEditActivity.kt
  app/src/main/java/org/wikipedia/descriptions/DescriptionEditFragment.kt
  app/src/main/java/org/wikipedia/descriptions/DescriptionEditTutorialFragment.kt
  app/src/main/java/org/wikipedia/descriptions/DescriptionEditView.kt
  app/src/main/java/org/wikipedia/views/SuggestedArticleDescriptionsDialog.kt
  app/src/main/java/org/wikipedia/views/SuggestedArticleDescriptionsReportDialog.kt
Labels: Minor, High Priority

#3918 Design tweak for onboarding screen
  app/src/main/res/drawable/illustration_ai_article_descriptions.xml
  app/src/main/res/layout/inflate_description_edit_tutorial_page_three.xml
Labels: Minor, High Priority

#3922 Hide suggestedEditButton on api response error
  app/src/main/java/org/wikipedia/descriptions/DescriptionEditFragment.kt
Labels: Minor, High Priority

#3923 Data wiring updates:
  app/src/main/java/org/wikipedia/analytics/eventplatform/MachineGeneratedArticleDescriptionsAnalyticsHelper.kt
  app/src/main/java/org/wikipedia/descriptions/DescriptionEditFragment.kt
  app/src/main/java/org/wikipedia/descriptions/DescriptionEditView.kt
Labels: High Priority

#3924 Followup (final?) to machine suggestion analytics.
  app/src/main/java/org/wikipedia/analytics/eventplatform/ABTest.kt
  app/src/main/java/org/wikipedia/analytics/eventplatform/MachineGeneratedArticleDescriptionABCTest.kt
  app/src/main/java/org/wikipedia/analytics/eventplatform/MachineGeneratedArticleDescriptionsAnalyticsHelper.kt
  app/src/main/java/org/wikipedia/descriptions/DescriptionEditActivity.kt
  app/src/main/java/org/wikipedia/descriptions/DescriptionEditFragment.kt
  app/src/main/java/org/wikipedia/descriptions/DescriptionEditTutorialFragment.kt
  app/src/main/java/org/wikipedia/descriptions/DescriptionEditView.kt
  app/src/main/java/org/wikipedia/settings/Prefs.kt
  app/src/main/java/org/wikipedia/views/SuggestedArticleDescriptionsDialog.kt
  app/src/main/java/org/wikipedia/views/SuggestedArticleDescriptionsReportDialog.kt
  app/src/main/res/values/preference_keys.xml
Labels: High Priority

#3925 Follow up: Update timer logic
  app/src/main/java/org/wikipedia/analytics/eventplatform/MachineGeneratedArticleDescriptionsAnalyticsHelper.kt
  app/src/main/java/org/wikipedia/descriptions/DescriptionEditFragment.kt
Labels: High Priority

#3926 Final follow-up (for real!) to analytics.
  app/src/main/java/org/wikipedia/analytics/eventplatform/MachineGeneratedArticleDescriptionsAnalyticsHelper.kt
  app/src/main/java/org/wikipedia/descriptions/DescriptionEditFragment.kt
  app/src/main/java/org/wikipedia/util/ActiveTimer.kt
Labels: High Priority

#3927 Keeping a consistent delimiter between key : value pairs
  app/src/main/java/org/wikipedia/analytics/eventplatform/MachineGeneratedArticleDescriptionsAnalyticsHelper.kt
Labels: High Priority

#3917 Allow shared reading lists to be serialized as IDs or titles.
  app/src/main/java/org/wikipedia/dataclient/Service.kt
  app/src/main/java/org/wikipedia/readinglist/ReadingListsReceiveHelper.kt
  app/src/main/java/org/wikipedia/readinglist/ReadingListsShareHelper.kt
Labels: Minor

#3912 Add provenance parameter when sharing reading lists.
  app/src/main/java/org/wikipedia/readinglist/ReadingListsShareHelper.kt
Labels: Minor
