Repository wikimedia/apps-android-wikipedia, pull requests merged in 2023-09, with the labels that each got.

#4169 Fix possible crash due to Receiver on API 34.
  app/src/main/java/org/wikipedia/gallery/GalleryActivity.kt
  app/src/main/java/org/wikipedia/gallery/MediaDownloadReceiver.kt
  app/src/main/java/org/wikipedia/main/MainFragment.kt
Labels: High Priority

#4174 Update required string for Patroller Tasks
  app/src/main/res/values/strings.xml
Labels: Minor

#4183 Update a few dependencies.
  app/build.gradle
Labels: dependencies

#4186 Remove unnecessary function.
  app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsCardsFragment.kt
  app/src/main/java/org/wikipedia/util/ResourceUtil.kt
  app/src/main/res/menu/menu_suggested_edits.xml
Labels: Minor

#4191 Correctly set content directionality in Link Previews.
  app/src/main/java/org/wikipedia/page/linkpreview/LinkPreviewDialog.kt
Labels: Minor

#4153 Patroller Tasks: main "List of edits" screen
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/wikipedia/Constants.kt
  app/src/main/java/org/wikipedia/dataclient/Service.kt
  app/src/main/java/org/wikipedia/dataclient/mwapi/MwQueryResponse.kt
  app/src/main/java/org/wikipedia/dataclient/mwapi/MwQueryResult.kt
  app/src/main/java/org/wikipedia/history/HistoryEntry.kt
  app/src/main/java/org/wikipedia/settings/Prefs.kt
  app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsRecentEditsActivity.kt
  app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsRecentEditsFilterTypes.kt
  app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsRecentEditsFragment.kt
  app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsRecentEditsItemView.kt
  app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsRecentEditsViewModel.kt
  app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsTasksFragment.kt
  app/src/main/java/org/wikipedia/talk/UserTalkPopupHelper.kt
  app/src/main/java/org/wikipedia/usercontrib/UserInformationDialog.kt
  app/src/main/java/org/wikipedia/usercontrib/UserInformationDialogViewModel.kt
  app/src/main/java/org/wikipedia/util/DateUtil.kt
  app/src/main/res/drawable/ic_report_flag.xml
  app/src/main/res/drawable/ic_user_information.xml
  app/src/main/res/layout/dialog_user_information.xml
  app/src/main/res/layout/fragment_suggested_edits_recent_edits.xml
  app/src/main/res/layout/item_suggested_edits_recent_edits.xml
  app/src/main/res/layout/item_suggested_edits_recent_edits_date.xml
  app/src/main/res/layout/view_suggested_edits_recent_edits_search_bar.xml
  app/src/main/res/menu/menu_recent_edits.xml
  app/src/main/res/menu/menu_user_talk_popup.xml
  app/src/main/res/values/preference_keys.xml
Labels: WIP

#4192 Improve HTTP logging by inserting the interceptor at the right spot.
  app/src/main/java/org/wikipedia/dataclient/ServiceFactory.kt
  app/src/main/java/org/wikipedia/dataclient/okhttp/OkHttpConnectionFactory.kt
Labels: Minor

#4193 Update filter count related functions across the app
  app/src/main/java/org/wikipedia/notifications/NotificationActivity.kt
  app/src/main/java/org/wikipedia/notifications/NotificationFilterActivity.kt
  app/src/main/java/org/wikipedia/page/edithistory/EditHistoryListActivity.kt
  app/src/main/java/org/wikipedia/usercontrib/UserContribFilterActivity.kt
  app/src/main/java/org/wikipedia/usercontrib/UserContribListActivity.kt
  app/src/main/java/org/wikipedia/watchlist/WatchlistFilterActivity.kt
  app/src/main/java/org/wikipedia/watchlist/WatchlistFragment.kt
Labels: Minor

#4202 Remove hydrated Summary response from Reading List structure.
  app/src/main/java/org/wikipedia/readinglist/sync/ReadingListSyncAdapter.kt
  app/src/main/java/org/wikipedia/readinglist/sync/SyncedReadingLists.kt
Labels: Minor

#4204 Support `<code>` tags in native TextViews.
  app/src/main/java/org/wikipedia/richtext/CustomHtmlParser.kt
Labels: Minor

#4210 A few more string updates.
  app/src/main/res/values-qq/strings.xml
  app/src/main/res/values/strings.xml
Labels: Minor
