Repository wikimedia/apps-android-wikipedia, pull requests merged in 2023-04, with the labels that each got.

#3932 Only logged in users should be included in the experiment
  app/src/main/java/org/wikipedia/descriptions/DescriptionEditActivity.kt
  app/src/main/java/org/wikipedia/descriptions/DescriptionEditFragment.kt
Labels: Minor, High Priority

#3933 Fix: Show promise text at the correct place
  app/src/main/java/org/wikipedia/descriptions/DescriptionEditTutorialFragment.kt
  app/src/main/java/org/wikipedia/onboarding/OnboardingPageView.kt
  app/src/main/res/layout/inflate_description_edit_tutorial_page_three.xml
Labels: Minor, High Priority

#3935 Fix Watchlist defaults and filter count.
  app/src/main/java/org/wikipedia/watchlist/WatchlistFilterTypes.kt
  app/src/main/java/org/wikipedia/watchlist/WatchlistViewModel.kt
  app/src/main/res/values/preference_keys.xml
Labels: Minor

#3911 Remove usages of launchWhenCreated in lifecycleScopes.
  app/src/main/java/org/wikipedia/categories/CategoryActivity.kt
  app/src/main/java/org/wikipedia/edit/insertmedia/InsertMediaActivity.kt
  app/src/main/java/org/wikipedia/notifications/NotificationActivity.kt
  app/src/main/java/org/wikipedia/page/edithistory/EditHistoryListActivity.kt
  app/src/main/java/org/wikipedia/page/linkpreview/LinkPreviewDialog.kt
  app/src/main/java/org/wikipedia/search/SearchResultsFragment.kt
  app/src/main/java/org/wikipedia/talk/ArchivedTalkPagesActivity.kt
  app/src/main/java/org/wikipedia/talk/TalkTopicsActivity.kt
  app/src/main/java/org/wikipedia/usercontrib/UserContribListActivity.kt
  app/src/main/java/org/wikipedia/watchlist/WatchlistFragment.kt
Labels: Minor

#3936 Crash fix: Do not log api info for group 0 users
  app/src/main/java/org/wikipedia/analytics/eventplatform/MachineGeneratedArticleDescriptionsAnalyticsHelper.kt
Labels: High Priority

#3937 Fix: Do not assign group to users not in experiment
  app/src/main/java/org/wikipedia/analytics/eventplatform/MachineGeneratedArticleDescriptionsAnalyticsHelper.kt
Labels: High Priority

#3894 Reduce and update type styles
  app/src/main/java/org/wikipedia/descriptions/DescriptionEditView.kt
  app/src/main/java/org/wikipedia/edit/summaries/EditSummaryFragment.kt
  app/src/main/java/org/wikipedia/history/HistoryFragment.kt
  app/src/main/java/org/wikipedia/page/PageActionTabLayout.kt
  app/src/main/java/org/wikipedia/readinglist/ReadingListFragment.kt
  app/src/main/java/org/wikipedia/views/PageItemView.kt
  app/src/main/res/layout-land/view_onboarding_page.xml
  app/src/main/res/layout/activity_category.xml
  app/src/main/res/layout/activity_edit_history.xml
  app/src/main/res/layout/activity_notifications.xml
  app/src/main/res/layout/activity_reset_password.xml
  app/src/main/res/layout/activity_talk_topics.xml
  app/src/main/res/layout/activity_user_contrib.xml
  app/src/main/res/layout/dialog_article_descriptions.xml
  app/src/main/res/layout/dialog_with_checkbox.xml
  app/src/main/res/layout/fragment_feed.xml
  app/src/main/res/layout/fragment_history.xml
  app/src/main/res/layout/fragment_main.xml
  app/src/main/res/layout/fragment_reading_list.xml
  app/src/main/res/layout/fragment_reading_lists.xml
  app/src/main/res/layout/fragment_search_recent.xml
  app/src/main/res/layout/fragment_watchlist.xml
  app/src/main/res/layout/group_captcha.xml
  app/src/main/res/layout/item_edit_history_separator.xml
  app/src/main/res/layout/item_feed_content_type.xml
  app/src/main/res/layout/item_feed_content_type_lang_select_dialog.xml
  app/src/main/res/layout/item_langlinks_list_entry.xml
  app/src/main/res/layout/item_language_list_entry.xml
  app/src/main/res/layout/item_language_spinner.xml
  app/src/main/res/layout/item_notification.xml
  app/src/main/res/layout/item_notification_filter.xml
  app/src/main/res/layout/item_page_list_entry.xml
  app/src/main/res/layout/item_reading_list.xml
  app/src/main/res/layout/item_reading_list_preview_save_select_item.xml
  app/src/main/res/layout/item_search_result.xml
  app/src/main/res/layout/item_talk_thread_item.xml
  app/src/main/res/layout/item_user_contrib_filter.xml
  app/src/main/res/layout/item_watchlist.xml
  app/src/main/res/layout/item_watchlist_filter.xml
  app/src/main/res/layout/item_wikipedia_language.xml
  app/src/main/res/layout/view_card_accessibility.xml
  app/src/main/res/layout/view_card_header_large.xml
  app/src/main/res/layout/view_card_offline.xml
  app/src/main/res/layout/view_description_edit.xml
  app/src/main/res/layout/view_edit_history_empty_messages.xml
  app/src/main/res/layout/view_link_preview_error.xml
  app/src/main/res/layout/view_message_card.xml
  app/src/main/res/layout/view_onboarding_page.xml
  app/src/main/res/layout/view_reading_list_preview_save_dialog.xml
  app/src/main/res/layout/view_search_empty.xml
  app/src/main/res/layout/view_section_header.xml
  app/src/main/res/layout/view_suggested_edits_task_item.xml
  app/src/main/res/values/styles.xml
Labels: Design review

#3941 Convert all AlertDialogs to Material3 dialogs.
  app/src/main/java/org/wikipedia/activity/BaseActivity.kt
  app/src/main/java/org/wikipedia/createaccount/CreateAccountActivity.kt
  app/src/main/java/org/wikipedia/descriptions/DescriptionEditView.kt
  app/src/main/java/org/wikipedia/diff/ArticleEditDetailsFragment.kt
  app/src/main/java/org/wikipedia/diff/UndoEditDialog.kt
  app/src/main/java/org/wikipedia/edit/EditSectionActivity.kt
  app/src/main/java/org/wikipedia/edit/preview/EditPreviewFragment.kt
  app/src/main/java/org/wikipedia/feed/FeedFragment.kt
  app/src/main/java/org/wikipedia/feed/configure/ConfigureItemView.kt
  app/src/main/java/org/wikipedia/gallery/GalleryActivity.kt
  app/src/main/java/org/wikipedia/history/HistoryFragment.kt
  app/src/main/java/org/wikipedia/main/MainFragment.kt
  app/src/main/java/org/wikipedia/page/AnnouncementDialog.kt
  app/src/main/java/org/wikipedia/page/PageActivity.kt
  app/src/main/java/org/wikipedia/page/PageFragment.kt
  app/src/main/java/org/wikipedia/page/tabs/TabActivity.kt
  app/src/main/java/org/wikipedia/readinglist/ReadingListBehaviorsUtil.kt
  app/src/main/java/org/wikipedia/readinglist/ReadingListFragment.kt
  app/src/main/java/org/wikipedia/readinglist/ReadingListSyncBehaviorDialogs.kt
  app/src/main/java/org/wikipedia/readinglist/ReadingListsReceiveSurveyHelper.kt
  app/src/main/java/org/wikipedia/readinglist/ReadingListsShareSurveyHelper.kt
  app/src/main/java/org/wikipedia/readinglist/RemoveFromReadingListsDialog.kt
  app/src/main/java/org/wikipedia/search/RecentSearchesFragment.kt
  app/src/main/java/org/wikipedia/settings/DeveloperSettingsPreferenceLoader.kt
  app/src/main/java/org/wikipedia/settings/LogoutPreference.kt
  app/src/main/java/org/wikipedia/settings/SettingsPreferenceLoader.kt
  app/src/main/java/org/wikipedia/settings/languages/WikipediaLanguagesFragment.kt
  app/src/main/java/org/wikipedia/talk/TalkReplyActivity.kt
  app/src/main/java/org/wikipedia/talk/TalkTopicActivity.kt
  app/src/main/java/org/wikipedia/talk/UserTalkPopupHelper.kt
  app/src/main/java/org/wikipedia/views/EditNoticesDialog.kt
  app/src/main/java/org/wikipedia/views/SuggestedArticleDescriptionsDialog.kt
  app/src/main/java/org/wikipedia/views/SuggestedArticleDescriptionsReportDialog.kt
  app/src/main/res/drawable/dialog_16dp_radius_background.xml
  app/src/main/res/layout/dialog_article_descriptions.xml
  app/src/main/res/layout/dialog_description_suggestion_report.xml
  app/src/main/res/layout/dialog_with_checkbox.xml
  app/src/main/res/layout/view_card_announcement.xml
  app/src/main/res/values/styles.xml
Labels: Design review

#3945 Fix: hide descriptions button conditionally for group1 users
  app/src/main/java/org/wikipedia/descriptions/DescriptionEditFragment.kt
  app/src/main/java/org/wikipedia/descriptions/DescriptionEditView.kt
Labels: High Priority

#3948 Follow-up: remove useless layout.
  app/src/main/res/layout/dialog_article_descriptions.xml
Labels: Minor

#3949 Fix/update snackbar styles.
  app/src/main/res/values/styles.xml
Labels: Minor

#3950 Update dependencies.
  app/build.gradle
Labels: Minor

#3951 Fix swipe background of History items.
  app/src/main/java/org/wikipedia/views/PageItemView.kt
  app/src/main/res/layout/item_page_list_entry.xml
Labels: Minor

#3953 Adding feature specific translations
  app/src/main/res/values-ar/strings.xml
  app/src/main/res/values-cs/strings.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fi/strings.xml
  app/src/main/res/values-hi/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values-ja/strings.xml
  app/src/main/res/values-ko/strings.xml
  app/src/main/res/values-ro/strings.xml
  app/src/main/res/values-ru/strings.xml
  app/src/main/res/values-tr/strings.xml
  app/src/main/res/values-vi/strings.xml
  app/src/main/res/values-zh/strings.xml
Labels: High Priority

#3956 Dutch translations: Machine gen article descs
  app/src/main/res/values-nl/strings.xml
Labels: High Priority

#3962 Use non-transitive R classes.
  app/src/androidTest/java/org/wikipedia/main/LoggedInTests.kt
  app/src/androidTest/java/org/wikipedia/main/SmokeTests.kt
  app/src/androidTest/java/org/wikipedia/search/SearchExternalIntentTest.kt
  app/src/androidTest/java/org/wikipedia/search/SearchIntentTest.kt
  app/src/main/java/org/wikipedia/descriptions/DescriptionEditView.kt
  app/src/main/java/org/wikipedia/feed/view/ListCardItemView.kt
  app/src/main/java/org/wikipedia/notifications/NotificationCategory.kt
  app/src/main/java/org/wikipedia/notifications/NotificationFilterItemView.kt
  app/src/main/java/org/wikipedia/page/PageActionTabLayout.kt
  app/src/main/java/org/wikipedia/readinglist/ReadingListItemView.kt
  app/src/main/java/org/wikipedia/readinglist/ReadingListsFragment.kt
  app/src/main/java/org/wikipedia/richtext/CustomHtmlParser.kt
  app/src/main/java/org/wikipedia/settings/languages/WikipediaLanguagesItemView.kt
  app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsSurvey.kt
  app/src/main/java/org/wikipedia/usercontrib/UserContribFilterItemView.kt
  app/src/main/java/org/wikipedia/util/FeedbackUtil.kt
  app/src/main/java/org/wikipedia/views/CabSearchView.kt
  app/src/main/java/org/wikipedia/views/FindInPageActionProvider.kt
  app/src/main/java/org/wikipedia/views/NotificationButtonView.kt
  app/src/main/java/org/wikipedia/views/PageItemView.kt
  app/src/main/java/org/wikipedia/views/TabCountsView.kt
  app/src/main/java/org/wikipedia/watchlist/WatchlistFilterItemView.kt
  gradle.properties
Labels: Minor

#3963 Fix Espresso tests, and improve for Airplane mode.
  app/src/androidTest/java/org/wikipedia/TestUtil.kt
  app/src/androidTest/java/org/wikipedia/main/SmokeTests.kt
  app/src/androidTest/java/org/wikipedia/search/SearchIntentTest.kt
Labels: Minor

#3965 Add additional Reading Lists data wiring
  app/src/main/java/org/wikipedia/analytics/eventplatform/ReadingListsAnalyticsHelper.kt
  app/src/main/java/org/wikipedia/analytics/eventplatform/ReadingListsSharingAnalyticsHelper.kt
  app/src/main/java/org/wikipedia/main/MainFragment.kt
  app/src/main/java/org/wikipedia/readinglist/LongPressMenu.kt
  app/src/main/java/org/wikipedia/readinglist/ReadingListActivity.kt
  app/src/main/java/org/wikipedia/readinglist/ReadingListFragment.kt
  app/src/main/java/org/wikipedia/readinglist/ReadingListsExportImportHelper.kt
  app/src/main/java/org/wikipedia/readinglist/ReadingListsFragment.kt
  app/src/main/java/org/wikipedia/readinglist/ReadingListsReceiveSurveyHelper.kt
  app/src/main/java/org/wikipedia/readinglist/ReadingListsShareHelper.kt
  app/src/main/java/org/wikipedia/readinglist/ReadingListsShareSurveyHelper.kt
Labels: High Priority

#3968 Fix/mitigate background color when previewing edits in Dark mode.
  app/src/main/java/org/wikipedia/edit/preview/EditPreviewFragment.kt
Labels: Minor

#3967 Fix opening page from external link, when already exists in another tab.
  app/src/main/java/org/wikipedia/page/PageContainerLongPressHandler.kt
  app/src/main/java/org/wikipedia/page/PageFragment.kt
Labels: Minor

#3972 Revert "Use Files methods in OfflineCacheInterceptor. (#3874)"
  app/build.gradle
  app/src/main/java/org/wikipedia/dataclient/okhttp/OfflineCacheInterceptor.kt
Labels: Minor, High Priority

#3973 Fix search execution when entering from intent.
  app/src/main/java/org/wikipedia/search/SearchFragment.kt
Labels: Minor, High Priority

#3975 Copy change to edit warning
  app/src/main/res/values/strings.xml
Labels: Minor
