Repository wikimedia/apps-android-wikipedia, pull requests merged in 2023-02, with the labels that each got.

#3803 Follow-up to exporting reading lists.
  app/src/main/java/org/wikipedia/readinglist/ReadingListBehaviorsUtil.kt
  app/src/main/java/org/wikipedia/readinglist/ReadingListsExportImportHelper.kt
  app/src/main/java/org/wikipedia/util/FileUtil.kt
  app/src/main/res/values-qq/strings.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/strings_no_translate.xml
  app/src/main/res/values/styles.xml
Labels: Minor

#3804 Fix ability to share/receive a list with over 50 pages.
  app/src/main/java/org/wikipedia/readinglist/ReadingListsImportHelper.kt
  app/src/main/java/org/wikipedia/readinglist/ReadingListsShareHelper.kt
Labels: Minor, High Priority

#3800 Show the imported list immediately after imported list
  app/src/main/java/org/wikipedia/readinglist/ReadingListsFragment.kt
Labels: Minor

#3809 Correctly hide voice icon when voice input unavailable.
  app/src/main/java/org/wikipedia/descriptions/DescriptionEditView.kt
  app/src/main/java/org/wikipedia/history/HistoryFragment.kt
Labels: Minor

#3811 Follow-up to session schema.
  app/src/main/java/org/wikipedia/analytics/SessionData.kt
Labels: Minor

#3813 Follow-up to search results ViewModel
  app/src/main/java/org/wikipedia/search/SearchFragment.kt
  app/src/main/java/org/wikipedia/search/SearchResultsFragment.kt
  app/src/main/java/org/wikipedia/search/SearchResultsViewModel.kt
Labels: Minor

#3815 Follow-up: simplify reading list multi-selection.
  app/src/main/java/org/wikipedia/readinglist/ReadingListsFragment.kt
  app/src/main/res/menu/menu_action_mode_reading_lists.xml
Labels: Minor

#3816 Change ReadingListsImportHelper to ReadingListsReceiveHelper
  app/src/main/java/org/wikipedia/readinglist/ReadingListsFragment.kt
  app/src/main/java/org/wikipedia/readinglist/ReadingListsReceiveHelper.kt
Labels: Minor

#3824 Remove feature flag for Export/Imp lists
  app/src/main/java/org/wikipedia/readinglist/ReadingListItemView.kt
  app/src/main/java/org/wikipedia/views/ReadingListsOverflowView.kt
Labels: High Priority

#3825 Correctly wire up and reset sessionId and pageViewId for analytics.
  app/src/main/java/org/wikipedia/analytics/eventplatform/AppSessionEvent.kt
  app/src/main/java/org/wikipedia/analytics/eventplatform/EventPlatformClient.kt
  app/src/main/java/org/wikipedia/page/PageFragment.kt
Labels: High Priority

#3823 Update RxJava to 3.1.6 and RxAndroid to 3.0.2.
  app/build.gradle
Labels: Minor

#3833 Fix: explicitly invalidate main menu when switching tabs.
  app/src/main/java/org/wikipedia/main/MainFragment.kt
Labels: Minor

#3836 Fix: Overwriting of pages during RL export
  app/src/main/java/org/wikipedia/readinglist/ReadingListsExportImportHelper.kt
Labels: High Priority

#3844 Fix display of reading lists with very long titles or descriptions.
  app/src/main/java/org/wikipedia/readinglist/ReadingListHeaderView.kt
  app/src/main/res/layout/fragment_reading_list.xml
  app/src/main/res/layout/item_reading_list.xml
Labels: Minor

#3842 Fix possible failure to display notifications when Theme is unavailable.
  app/src/main/java/org/wikipedia/notifications/NotificationPresenter.kt
Labels: Minor, High Priority

#3843 Update MEP stream configs on a daily basis, instead of once ever.
  app/src/main/java/org/wikipedia/analytics/eventplatform/EventPlatformClient.kt
  app/src/main/java/org/wikipedia/recurring/DailyEventTask.kt
Labels: Minor

#3841 Minor cleanup of unnecessary static data in NotificationReceiver.
  app/src/main/java/org/wikipedia/notifications/NotificationPollBroadcastReceiver.kt
  app/src/main/java/org/wikipedia/notifications/PollNotificationWorker.kt
Labels: Minor

#3840 Fix extremely minor possible race condition.
  app/src/main/java/org/wikipedia/WikipediaApp.kt
Labels: Minor

#3846 Re-arranged reading list item pop-up menu
  app/src/main/res/menu/menu_reading_list_item.xml
Labels: Minor

#3847 Encode the talk topic title for sharing the topic link
  app/src/main/java/org/wikipedia/talk/TalkTopicActivity.kt
Labels: Minor
