Repository wikimedia/apps-android-wikipedia, pull requests merged in 2023-11, with the labels that each got.

#4262 Fix: make Patroller Tasks available only on Indonesian and Test wiki
  app/src/main/java/org/wikipedia/dataclient/Service.kt
  app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsRecentEditsFilterActivity.kt
  app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsRecentEditsViewModel.kt
  app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsTasksFragment.kt
  app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsTasksFragmentViewModel.kt
Labels: High Priority

#4274 Add a bottom gradient as scroll indicator
  app/src/main/res/layout/dialog_campaign.xml
Labels: High Priority

#4275 Fix: PT data string
  app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsRecentEditsOnboardingFragment.kt
Labels: Minor, High Priority

#4277 Fix: Minor changes PT Data
  app/src/main/java/org/wikipedia/analytics/eventplatform/PatrollerExperienceEvent.kt
  app/src/main/java/org/wikipedia/usercontrib/UserInformationDialog.kt
Labels: Minor, High Priority

#4279 Fix: Final touches to PT data
  app/src/main/java/org/wikipedia/diff/ArticleEditDetailsFragment.kt
  app/src/main/java/org/wikipedia/diff/ArticleEditDetailsViewModel.kt
  app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsRecentEditsFragment.kt
Labels: High Priority

#4297 Templates data fix
  app/src/main/java/org/wikipedia/talk/template/TalkTemplatesFragment.kt
Labels: Minor

#4300 Minor fix : DE wiki fix
  app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsTasksFragment.kt
Labels: High Priority
