Repository wikimedia/apps-android-wikipedia, pull requests merged in 2023-07, with the labels that each got.

#4073 Factor out intent parameters for Title and WikiSite.
  app/src/main/java/org/wikipedia/Constants.kt
  app/src/main/java/org/wikipedia/categories/CategoryActivity.kt
  app/src/main/java/org/wikipedia/categories/CategoryActivityViewModel.kt
  app/src/main/java/org/wikipedia/categories/CategoryDialog.kt
  app/src/main/java/org/wikipedia/categories/CategoryDialogViewModel.kt
  app/src/main/java/org/wikipedia/commons/FilePageActivity.kt
  app/src/main/java/org/wikipedia/commons/FilePageFragment.kt
  app/src/main/java/org/wikipedia/descriptions/DescriptionEditActivity.kt
  app/src/main/java/org/wikipedia/descriptions/DescriptionEditFragment.kt
  app/src/main/java/org/wikipedia/edit/EditSectionActivity.kt
  app/src/main/java/org/wikipedia/feed/news/NewsActivity.kt
  app/src/main/java/org/wikipedia/feed/news/NewsFragment.kt
  app/src/main/java/org/wikipedia/feed/news/NewsViewModel.kt
  app/src/main/java/org/wikipedia/feed/onthisday/OnThisDayActivity.kt
  app/src/main/java/org/wikipedia/feed/onthisday/OnThisDayFragment.kt
  app/src/main/java/org/wikipedia/gallery/GalleryActivity.kt
  app/src/main/java/org/wikipedia/gallery/GalleryItemFragment.kt
  app/src/main/java/org/wikipedia/language/LangLinksActivity.kt
  app/src/main/java/org/wikipedia/language/LangLinksViewModel.kt
  app/src/main/java/org/wikipedia/notifications/NotificationPollBroadcastReceiver.kt
  app/src/main/java/org/wikipedia/notifications/NotificationPresenter.kt
  app/src/main/java/org/wikipedia/page/PageActivity.kt
  app/src/main/java/org/wikipedia/page/edithistory/EditHistoryListActivity.kt
  app/src/main/java/org/wikipedia/page/edithistory/EditHistoryListViewModel.kt
  app/src/main/java/org/wikipedia/random/RandomActivity.kt
  app/src/main/java/org/wikipedia/random/RandomFragment.kt
  app/src/main/java/org/wikipedia/random/RandomItemFragment.kt
  app/src/main/java/org/wikipedia/talk/ArchivedTalkPagesActivity.kt
  app/src/main/java/org/wikipedia/talk/ArchivedTalkPagesViewModel.kt
  app/src/main/java/org/wikipedia/talk/TalkReplyActivity.kt
  app/src/main/java/org/wikipedia/talk/TalkReplyViewModel.kt
  app/src/main/java/org/wikipedia/talk/TalkTopicActivity.kt
  app/src/main/java/org/wikipedia/talk/TalkTopicViewModel.kt
  app/src/main/java/org/wikipedia/talk/TalkTopicsActivity.kt
  app/src/main/java/org/wikipedia/widgets/WidgetProviderFeaturedPage.kt
Labels: Minor

#4074 Underpinnings/preludes/fixes to proper insertion of images.
  app/src/main/java/org/wikipedia/dataclient/Service.kt
  app/src/main/java/org/wikipedia/dataclient/mwapi/MwQueryResult.kt
  app/src/main/java/org/wikipedia/edit/EditSectionActivity.kt
  app/src/main/java/org/wikipedia/edit/insertmedia/InsertMediaActivity.kt
  app/src/main/java/org/wikipedia/edit/insertmedia/InsertMediaViewModel.kt
Labels: Minor

#4078 Design tweak: snackbar styles.
  app/src/main/java/org/wikipedia/util/FeedbackUtil.kt
  app/src/main/res/values/styles.xml
Labels: Minor

#4077 Stop using Summary endpoint for getting LangLinks variants.
  app/src/main/java/org/wikipedia/dataclient/Service.kt
  app/src/main/java/org/wikipedia/dataclient/mwapi/MwQueryPage.kt
  app/src/main/java/org/wikipedia/language/LangLinksActivity.kt
  app/src/main/java/org/wikipedia/language/LangLinksViewModel.kt
Labels: Minor

#4079 Stop using Summary endpoint for Tab thumbnail/description cache.
  app/src/main/java/org/wikipedia/dataclient/Service.kt
  app/src/main/java/org/wikipedia/language/LangLinksViewModel.kt
  app/src/main/java/org/wikipedia/page/PageCacher.kt
  app/src/main/java/org/wikipedia/page/PageFragment.kt
  app/src/main/java/org/wikipedia/readinglist/ReadingListsReceiveHelper.kt
Labels: Minor

#4080 Stop using Summary endpoint for redirected titles for reading list.
  app/src/main/java/org/wikipedia/dataclient/RestService.kt
  app/src/main/java/org/wikipedia/page/PageFragment.kt
  app/src/main/res/layout/fragment_page.xml
Labels: Minor

#4075 Added full screen onboarding to image recs
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/wikipedia/onboarding/OnboardingPageView.kt
  app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsCardsFragment.kt
  app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsImageRecsOnboardingActivity.kt
  app/src/main/res/drawable/illustration_add_images.xml
  app/src/main/res/layout/activity_suggested_edits_image_recs_onboarding.xml
Labels: Design review

#4081 Design tweaks for inserting images, and prepare for Add Image flow.
  app/src/main/java/org/wikipedia/Constants.kt
  app/src/main/java/org/wikipedia/edit/EditSectionActivity.kt
  app/src/main/java/org/wikipedia/edit/insertmedia/InsertMediaActivity.kt
  app/src/main/java/org/wikipedia/edit/insertmedia/InsertMediaViewModel.kt
  app/src/main/java/org/wikipedia/page/PageActivity.kt
  app/src/main/java/org/wikipedia/talk/TalkTopicActivity.kt
  app/src/main/res/layout/fragment_insert_media_advanced_settings.xml
  app/src/main/res/layout/fragment_insert_media_settings.xml
  app/src/main/res/values/strings.xml
Labels: Minor

#4082 Additional API bits for image recommendations.
  app/src/main/java/org/wikipedia/dataclient/Service.kt
  app/src/main/java/org/wikipedia/dataclient/growthtasks/GrowthImageSuggestion.kt
Labels: Minor

#4069 Meditations on algorithms for inserting an image into an article.
  app/src/main/java/org/wikipedia/dataclient/Service.kt
  app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsImageRecsFragment.kt
  app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsImageRecsFragmentViewModel.kt
Labels: WIP, Experimental

#4083 Properly search Commons for image files.
  app/src/main/java/org/wikipedia/dataclient/RestService.kt
  app/src/main/java/org/wikipedia/dataclient/Service.kt
  app/src/main/java/org/wikipedia/edit/insertmedia/InsertMediaActivity.kt
  app/src/main/java/org/wikipedia/edit/insertmedia/InsertMediaSettingsFragment.kt
  app/src/main/java/org/wikipedia/edit/insertmedia/InsertMediaViewModel.kt
  app/src/main/res/layout/fragment_insert_media_settings.xml
Labels: Minor

#4085 Update Rest API paths and error handling.
  app/src/main/java/org/wikipedia/dataclient/CoreRestService.kt
  app/src/main/java/org/wikipedia/dataclient/growthtasks/GrowthImageSuggestion.kt
  app/src/main/java/org/wikipedia/dataclient/restbase/RbServiceError.kt
Labels: Minor

#4086 Design tweaks/fixes in edit preview.
  app/src/main/java/org/wikipedia/bridge/JavaScriptActionHandler.kt
  app/src/main/java/org/wikipedia/edit/preview/EditPreviewFragment.kt
  app/src/main/res/layout/fragment_preview_edit.xml
Labels: Minor

#4097 Migrate from kapt to ksp.
  app/build.gradle
  build.gradle
Labels: Minor

#4101 Update a few dependencies.
  app/build.gradle
  app/src/main/java/org/wikipedia/main/MainFragment.kt
  app/src/main/java/org/wikipedia/page/linkpreview/LinkPreviewDialog.kt
Labels: dependencies

#4102 Fix obscure potential crash when updating network online state.
  app/src/main/java/org/wikipedia/connectivity/ConnectionStateMonitor.kt
Labels: Minor

#4100 Update gradle to 8.1.0.
  app/build.gradle
  build.gradle
Labels: dependencies

#4105 Clean up unused constant values and reduce not-null type in WikitionaryDialog
  app/src/main/java/org/wikipedia/Constants.kt
  app/src/main/java/org/wikipedia/wiktionary/WiktionaryDialog.kt
Labels: Minor
