Repository wikimedia/apps-android-wikipedia, pull requests merged in 2023-01, with the labels that each got.

#3755 Exclude some screens from click events
  app/src/main/java/org/wikipedia/analytics/eventplatform/BreadCrumbViewUtil.kt
Labels: High Priority

#3764 Update gradle plugin to 7.4.0.
  app/build.gradle
  build.gradle
  gradle.properties
  gradle/wrapper/gradle-wrapper.properties
Labels: Minor

#3769 Fix/relax regex for getting different thumbnail widths.
  app/src/main/java/org/wikipedia/util/ImageUrlUtil.kt
  app/src/test/java/org/wikipedia/util/ImageUriUtilTest.kt
Labels: Minor

#3770 Use proper import in the NotificationFilterItemView
  app/src/main/java/org/wikipedia/notifications/NotificationFilterItemView.kt
Labels: Minor

#3771 Follow-up to Watchlist ViewModel.
  app/src/main/java/org/wikipedia/watchlist/WatchlistFragment.kt
  app/src/main/java/org/wikipedia/watchlist/WatchlistViewModel.kt
Labels: Minor

#3772 Correctly expose immutable state flow in NotificationViewModel
  app/src/main/java/org/wikipedia/notifications/NotificationViewModel.kt
Labels: Minor

#3773 Fix/improve tracking of latency on page loads.
  app/src/main/java/org/wikipedia/analytics/SessionData.kt
  app/src/main/java/org/wikipedia/analytics/SessionFunnel.kt
Labels: Minor, High Priority
