Repository wikimedia/apps-android-wikipedia, pull requests merged in 2024-04, with the labels that each got.

#4571 Remove (for real) feature flag for account vanishing.
  app/src/main/java/org/wikipedia/settings/LogoutPreference.kt
Labels: Minor

#4575 Fix potential crash when finding text in editor.
  app/src/main/java/org/wikipedia/edit/FindInEditorActionProvider.kt
Labels: Minor

#4573 Remove redundant attribute from custom CardView.
  app/src/main/java/org/wikipedia/views/WikiCardView.kt
  app/src/main/res/layout/activity_insert_media.xml
  app/src/main/res/layout/dialog_campaign.xml
  app/src/main/res/layout/fragment_places.xml
  app/src/main/res/layout/view_edit_history_search_bar.xml
  app/src/main/res/layout/view_notification_search_bar.xml
  app/src/main/res/layout/view_search_bar.xml
  app/src/main/res/layout/view_suggested_edits_recent_edits_search_bar.xml
  app/src/main/res/layout/view_talk_topics_header.xml
  app/src/main/res/layout/view_watchlist_search_bar.xml
  app/src/main/res/values/attrs.xml
Labels: Minor

#4576 Eliminate unnecessary and redundant SiteInfoClient.
  app/src/main/java/org/wikipedia/WikipediaApp.kt
  app/src/main/java/org/wikipedia/activity/BaseActivity.kt
  app/src/main/java/org/wikipedia/feed/featured/FeaturedArticleCardView.kt
  app/src/main/java/org/wikipedia/feed/mainpage/MainPageCardView.kt
  app/src/main/java/org/wikipedia/language/LangLinksViewModel.kt
  app/src/main/java/org/wikipedia/main/MainFragment.kt
  app/src/main/java/org/wikipedia/page/PageActivity.kt
  app/src/main/java/org/wikipedia/page/PageTitle.kt
  app/src/main/java/org/wikipedia/readinglist/AddToReadingListDialog.kt
  app/src/main/java/org/wikipedia/readinglist/ReadingListFragment.kt
  app/src/main/java/org/wikipedia/settings/SiteInfoClient.kt
Labels: Minor

#4574 Greatly simplify retrieval and usage of UserIDs.
  app/src/main/java/org/wikipedia/WikipediaApp.kt
  app/src/main/java/org/wikipedia/analytics/eventplatform/EditAttemptStepEvent.kt
  app/src/main/java/org/wikipedia/auth/AccountUtil.kt
  app/src/main/java/org/wikipedia/dataclient/SharedPreferenceCookieManager.kt
  app/src/main/res/values/preference_keys.xml
  app/src/main/res/xml/developer_preferences.xml
Labels: Minor

#4577 Improve positioning of Snackbars in Diff screen.
  app/src/main/java/org/wikipedia/diff/ArticleEditDetailsFragment.kt
  app/src/main/java/org/wikipedia/talk/template/TalkTemplatesFragment.kt
  app/src/main/res/layout/fragment_talk_templates.xml
Labels: Minor

#4578 Improve Back navigation when previewing New talk message.
  app/src/main/java/org/wikipedia/talk/TalkReplyActivity.kt
Labels: Minor

#4599 Fix Gallery playback of Ogg and other audio files.
  app/src/main/java/org/wikipedia/gallery/GalleryItemFragment.kt
  app/src/main/java/org/wikipedia/gallery/MediaListItem.kt
Labels: High Priority

#4598 Update gradle and a few libraries.
  app/build.gradle
  build.gradle
Labels: dependencies

#4603 Fix showing Link Preview stub edit pencil only for Main namespace.
  app/src/main/java/org/wikipedia/page/linkpreview/LinkPreviewContents.kt
  app/src/main/java/org/wikipedia/page/linkpreview/LinkPreviewDialog.kt
Labels: High Priority

#4606 Fix: crashes on Explore Feed when airplane mode is activated
  app/src/main/java/org/wikipedia/feed/aggregated/AggregatedFeedContentClient.kt
  app/src/main/java/org/wikipedia/feed/becauseyouread/BecauseYouReadClient.kt
Labels: High Priority

#4610 Fix: use subdomain for available wikis in Patroller Tasks
  app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsTasksFragment.kt
Labels: High Priority

#4612 Fix enabling Next button in TalkReply from saved messages.
  app/src/main/java/org/wikipedia/talk/TalkReplyActivity.kt
Labels: Minor, High Priority

#4613 Don't reset to Your Messages tab unless message was updated.
  app/src/main/java/org/wikipedia/talk/template/TalkTemplatesFragment.kt
Labels: Minor, High Priority

#4615 Update help URL for "minor" edits.
  app/src/main/res/values/strings_no_translate.xml
Labels: Minor

#4611 Update verbiage for image recommendation rejection dialog.
  app/src/main/res/values/strings.xml
Labels: Minor, Ready to merge

#4616 Add strings for Google Pay workflow.
  app/src/main/res/values-qq/strings.xml
  app/src/main/res/values/strings.xml
Labels: Ready to merge

#4623 Update core-ktx dependency.
  app/build.gradle
Labels: dependencies

#4622 Foundations for Google Pay integration.
  app/build.gradle
  app/src/extra/java/org/wikipedia/donate/GooglePayActivity.kt
  app/src/extra/java/org/wikipedia/donate/GooglePayComponent.kt
  app/src/fdroid/AndroidManifest.xml
  app/src/fdroid/java/org/wikipedia/donate/GooglePayComponent.kt
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/wikipedia/dataclient/donate/PaymentResponseContainer.kt
  app/src/main/res/values-qq/strings.xml
  app/src/main/res/values-zh-rTW/strings.xml
Labels: dependencies

#4626 Make Location permissions not required in manifest.
  app/src/main/AndroidManifest.xml
Labels: Minor, High Priority

#4609 Refactoring FilePage related class to use coroutine and ViewModel
  app/src/main/java/org/wikipedia/commons/FilePage.kt
  app/src/main/java/org/wikipedia/commons/FilePageFragment.kt
  app/src/main/java/org/wikipedia/commons/FilePageView.kt
  app/src/main/java/org/wikipedia/commons/FilePageViewModel.kt
  app/src/main/java/org/wikipedia/commons/ImagePreviewDialog.kt
  app/src/main/java/org/wikipedia/commons/ImagePreviewViewModel.kt
  app/src/main/java/org/wikipedia/commons/ImageTagsProvider.kt
  app/src/main/java/org/wikipedia/dataclient/Service.kt
  app/src/main/java/org/wikipedia/descriptions/DescriptionEditActivity.kt
  app/src/main/java/org/wikipedia/descriptions/DescriptionEditBottomBarView.kt
  app/src/main/java/org/wikipedia/edit/insertmedia/InsertMediaSettingsFragment.kt
  app/src/main/java/org/wikipedia/feed/suggestededits/SuggestedEditsCardItemFragment.kt
  app/src/main/java/org/wikipedia/suggestededits/PageSummaryForEdit.kt
  app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsCardsItemFragment.kt
  app/src/main/java/org/wikipedia/views/ImagePreviewDialog.kt
  app/src/main/res/layout/fragment_file_page.xml
Labels: Ready to merge

#4627 Final roll out for Patroller Tasks
  app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsRecentEditsActivity.kt
  app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsTasksFragment.kt
  app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsTasksFragmentViewModel.kt
Labels: Ready to merge

#4628 Refactoring Wiktionary to use Coroutine and ViewModel
  app/src/main/java/org/wikipedia/Constants.kt
  app/src/main/java/org/wikipedia/dataclient/RestService.kt
  app/src/main/java/org/wikipedia/dataclient/restbase/RbDefinition.kt
  app/src/main/java/org/wikipedia/wiktionary/WiktionaryDialog.kt
  app/src/main/java/org/wikipedia/wiktionary/WiktionaryViewModel.kt
  app/src/main/res/layout/dialog_wiktionary.xml
Labels: Ready to merge

#4559 Data wiring for wikitext template
  app/src/main/java/org/wikipedia/edit/SyntaxHighlightViewAdapter.kt
  app/src/main/java/org/wikipedia/edit/templates/InsertTemplateFragment.kt
  app/src/main/java/org/wikipedia/edit/templates/TemplatesSearchActivity.kt
  app/src/main/java/org/wikipedia/edit/templates/TemplatesSearchViewModel.kt
  app/src/main/java/org/wikipedia/talk/TalkReplyActivity.kt
Labels: Ready to merge

#4632 Constrain number of suggested languages on initial install.
  app/src/main/java/org/wikipedia/language/AppLanguageState.kt
  app/src/main/java/org/wikipedia/language/LanguageUtil.kt
  app/src/main/java/org/wikipedia/language/LanguagesListViewModel.kt
Labels: Minor
