Repository wikimedia/apps-android-wikipedia, pull requests merged in 2024-09, with the labels that each got.

#4915 Enforce end-date for Recommended Content experiment.
  app/src/main/java/org/wikipedia/analytics/metricsplatform/RecommendedContentAnalyticsHelper.kt
  app/src/main/java/org/wikipedia/search/RecentSearchesFragment.kt
Labels: Minor

#4916 Use style instead of deprecated method for resizing dialog window.
  app/src/main/java/org/wikipedia/views/SurveyDialog.kt
  app/src/main/res/values/styles.xml
Labels: Minor

#4920 Fix scroll area of edit window when obscured by wikitext buttons.
  app/src/main/res/layout/activity_edit_section.xml
Labels: Minor

#4919 Remove deprecated check from breadcrumbs handler.
  app/src/main/java/org/wikipedia/analytics/eventplatform/BreadCrumbViewUtil.kt
Labels: Minor

#4923 Optimizing the NewsItem and OnThisDay variables
  app/src/main/java/org/wikipedia/feed/news/NewsItem.kt
  app/src/main/java/org/wikipedia/feed/news/NewsLinkCard.kt
  app/src/main/java/org/wikipedia/feed/onthisday/OnThisDay.kt
  app/src/main/java/org/wikipedia/feed/onthisday/OnThisDayCard.kt
  app/src/main/java/org/wikipedia/feed/onthisday/OnThisDayCardView.kt
  app/src/main/java/org/wikipedia/feed/onthisday/OnThisDayFragment.kt
Labels: Minor

#4922 Preparations for removing recommendation-api service.
  app/src/main/java/org/wikipedia/commons/FilePageViewModel.kt
  app/src/main/java/org/wikipedia/dataclient/Service.kt
  app/src/main/java/org/wikipedia/dataclient/wikidata/Entities.kt
  app/src/main/java/org/wikipedia/feed/suggestededits/SuggestedEditsCardItemViewModel.kt
  app/src/main/java/org/wikipedia/gallery/GalleryViewModel.kt
  app/src/main/java/org/wikipedia/page/leadimages/LeadImagesHandler.kt
  app/src/main/java/org/wikipedia/settings/DeveloperSettingsPreferenceLoader.kt
  app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsCardsItemViewModel.kt
  app/src/main/java/org/wikipedia/suggestededits/provider/EditingSuggestionsProvider.kt
  app/src/main/java/org/wikipedia/usercontrib/UserContribStats.kt
  app/src/main/java/org/wikipedia/util/L10nUtil.kt
Labels: Minor

#4859 Feature branch: Recommended Content
  app/src/main/java/org/wikipedia/Constants.kt
  app/src/main/java/org/wikipedia/analytics/ABTest.kt
  app/src/main/java/org/wikipedia/analytics/metricsplatform/ArticleEvent.kt
  app/src/main/java/org/wikipedia/analytics/metricsplatform/RecommendedContentABCTest.kt
  app/src/main/java/org/wikipedia/analytics/metricsplatform/RecommendedContentAnalyticsHelper.kt
  app/src/main/java/org/wikipedia/diff/ArticleEditDetailsFragment.kt
  app/src/main/java/org/wikipedia/history/HistoryEntry.kt
  app/src/main/java/org/wikipedia/history/db/HistoryEntryWithImageDao.kt
  app/src/main/java/org/wikipedia/page/PageFragment.kt
  app/src/main/java/org/wikipedia/recommendedcontent/RecommendedContentFragment.kt
  app/src/main/java/org/wikipedia/recommendedcontent/RecommendedContentSectionView.kt
  app/src/main/java/org/wikipedia/recommendedcontent/RecommendedContentViewModel.kt
  app/src/main/java/org/wikipedia/search/RecentSearchesFragment.kt
  app/src/main/java/org/wikipedia/search/SearchFragment.kt
  app/src/main/java/org/wikipedia/settings/Prefs.kt
  app/src/main/java/org/wikipedia/views/SurveyDialog.kt
  app/src/main/res/layout/dialog_feedback_input.xml
  app/src/main/res/layout/dialog_feedback_options.xml
  app/src/main/res/layout/dialog_patrol_edit_feedback_options.xml
  app/src/main/res/layout/fragment_history.xml
  app/src/main/res/layout/fragment_recommended_content.xml
  app/src/main/res/layout/fragment_search_recent.xml
  app/src/main/res/layout/item_recommended_content_search_history.xml
  app/src/main/res/layout/item_recommended_content_section_text.xml
  app/src/main/res/layout/view_recommended_content_section.xml
  app/src/main/res/values-qq/strings.xml
  app/src/main/res/values/preference_keys.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
  app/src/main/res/xml/developer_preferences.xml
Labels: Ready to merge

#4925 Tiny follow-up to recommended content.
  app/src/main/java/org/wikipedia/recommendedcontent/RecommendedContentViewModel.kt
Labels: Minor

#4928 Fix potential crash in recommended content.
  app/src/main/java/org/wikipedia/recommendedcontent/RecommendedContentFragment.kt
  app/src/main/java/org/wikipedia/views/LanguageScrollView.kt
Labels: Minor, High Priority

#4929 Fix: apply start and end padding to the OverFlowMenuItem style
  app/src/main/res/values/styles.xml
Labels: Minor, High Priority

#4932 Use async to improve the loading time for the random article card
  app/src/main/java/org/wikipedia/feed/random/RandomClient.kt
Labels: Minor

#4933 Fix: show the correct article extracts for the featured article in zhwiki
  app/src/main/java/org/wikipedia/dataclient/page/PageSummary.kt
  app/src/main/java/org/wikipedia/feed/aggregated/AggregatedFeedContentClient.kt
  app/src/main/java/org/wikipedia/util/L10nUtil.kt
Labels: Minor

#4935 Tiny follow-up to async improvements.
  app/src/main/java/org/wikipedia/feed/random/RandomClient.kt
  app/src/main/java/org/wikipedia/util/L10nUtil.kt
Labels: Minor

#4939 Correctly strip html styling from Talk activity titles.
  app/src/main/java/org/wikipedia/talk/TalkThreadHeaderView.kt
  app/src/main/java/org/wikipedia/talk/TalkTopicsActivity.kt
Labels: Minor

#4937 Fix possible duplicate action in notifications.
  app/src/main/java/org/wikipedia/notifications/NotificationPresenter.kt
Labels: Minor

#4940 Fix: typo in ViewModel class
  app/src/main/java/org/wikipedia/page/linkpreview/LinkPreviewViewModel.kt
  app/src/main/java/org/wikipedia/watchlist/WatchlistExpiryDialogViewModel.kt
Labels: Minor

#4942 Minor: update the order of enabled countries list for Recommended Content
  app/src/main/java/org/wikipedia/analytics/metricsplatform/RecommendedContentAnalyticsHelper.kt
Labels: Minor

#4945 Simplify the logic of getting captchaId and captchaWord from the handler
  app/src/main/java/org/wikipedia/captcha/CaptchaHandler.kt
  app/src/main/java/org/wikipedia/createaccount/CreateAccountActivity.kt
  app/src/main/java/org/wikipedia/descriptions/DescriptionEditFragment.kt
  app/src/main/java/org/wikipedia/edit/EditSectionActivity.kt
Labels: Minor

#4938 Simplify the logic of picking up a random event from On This Day
  app/src/main/java/org/wikipedia/feed/aggregated/AggregatedFeedContent.kt
  app/src/main/java/org/wikipedia/feed/aggregated/AggregatedFeedContentClient.kt
  app/src/main/java/org/wikipedia/feed/onthisday/OnThisDayCard.kt
Labels: Minor

#4948 (Truly) fix possible crash in recommended content.
  app/src/main/java/org/wikipedia/search/RecentSearchesFragment.kt
Labels: Minor, High Priority

#4949 Fix: don't send empty string for morelike API in Recommended content
  app/src/main/java/org/wikipedia/recommendedcontent/RecommendedContentFragment.kt
  app/src/main/java/org/wikipedia/recommendedcontent/RecommendedContentViewModel.kt
Labels: High Priority

#4950 Fix: do not make an API call for an empty list in getPagesForLanguageVariant()
  app/src/main/java/org/wikipedia/util/L10nUtil.kt
Labels: Minor, High Priority

#4946 Update campaign ID format sent with GPay transaction.
  app/src/extra/java/org/wikipedia/donate/GooglePayViewModel.kt
Labels: Minor

#4905 Remove dependency on recommendation-api service.
  app/src/main/java/org/wikipedia/dataclient/RestService.kt
  app/src/main/java/org/wikipedia/dataclient/Service.kt
  app/src/main/java/org/wikipedia/feed/suggestededits/SuggestedEditsCardItemViewModel.kt
  app/src/main/java/org/wikipedia/settings/DeveloperSettingsPreferenceLoader.kt
  app/src/main/java/org/wikipedia/suggestededits/provider/EditingSuggestionsProvider.kt
  app/src/main/java/org/wikipedia/suggestededits/provider/SuggestedEditItem.kt
Labels: Ready to merge

#4955 A bit more ground work for temp accounts.
  app/src/main/java/org/wikipedia/auth/AccountUtil.kt
Labels: Minor

#4967 Update gitignore to ignore *.salive files
  .gitignore
Labels: Minor

#4974 Hygiene: update test cases to use suspend API functions and remove unused test class
  app/src/main/java/org/wikipedia/commons/FilePageViewModel.kt
  app/src/main/java/org/wikipedia/commons/ImagePreviewViewModel.kt
  app/src/main/java/org/wikipedia/dataclient/RestService.kt
  app/src/main/java/org/wikipedia/dataclient/Service.kt
  app/src/main/java/org/wikipedia/feed/suggestededits/SuggestedEditsCardItemViewModel.kt
  app/src/main/java/org/wikipedia/gallery/GalleryItemViewModel.kt
  app/src/main/java/org/wikipedia/gallery/GalleryViewModel.kt
  app/src/main/java/org/wikipedia/page/leadimages/LeadImagesHandler.kt
  app/src/main/java/org/wikipedia/page/linkpreview/LinkPreviewViewModel.kt
  app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsCardsItemViewModel.kt
  app/src/test/java/org/wikipedia/gallery/GalleryClientTest.kt
  app/src/test/java/org/wikipedia/gallery/ImageLicenseFetchClientTest.kt
  app/src/test/java/org/wikipedia/pageimages/PageImagesClientTest.kt
Labels: Minor

#4975 Hygiene: update function type in fdroid package and update pollNotificationWorker
  app/src/fdroid/java/org/wikipedia/push/WikipediaFirebaseMessagingService.kt
  app/src/main/java/org/wikipedia/notifications/PollNotificationWorker.kt
Labels: Minor

#4969 Fix: the text elements are cutoff in the On This Day screen
  app/src/main/java/org/wikipedia/feed/onthisday/OnThisDayFragment.kt
  app/src/main/res/layout/date_picker_dialog.xml
  app/src/main/res/layout/fragment_on_this_day.xml
Labels: Ready to merge

#4988 Hygiene: remove unused API calls and rename the getClaims() function
  app/src/main/java/org/wikipedia/commons/ImageTagsProvider.kt
  app/src/main/java/org/wikipedia/dataclient/Service.kt
Labels: Minor

#4986 Fix: example messages disappear after re-entering the screen
  app/src/main/java/org/wikipedia/talk/template/TalkTemplatesFragment.kt
Labels: Minor

#4983 Convert PrefsIoUtil to Kotlin
  app/src/main/java/org/wikipedia/settings/PrefsIoUtil.java
  app/src/main/java/org/wikipedia/settings/PrefsIoUtil.kt
Labels: Minor

#4953 Refresh the feed content after changing the app languages while onboarding
  app/src/main/java/org/wikipedia/main/MainActivity.kt
  app/src/main/java/org/wikipedia/onboarding/InitialOnboardingActivity.kt
  app/src/main/java/org/wikipedia/onboarding/InitialOnboardingFragment.kt
Labels: Minor

#4927 Optimizing the language variant logic for the feed and apply it for On This Day
  app/src/main/java/org/wikipedia/feed/aggregated/AggregatedFeedContentClient.kt
  app/src/main/java/org/wikipedia/feed/onthisday/OnThisDay.kt
  app/src/main/java/org/wikipedia/feed/onthisday/OnThisDayViewModel.kt
Labels: Ready to merge

#4941 Refactoring DescriptionEditFragment to use ViewModel and Coroutine
  app/src/main/java/org/wikipedia/dataclient/RestService.kt
  app/src/main/java/org/wikipedia/dataclient/Service.kt
  app/src/main/java/org/wikipedia/descriptions/DescriptionEditFragment.kt
  app/src/main/java/org/wikipedia/descriptions/DescriptionEditViewModel.kt
  app/src/main/java/org/wikipedia/page/linkpreview/LinkPreviewViewModel.kt
  app/src/test/java/org/wikipedia/descriptions/DescriptionEditClientTest.kt
  app/src/test/res/raw/label_edit.json
Labels: Ready to merge

#4733 Refactoring CsrfTokenClient to use coroutine
  app/src/extra/java/org/wikipedia/push/WikipediaFirebaseMessagingService.kt
  app/src/main/java/org/wikipedia/csrf/CsrfTokenClient.kt
  app/src/main/java/org/wikipedia/notifications/NotificationPollBroadcastReceiver.kt
  app/src/main/java/org/wikipedia/notifications/PollNotificationWorker.kt
  app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsImageRecsFragmentViewModel.kt
  app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsImageTagsViewModel.kt
  app/src/main/java/org/wikipedia/talk/NotificationDirectReplyHelper.kt
  app/src/main/java/org/wikipedia/talk/TalkTopicsViewModel.kt
  app/src/test/java/org/wikipedia/csrf/CsrfTokenClientTest.java
  app/src/test/java/org/wikipedia/csrf/CsrfTokenClientTest.kt
Labels: Ready to merge

#4991 Follow-up to Csrf coroutine refactor.
  app/src/main/java/org/wikipedia/csrf/CsrfTokenClient.kt
  app/src/main/java/org/wikipedia/descriptions/DescriptionEditViewModel.kt
Labels: Minor

#4990 Follow-up to DescriptionEditFragment viewModel.
  app/src/main/java/org/wikipedia/descriptions/DescriptionEditFragment.kt
  app/src/main/java/org/wikipedia/descriptions/DescriptionEditViewModel.kt
  app/src/test/java/org/wikipedia/descriptions/DescriptionEditClientTest.kt
Labels: Minor

#4992 Remove hashtag comment when submitting Image Recommendations.
  app/src/main/java/org/wikipedia/edit/EditSectionActivity.kt
  app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsImageRecsFragment.kt
Labels: Minor

#4973 Refactoring EditSectionActivity to use Coroutine and ViewModel
  app/src/main/java/org/wikipedia/dataclient/Service.kt
  app/src/main/java/org/wikipedia/descriptions/DescriptionEditViewModel.kt
  app/src/main/java/org/wikipedia/edit/EditSectionActivity.kt
  app/src/main/java/org/wikipedia/edit/EditSectionViewModel.kt
  app/src/main/java/org/wikipedia/edit/summaries/EditSummaryFragment.kt
  app/src/main/java/org/wikipedia/talk/NotificationDirectReplyHelper.kt
  app/src/main/res/layout/activity_edit_section.xml
  app/src/test/java/org/wikipedia/descriptions/DescriptionEditClientTest.kt
  app/src/test/java/org/wikipedia/edit/wikitext/WikitextClientTest.kt
Labels: Ready to merge

#4976 Move readingListPage handling behavior to the utility class and use coroutine
  app/src/main/java/org/wikipedia/readinglist/ReadingListBehaviorsUtil.kt
  app/src/main/java/org/wikipedia/readinglist/ReadingListFragment.kt
  app/src/main/java/org/wikipedia/readinglist/ReadingListsFragment.kt
Labels: Minor

#4954 Redesign Tabs screen.
  app/build.gradle
  app/src/main/java/org/wikipedia/feed/view/FeedView.kt
  app/src/main/java/org/wikipedia/page/PageActivity.kt
  app/src/main/java/org/wikipedia/page/tabs/SwipeableTabTouchHelperCallback.kt
  app/src/main/java/org/wikipedia/page/tabs/TabActivity.kt
  app/src/main/java/org/wikipedia/views/AutoFitRecyclerView.kt
  app/src/main/res/layout/activity_tabs.xml
  app/src/main/res/layout/fragment_feed.xml
  app/src/main/res/layout/item_tab_contents.xml
  app/src/main/res/values/attrs.xml
  gradle/libs.versions.toml
Labels: Ready to merge

#4993 Facepalm: correctly get campaign id from Activity's intent.
  app/src/extra/java/org/wikipedia/donate/GooglePayActivity.kt
Labels: Minor, High Priority

#4984 Fix: a possible crash about lateinit WikipediaApp instance has not en initialized
  app/src/main/java/org/wikipedia/WikipediaApp.kt
Labels: Ready to merge

#4994 Fix FromHtml rendering of ordered lists with Paragraph spans.
  app/src/main/java/org/wikipedia/richtext/CustomHtmlParser.kt
Labels: Minor

#4998 Correctly format Campaign ID for native payments and analytics.
  app/src/extra/java/org/wikipedia/donate/GooglePayViewModel.kt
  app/src/main/java/org/wikipedia/analytics/eventplatform/DonorExperienceEvent.kt
  app/src/main/java/org/wikipedia/dataclient/donate/CampaignCollection.kt
Labels: Minor, High Priority
