Repository wikimedia/apps-android-wikipedia, pull requests merged in 2024-07, with the labels that each got.

#4765 Use selectableItemBackground in SearchBarView in Places
  app/src/main/res/layout/fragment_places.xml
Labels: Minor

#4763 Refactoring UserMentionInputView to use coroutine
  app/src/main/java/org/wikipedia/dataclient/Service.kt
  app/src/main/java/org/wikipedia/feed/view/ListCardItemView.kt
  app/src/main/java/org/wikipedia/views/UserMentionInputView.kt
Labels: Ready to merge

#4759 Update Revision Tags and stop using edit summaries batch 1
  app/src/main/java/org/wikipedia/dataclient/Service.kt
  app/src/main/java/org/wikipedia/descriptions/DescriptionEditFragment.kt
  app/src/main/java/org/wikipedia/diff/ArticleEditDetailsViewModel.kt
  app/src/main/java/org/wikipedia/edit/EditTags.kt
Labels: Ready to merge

#4771 Fix: add Commons to dbName() logic for Constributions list
  app/src/main/java/org/wikipedia/dataclient/WikiSite.kt
Labels: Minor

#4772 Fix: open wikidata history page in a customTab in the Diff screen
  app/src/main/java/org/wikipedia/diff/ArticleEditDetailsFragment.kt
Labels: Minor

#4775 Properly ask for permission to show notifications on API 33+.
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/wikipedia/activity/BaseActivity.kt
  app/src/main/java/org/wikipedia/alphaupdater/AlphaUpdateChecker.kt
  app/src/main/java/org/wikipedia/notifications/NotificationPresenter.kt
Labels: Minor, High Priority

#4774 Fix potential crash in Search paging, and simplify.
  app/src/main/java/org/wikipedia/search/SearchResultsFragment.kt
  app/src/main/java/org/wikipedia/search/SearchResultsViewModel.kt
Labels: Minor

#4773 Fix possible crash when searching for text in Syntax Highlighter.
  app/src/main/java/org/wikipedia/edit/richtext/SyntaxHighlighter.kt
Labels: Minor

#4780 Use coroutine in EventPlatformClient
  app/src/main/java/org/wikipedia/analytics/eventplatform/EventPlatformClient.kt
  app/src/main/java/org/wikipedia/dataclient/Service.kt
Labels: Minor

#4778 Use coroutine in SuggestedEditsImageTagDialog
  app/src/main/java/org/wikipedia/dataclient/Service.kt
  app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsImageTagDialog.kt
Labels: Minor

#4782 Follow-up: improve/simplify debouncing in ImageTagDialog.
  app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsImageTagDialog.kt
Labels: Minor

#4781 Fix certain markers in Places missing a thumbnail image.
  app/src/main/java/org/wikipedia/dataclient/Service.kt
Labels: Minor

#4783 Fix: possible NullPointerException in SuggestedEditsCardsFragment
  app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsCardsFragment.kt
Labels: Minor

#4779 Use coroutine in RecurringTask
  app/src/main/java/org/wikipedia/activity/BaseActivity.kt
  app/src/main/java/org/wikipedia/alphaupdater/AlphaUpdateChecker.kt
  app/src/main/java/org/wikipedia/recurring/DailyEventTask.kt
  app/src/main/java/org/wikipedia/recurring/RecurringTask.kt
  app/src/main/java/org/wikipedia/recurring/RecurringTasksExecutor.kt
  app/src/main/java/org/wikipedia/recurring/TalkOfflineCleanupTask.kt
  app/src/main/java/org/wikipedia/settings/RemoteConfigRefreshTask.kt
Labels: Minor

#4785 Follow-up to recurring tasks.
  app/src/main/java/org/wikipedia/alphaupdater/AlphaUpdateChecker.kt
  app/src/main/java/org/wikipedia/analytics/eventplatform/EventPlatformClient.kt
  app/src/main/java/org/wikipedia/recurring/RecurringTasksExecutor.kt
  app/src/main/java/org/wikipedia/recurring/TalkOfflineCleanupTask.kt
  app/src/main/java/org/wikipedia/settings/RemoteConfigRefreshTask.kt
Labels: Minor

#4764 Open Special:ChangePassword in an external browser in Notifications
  app/src/main/java/org/wikipedia/notifications/NotificationActivity.kt
  app/src/main/java/org/wikipedia/notifications/NotificationCategory.kt
  app/src/main/java/org/wikipedia/notifications/NotificationLinkHandler.kt
  app/src/main/java/org/wikipedia/views/NotificationActionsOverflowView.kt
Labels: Ready to merge

#4760 Fix: Provide a login option in WikiErrorView
  app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsTasksFragment.kt
  app/src/main/java/org/wikipedia/util/ThrowableUtil.kt
  app/src/main/java/org/wikipedia/views/WikiErrorView.kt
Labels: Ready to merge

#4795 Remove unused editing text size preference
  app/src/main/java/org/wikipedia/settings/Prefs.kt
  app/src/main/res/values/preference_keys.xml
Labels: Minor

#4799 Fix display of non-edit log events in Watchlist items.
  app/src/main/java/org/wikipedia/watchlist/WatchlistItemView.kt
Labels: Minor

#4793 Apply the correct language code from Places in the Search screen
  app/src/main/java/org/wikipedia/search/SearchFragment.kt
Labels: Ready to merge

#4802 Convert top-level gradle file to use version catalog.
  build.gradle
  gradle/libs.versions.toml
Labels: dependencies

#4801 Introduce dependabot for dependency updates.
  .github/dependabot.yml
Labels: dependencies

#4819 No longer ignore maplibre for dependabot.
  .github/dependabot.yml
Labels: dependencies

#4791 Integrate with new account vanishing form.
  app/src/main/java/org/wikipedia/activity/SingleWebViewActivity.kt
  app/src/main/java/org/wikipedia/bridge/JavaScriptActionHandler.kt
  app/src/main/res/values/strings_no_translate.xml
Labels: High Priority, Ready to merge

#4822 Fix auto-logout from CsrfTokenClient.
  app/src/main/java/org/wikipedia/csrf/CsrfTokenClient.kt
Labels: High Priority

#4826 Remove installreferrer from refactored dependencies.
  app/build.gradle
Labels: High Priority, dependencies

#4828 Move NearbyPage to dataclient package
  app/src/main/java/org/wikipedia/dataclient/page/NearbyPage.kt
  app/src/main/java/org/wikipedia/places/PlacesFragment.kt
  app/src/main/java/org/wikipedia/places/PlacesFragmentViewModel.kt
Labels: Minor

#4829 Tiny follow-up: remove unnecessary fields.
  app/src/main/java/org/wikipedia/dataclient/page/NearbyPage.kt
Labels: Minor

#4820 Relocate 'Send Feedback' Button to Settings
  app/src/main/java/org/wikipedia/settings/AboutActivity.kt
  app/src/main/java/org/wikipedia/settings/SettingsPreferenceLoader.kt
  app/src/main/res/layout/activity_about.xml
  app/src/main/res/values/preference_keys.xml
  app/src/main/res/xml/preferences_about.xml
Labels: Design review

#4695 Build dialogs for removing generic Chinese language variant codes
  app/src/main/java/org/wikipedia/feed/FeedFragment.kt
  app/src/main/java/org/wikipedia/feed/view/RegionalLanguageVariantSelectionDialog.kt
  app/src/main/java/org/wikipedia/language/AppLanguageState.kt
  app/src/main/java/org/wikipedia/language/LangLinksViewModel.kt
  app/src/main/res/layout/dialog_regional_language_variant_selection.xml
  app/src/main/res/layout/item_language_variant_selection.xml
  app/src/test/java/org/wikipedia/language/LangLinksActivityTest.kt
Labels: Ready to merge

#4833 Revert "Remove feature flag for machine-suggested descriptions."
  app/src/main/java/org/wikipedia/descriptions/DescriptionEditActivity.kt
  app/src/main/java/org/wikipedia/descriptions/DescriptionEditFragment.kt
Labels: High Priority

#4839 Add license parameter when querying pageimages with recommendations.
  app/src/main/java/org/wikipedia/dataclient/Service.kt
Labels: Minor

#4823 Use W logo for the image placeholder and update cluster marker in Places
  app/src/main/java/org/wikipedia/places/PlacesFragment.kt
  app/src/main/java/org/wikipedia/util/ResourceUtil.kt
  app/src/main/res/drawable/ic_w_logo_circle.xml
  app/src/main/res/layout/item_places_list.xml
Labels: Ready to merge

#4843 Follow-up to map markers.
  app/src/main/java/org/wikipedia/gallery/ImagePipelineBitmapGetter.kt
  app/src/main/java/org/wikipedia/places/PlacesFragment.kt
Labels: Minor

#4831 Edit tags, final batch.
  app/src/main/java/org/wikipedia/dataclient/Service.kt
  app/src/main/java/org/wikipedia/descriptions/DescriptionEditFragment.kt
  app/src/main/java/org/wikipedia/edit/EditSectionActivity.kt
  app/src/main/java/org/wikipedia/edit/EditTags.kt
  app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsImageTagsViewModel.kt
Labels: Ready to merge
