Repository wikimedia/apps-android-wikipedia, pull requests merged in 2024-01, with the labels that each got.

#4349 Correctly optimize display of Diff lines in RecyclerView.
  app/src/main/java/org/wikipedia/diff/ArticleEditDetailsFragment.kt
  app/src/main/res/layout/fragment_article_edit_details.xml
Labels: Minor, High Priority

#4350 Optimize date format cache.
  app/src/main/java/org/wikipedia/util/DateUtil.kt
Labels: Minor

#4355 Revert "Update material-components-android library version to 1.11.0"
  app/build.gradle
Labels: High Priority

#4361 Correctly set `schemaLocation` for the Room annotation processor.
  app/build.gradle
  app/schemas/org.wikipedia.database.AppDatabase/25.json
Labels: Minor

#4360 Launch donation flow from Donate button in Chrome Custom Tab.
  app/src/main/java/org/wikipedia/navtab/MenuNavTabDialog.kt
Labels: Minor

#4359 Update Gradle and ksp to latest versions.
  build.gradle
Labels: dependencies

#4364 Follow-up to HistoryEntry database update (descriptions).
  app/schemas/org.wikipedia.database.AppDatabase/26.json
  app/src/main/java/org/wikipedia/history/HistoryEntry.kt
  app/src/main/java/org/wikipedia/history/db/HistoryEntryDao.kt
Labels: Minor

#4368 Follow-up to watchlist expiry logic.
  app/src/main/java/org/wikipedia/watchlist/WatchlistExpiryDialog.kt
  app/src/main/java/org/wikipedia/watchlist/WatchlistExpiryDialogViewModel.kt
Labels: Minor

#4367 Don't allow thanking when logged out.
  app/src/main/java/org/wikipedia/talk/UserTalkPopupHelper.kt
Labels: Minor

#4372 Fix behavior of Diff bottom bar when logged out.
  app/src/main/java/org/wikipedia/diff/ArticleEditDetailsFragment.kt
  app/src/main/res/layout/fragment_article_edit_details.xml
Labels: Minor

#4373 Fix full-text search.
  app/src/main/java/org/wikipedia/search/SearchResultsViewModel.kt
Labels: High Priority

#4374 Correctly handle nested list tags in Html.
  app/src/main/java/org/wikipedia/richtext/CustomHtmlParser.kt
  app/src/main/java/org/wikipedia/talk/TalkTopicsActivity.kt
Labels: High Priority

#4370 Simplify the logic of adding/moving article to reading list
  app/src/main/java/org/wikipedia/feed/news/NewsFragment.kt
  app/src/main/java/org/wikipedia/feed/onthisday/OnThisDayCardView.kt
  app/src/main/java/org/wikipedia/feed/onthisday/OnThisDayPagesViewHolder.kt
  app/src/main/java/org/wikipedia/feed/topread/TopReadFragment.kt
  app/src/main/java/org/wikipedia/main/MainFragment.kt
  app/src/main/java/org/wikipedia/page/ExclusiveBottomSheetPresenter.kt
  app/src/main/java/org/wikipedia/page/PageActivity.kt
  app/src/main/java/org/wikipedia/page/PageContainerLongPressHandler.kt
  app/src/main/java/org/wikipedia/page/PageFragment.kt
  app/src/main/java/org/wikipedia/page/linkpreview/LinkPreviewDialog.kt
  app/src/main/java/org/wikipedia/random/RandomFragment.kt
  app/src/main/java/org/wikipedia/readinglist/MoveToReadingListDialog.kt
  app/src/main/java/org/wikipedia/readinglist/ReadingListBehaviorsUtil.kt
  app/src/main/java/org/wikipedia/search/SearchFragment.kt
Labels: High Priority

#4377 Use the newer version of build tools for the Github sign-android-release action
  .github/workflows/android.yml
  .github/workflows/android_branch.yml
Labels: High Priority

#4379 Don't create unnecessary bitmaps.
  app/src/main/java/org/wikipedia/places/PlacesFragment.kt
Labels: Minor

#4343 Places: update UI elements on map
  app/src/main/java/org/wikipedia/places/PlacesFragment.kt
  app/src/main/res/drawable/ic_compass_with_bg.xml
  app/src/main/res/layout/fragment_places.xml
Labels: Design review

#4319 Places: Search
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/wikipedia/places/PlacesFilterActivity.kt
  app/src/main/java/org/wikipedia/places/PlacesFragment.kt
  app/src/main/java/org/wikipedia/search/SearchFragment.kt
  app/src/main/java/org/wikipedia/search/SearchResult.kt
  app/src/main/java/org/wikipedia/search/SearchResults.kt
  app/src/main/java/org/wikipedia/search/SearchResultsFragment.kt
  app/src/main/java/org/wikipedia/search/SearchResultsViewModel.kt
  app/src/main/res/layout/activity_places_filters.xml
  app/src/main/res/layout/view_places_filter_item.xml
  app/src/main/res/layout/view_places_filters_footer.xml
  app/src/main/res/values-qq/strings.xml
  app/src/main/res/values/strings.xml
Labels: Design review

#4389 Follow-up (Places): run animation when opening in new tab.
  app/src/main/java/org/wikipedia/places/PlacesFragment.kt
Labels: Minor

#4390 Fix Commons search when inserting images.
  app/src/main/java/org/wikipedia/dataclient/Service.kt
  app/src/main/java/org/wikipedia/dataclient/mwapi/MwQueryResponse.kt
  app/src/main/java/org/wikipedia/edit/insertmedia/InsertMediaViewModel.kt
  app/src/main/java/org/wikipedia/search/SearchResultsViewModel.kt
  app/src/test/java/org/wikipedia/search/FullTextSearchClientTest.kt
Labels: High Priority

#4391 Further improve/fix Search interface.
  app/src/main/java/org/wikipedia/search/SearchResultsFragment.kt
  app/src/main/java/org/wikipedia/search/SearchResultsViewModel.kt
Labels: Minor

#4392 Design tweak: Places search
  app/src/main/java/org/wikipedia/places/PlacesFragment.kt
Labels: Design review

#4383 Places Filter screen: Design tweaks
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/wikipedia/places/PlacesFilterActivity.kt
  app/src/main/res/layout/activity_places_filters.xml
  app/src/main/res/layout/fragment_places.xml
  app/src/main/res/layout/view_places_filter_item.xml
  app/src/main/res/layout/view_places_filters_footer.xml
  app/src/main/res/layout/view_watchlist_filter_header.xml
Labels: Design review

#4396 Re-introduce minimum movement constraint for querying map updates.
  app/src/main/java/org/wikipedia/places/PlacesFragment.kt
Labels: Minor

#4397 (Places) Correctly handle insets.
  app/src/main/java/org/wikipedia/places/PlacesFragment.kt
Labels: Minor

#4402 (Places) remove postDelayed calls.
  app/src/main/java/org/wikipedia/places/PlacesFragment.kt
Labels: Minor

#4403 (Places) Clean up searching, and correctly remember last search term.
  app/src/main/java/org/wikipedia/places/PlacesFragment.kt
  app/src/main/java/org/wikipedia/search/SearchFragment.kt
  app/src/main/java/org/wikipedia/search/SearchResult.kt
  app/src/main/java/org/wikipedia/search/SearchResultsFragment.kt
Labels: Minor

#4413 Add prop=extracts for list view items in Places
  app/src/main/java/org/wikipedia/dataclient/Service.kt
  app/src/main/java/org/wikipedia/places/PlacesFragmentViewModel.kt
Labels: High Priority

#4411 Survey text strings for translation
  app/src/main/res/values-qq/strings.xml
  app/src/main/res/values/strings.xml
Labels: High Priority

#4418 Update gradle and dependencies.
  app/build.gradle
  app/src/main/java/org/wikipedia/gallery/GalleryItemFragment.kt
  app/src/main/java/org/wikipedia/views/FaceAndColorDetectImageView.kt
  build.gradle
Labels: dependencies

#4416 (Places) Don't use extra list along with LiveData.
  app/src/main/java/org/wikipedia/places/PlacesFragment.kt
  app/src/main/java/org/wikipedia/places/PlacesFragmentViewModel.kt
Labels: Minor

#4419 Log invokeSource in breadcrumbs "show" events.
  app/src/main/java/org/wikipedia/analytics/eventplatform/BreadCrumbLogEvent.kt
Labels: Minor

#4421 Places: New string
  app/src/main/res/values-qq/strings.xml
  app/src/main/res/values/strings.xml
Labels: High Priority

#4357 Places: Build a "list" view of places, alongside the "map" view
  app/src/main/java/org/wikipedia/dataclient/Service.kt
  app/src/main/java/org/wikipedia/page/PageFragment.kt
  app/src/main/java/org/wikipedia/page/linkpreview/LinkPreviewDialog.kt
  app/src/main/java/org/wikipedia/places/PlacesFragment.kt
  app/src/main/java/org/wikipedia/places/PlacesFragmentViewModel.kt
  app/src/main/java/org/wikipedia/random/RandomFragment.kt
  app/src/main/java/org/wikipedia/readinglist/LongPressMenu.kt
  app/src/main/java/org/wikipedia/readinglist/ReadingListPreviewSaveDialogView.kt
  app/src/main/java/org/wikipedia/views/ViewUtil.kt
  app/src/main/res/drawable/ic_places_empty_state_illustration.xml
  app/src/main/res/layout/dialog_link_preview.xml
  app/src/main/res/layout/fragment_places.xml
  app/src/main/res/layout/item_places_list.xml
  app/src/main/res/menu/menu_places_long_press.xml
  app/src/main/res/values/styles.xml
Labels: Design review

#4427 Fix width calculation of tooltop "Got it" button.
  app/src/main/java/org/wikipedia/util/FeedbackUtil.kt
  app/src/main/res/layout/view_plain_text_tooltip.xml
Labels: Minor
