Repository wikimedia/apps-android-wikipedia, pull requests merged in 2024-12, with the labels that each got.

#5155 Tiny tweak to Rabbit Holes analytics event.
  app/src/main/java/org/wikipedia/search/RecentSearchesFragment.kt
Labels: Minor, High Priority

#5148 Espresso Suggested Edit Test
  app/src/androidTest/java/org/wikipedia/TestSuite.kt
  app/src/androidTest/java/org/wikipedia/base/BaseRobot.kt
  app/src/androidTest/java/org/wikipedia/base/BaseTest.kt
  app/src/androidTest/java/org/wikipedia/robots/navigation/BottomNavRobot.kt
  app/src/androidTest/java/org/wikipedia/robots/screen/ContributionScreenScreenRobot.kt
  app/src/androidTest/java/org/wikipedia/robots/screen/SuggestedEditsScreenRobot.kt
  app/src/androidTest/java/org/wikipedia/tests/SuggestedEditScreenTest.kt
  app/src/main/java/org/wikipedia/settings/Prefs.kt
  app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsTasksFragmentViewModel.kt
  app/src/main/res/values/preference_keys.xml
  app/src/main/res/xml/developer_preferences.xml
Labels: Ready to merge

#5162 Hygiene: code clean up for the diff package
  app/src/main/java/org/wikipedia/diff/ArticleEditDetailsViewModel.kt
  app/src/main/java/org/wikipedia/diff/DiffLineView.kt
  app/src/main/java/org/wikipedia/diff/DiffUtil.kt
  app/src/main/java/org/wikipedia/diff/UndoEditDialog.kt
Labels: Minor

#5163 Use slightly different verbiage for Reading List survey dialog.
  app/src/main/java/org/wikipedia/readinglist/ReadingListsFragment.kt
  app/src/main/res/values-qq/strings.xml
  app/src/main/res/values/strings.xml
Labels: Minor, High Priority

#5130 Espresso test explore feed
  app/src/androidTest/java/org/wikipedia/Constants.kt
  app/src/androidTest/java/org/wikipedia/ExploreFeedTestSuite.kt
  app/src/androidTest/java/org/wikipedia/TestSuite.kt
  app/src/androidTest/java/org/wikipedia/base/BaseRobot.kt
  app/src/androidTest/java/org/wikipedia/base/BaseTest.kt
  app/src/androidTest/java/org/wikipedia/robots/SystemRobot.kt
  app/src/androidTest/java/org/wikipedia/robots/feature/ExploreFeedRobot.kt
  app/src/androidTest/java/org/wikipedia/robots/feature/SearchRobot.kt
  app/src/androidTest/java/org/wikipedia/robots/navigation/BottomNavRobot.kt
  app/src/androidTest/java/org/wikipedia/robots/screen/HomeScreenRobot.kt
  app/src/androidTest/java/org/wikipedia/tests/explorefeed/BecauseYouReadTest.kt
  app/src/androidTest/java/org/wikipedia/tests/explorefeed/FeedScreenSearchTest.kt
  app/src/androidTest/java/org/wikipedia/tests/explorefeed/FeedScreenSuggestedEditTest.kt
  app/src/androidTest/java/org/wikipedia/tests/explorefeed/FeedScreenTest.kt
  app/src/androidTest/java/org/wikipedia/tests/explorefeed/NavigationItemTest.kt
Labels: Ready to merge

#5150 Espresso test settings
  app/src/androidTest/java/org/wikipedia/SettingsTestSuite.kt
  app/src/androidTest/java/org/wikipedia/TestSuite.kt
  app/src/androidTest/java/org/wikipedia/base/BaseRobot.kt
  app/src/androidTest/java/org/wikipedia/base/BaseTest.kt
  app/src/androidTest/java/org/wikipedia/base/ColorAssertions.kt
  app/src/androidTest/java/org/wikipedia/robots/AppThemeRobot.kt
  app/src/androidTest/java/org/wikipedia/robots/SystemRobot.kt
  app/src/androidTest/java/org/wikipedia/robots/feature/EditorRobot.kt
  app/src/androidTest/java/org/wikipedia/robots/feature/ExploreFeedRobot.kt
  app/src/androidTest/java/org/wikipedia/robots/feature/PageRobot.kt
  app/src/androidTest/java/org/wikipedia/robots/feature/ReadingListRobot.kt
  app/src/androidTest/java/org/wikipedia/robots/feature/SearchRobot.kt
  app/src/androidTest/java/org/wikipedia/robots/feature/SettingsRobot.kt
  app/src/androidTest/java/org/wikipedia/robots/screen/HomeScreenRobot.kt
  app/src/androidTest/java/org/wikipedia/robots/screen/LanguageListRobot.kt
  app/src/androidTest/java/org/wikipedia/robots/screen/SavedScreenRobot.kt
  app/src/androidTest/java/org/wikipedia/tests/explorefeed/FeedScreenTest.kt
  app/src/androidTest/java/org/wikipedia/tests/settings/AboutSettingsTest.kt
  app/src/androidTest/java/org/wikipedia/tests/settings/AppThemeTest.kt
  app/src/androidTest/java/org/wikipedia/tests/settings/ChangingLanguageTest.kt
  app/src/androidTest/java/org/wikipedia/tests/settings/CollapseTablesTest.kt
  app/src/androidTest/java/org/wikipedia/tests/settings/CustomizeExploreFeedTest.kt
  app/src/androidTest/java/org/wikipedia/tests/settings/DownloadReadingListTest.kt
  app/src/androidTest/java/org/wikipedia/tests/settings/FontChangeTest.kt
  app/src/androidTest/java/org/wikipedia/tests/settings/FontSizeTest.kt
  app/src/androidTest/java/org/wikipedia/tests/settings/LinkPreviewTest.kt
  app/src/androidTest/java/org/wikipedia/tests/settings/ReadingFocusModeTest.kt
  app/src/androidTest/java/org/wikipedia/tests/settings/ShowImageTest.kt
Labels: Ready to merge

#5168 Fix potential crash when filtering reading list pages.
  app/src/main/java/org/wikipedia/readinglist/ReadingListBehaviorsUtil.kt
Labels: Minor

#5170 Fix another potential crash when deleting items from reading list.
  app/src/main/java/org/wikipedia/readinglist/ReadingListsFragment.kt
Labels: Minor

#5174 Periodic update of languages and static data.
  app/src/main/java/org/wikipedia/staticdata/ContributionsNameData.kt
  app/src/main/java/org/wikipedia/staticdata/FileAliasData.kt
  app/src/main/java/org/wikipedia/staticdata/MainPageNameData.kt
  app/src/main/java/org/wikipedia/staticdata/SpecialAliasData.kt
  app/src/main/java/org/wikipedia/staticdata/TalkAliasData.kt
  app/src/main/java/org/wikipedia/staticdata/UserAliasData.kt
  app/src/main/java/org/wikipedia/staticdata/UserTalkAliasData.kt
  app/src/main/res/values/languages_list.xml
Labels: Minor

#5172 Fix another potential crash throughout usages of PagingDataAdapter
  app/src/main/java/org/wikipedia/adapter/PagingDataAdapterPatched.kt
  app/src/main/java/org/wikipedia/categories/CategoryActivity.kt
  app/src/main/java/org/wikipedia/edit/insertmedia/InsertMediaActivity.kt
  app/src/main/java/org/wikipedia/edit/templates/TemplatesSearchActivity.kt
  app/src/main/java/org/wikipedia/page/edithistory/EditHistoryListActivity.kt
  app/src/main/java/org/wikipedia/page/edithistory/EditHistoryListViewModel.kt
  app/src/main/java/org/wikipedia/search/SearchResultsFragment.kt
  app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsRecentEditsFragment.kt
  app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsRecentEditsViewModel.kt
  app/src/main/java/org/wikipedia/talk/ArchivedTalkPagesActivity.kt
  app/src/main/java/org/wikipedia/usercontrib/UserContribListActivity.kt
  app/src/main/java/org/wikipedia/usercontrib/UserContribListViewModel.kt
Labels: Minor, High Priority

#5169 Upgrade to SDK 35
  app/build.gradle
  app/src/main/java/org/wikipedia/page/ExtendedBottomSheetDialogFragment.kt
  app/src/main/java/org/wikipedia/page/PageActivity.kt
  app/src/main/java/org/wikipedia/page/PageFragment.kt
  gradle/libs.versions.toml
Labels: Ready to merge

#5175 Follow-up: More proper handling of Dialog insets.
  app/src/main/java/org/wikipedia/page/ExtendedBottomSheetDialogFragment.kt
  app/src/main/java/org/wikipedia/page/linkpreview/LinkPreviewDialog.kt
Labels: Minor

#5180 Include `is_anon` field in EditAttemptStep events.
  app/src/main/java/org/wikipedia/analytics/eventplatform/EditAttemptStepEvent.kt
Labels: Minor, High Priority

#5182 Fix submitting image captions in correct language.
  app/src/main/java/org/wikipedia/descriptions/DescriptionEditViewModel.kt
Labels: Minor, High Priority

#5189 Fix Espresso Test
  app/src/androidTest/java/org/wikipedia/robots/feature/ExploreFeedRobot.kt
  app/src/androidTest/java/org/wikipedia/robots/feature/LoginRobot.kt
  app/src/androidTest/java/org/wikipedia/robots/feature/ReadingListRobot.kt
  app/src/androidTest/java/org/wikipedia/robots/screen/SavedScreenRobot.kt
  app/src/androidTest/java/org/wikipedia/tests/explorefeed/FeedScreenSuggestedEditTest.kt
  app/src/androidTest/java/org/wikipedia/tests/settings/AppThemeTest.kt
  app/src/androidTest/java/org/wikipedia/tests/settings/ShowImageTest.kt
  app/src/androidTest/java/org/wikipedia/testsuites/TestSuite.kt
Labels: Ready to merge
