Repository wikimedia/apps-android-wikipedia, pull requests merged in 2024-05, with the labels that each got.

#4635 Reduce false positives in Image Recs by checking for existing thumbnail.
  app/src/main/java/org/wikipedia/dataclient/Service.kt
  app/src/main/java/org/wikipedia/suggestededits/provider/EditingSuggestionsProvider.kt
Labels: Minor, High Priority

#4642 Update ImagePipelineBitmapGetter to a regular helper
  app/src/main/java/org/wikipedia/gallery/GalleryItemFragment.kt
  app/src/main/java/org/wikipedia/gallery/ImagePipelineBitmapGetter.kt
  app/src/main/java/org/wikipedia/main/MainFragment.kt
  app/src/main/java/org/wikipedia/places/PlacesFragment.kt
  app/src/main/java/org/wikipedia/richtext/CustomHtmlParser.kt
Labels: Ready to merge

#4634 Hygiene: remove custom UIState class and use standard Resouce for Notification
  app/src/main/java/org/wikipedia/notifications/NotificationActivity.kt
  app/src/main/java/org/wikipedia/notifications/NotificationRepository.kt
  app/src/main/java/org/wikipedia/notifications/NotificationViewModel.kt
Labels: Minor, Ready to merge

#4639 Fix: do not add additional language variants to the langlinks if the list is empty
  app/src/main/java/org/wikipedia/language/LangLinksViewModel.kt
  app/src/test/java/org/wikipedia/language/LangLinksActivityTest.java
  app/src/test/java/org/wikipedia/language/LangLinksActivityTest.kt
Labels: Minor, Ready to merge

#4633 Use coroutine in LeadImagesHandler
  app/src/main/java/org/wikipedia/dataclient/Service.kt
  app/src/main/java/org/wikipedia/page/leadimages/LeadImagesHandler.kt
Labels: Ready to merge

#4641 Use coroutine in CaptchaHandler
  app/src/main/java/org/wikipedia/captcha/CaptchaHandler.kt
  app/src/main/java/org/wikipedia/dataclient/Service.kt
  app/src/main/java/org/wikipedia/descriptions/DescriptionEditFragment.kt
  app/src/test/java/org/wikipedia/captcha/CaptchaClientTest.kt
Labels: Ready to merge

#4640 Use coroutine in AnnouncementClient
  app/src/main/java/org/wikipedia/dataclient/RestService.kt
  app/src/main/java/org/wikipedia/feed/announcement/AnnouncementClient.kt
  app/src/test/java/org/wikipedia/feed/announcement/AnnouncementClientTest.kt
Labels: Ready to merge

#4647 Fix: the app should hide the empty card if the content is not empty
  app/src/main/java/org/wikipedia/feed/FeedFragment.kt
Labels: Minor, Ready to merge

#4655 Correctly assign Job in CaptchaHandler.
  app/src/main/java/org/wikipedia/captcha/CaptchaHandler.kt
Labels: Minor, High Priority

#4658 Fix RTL awareness when inserting images into wikitext.
  app/src/main/java/org/wikipedia/edit/insertmedia/InsertMediaViewModel.kt
  app/src/test/java/org/wikipedia/edit/insertmedia/InsertMediaTest.kt
Labels: Minor, High Priority

#4656 Update Gradle and a few dependencies.
  app/build.gradle
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
Labels: dependencies

#4650 Fix: add additional try and catch block for loading lead images info in offline
  app/src/main/java/org/wikipedia/page/leadimages/LeadImagesHandler.kt
Labels: Minor, High Priority

#4662 Update list of codeowners.
  .github/CODEOWNERS
Labels: Minor

#4661 Follow-up to Google Pay integration
  app/src/extra/java/org/wikipedia/donate/GooglePayActivity.kt
  app/src/extra/java/org/wikipedia/donate/GooglePayComponent.kt
  app/src/extra/java/org/wikipedia/donate/GooglePayViewModel.kt
  app/src/main/java/org/wikipedia/donate/DonateDialog.kt
  app/src/main/java/org/wikipedia/page/campaign/CampaignDialog.kt
Labels: Minor, High Priority

#4659 Convert GeoIPCookie and its test case to Kotlin
  app/src/main/java/org/wikipedia/feed/announcement/GeoIPCookie.java
  app/src/main/java/org/wikipedia/feed/announcement/GeoIPCookie.kt
  app/src/main/java/org/wikipedia/util/GeoUtil.kt
  app/src/test/java/org/wikipedia/feed/announcement/GeoIPCookieUnmarshallerTest.java
  app/src/test/java/org/wikipedia/feed/announcement/GeoIPCookieUnmarshallerTest.kt
Labels: Minor

#4667 Send correct country code when making payment.
  app/src/extra/java/org/wikipedia/donate/GooglePayViewModel.kt
Labels: Minor, High Priority

#4668 Allow Google Pay only in supported countries received from config.
  app/src/extra/java/org/wikipedia/donate/GooglePayViewModel.kt
  app/src/main/java/org/wikipedia/dataclient/donate/DonationConfig.kt
Labels: Minor, High Priority

#4671 Fix: make sure sending data if it is from Edit Patrol
  app/src/main/java/org/wikipedia/talk/TalkReplyActivity.kt
Labels: Minor, High Priority

#4670 Always send final amount in canonical decimal format.
  app/src/extra/java/org/wikipedia/donate/GooglePayComponent.kt
  app/src/extra/java/org/wikipedia/donate/GooglePayViewModel.kt
Labels: Minor, High Priority

#4672 Remove Places survey.
  app/src/main/java/org/wikipedia/places/PlacesFragment.kt
  app/src/main/java/org/wikipedia/places/PlacesFragmentViewModel.kt
  app/src/main/java/org/wikipedia/settings/Prefs.kt
  app/src/main/java/org/wikipedia/views/SurveyDialog.kt
  app/src/main/res/values/preference_keys.xml
  app/src/main/res/xml/developer_preferences.xml
Labels: High Priority

#4644 Correctly handle language variants selection in LangLinks
  app/src/main/java/org/wikipedia/language/LangLinksViewModel.kt
Labels: High Priority, Ready to merge

#4680 GPay: Fix setting language for currency NumberFormat.
  app/src/extra/java/org/wikipedia/donate/GooglePayViewModel.kt
Labels: Minor, High Priority

#4679 Image recs: insert into infobox only for English.
  app/src/main/java/org/wikipedia/edit/insertmedia/InsertMediaViewModel.kt
Labels: Minor, High Priority

#4648 Use coroutine in EditSummary related classes
  app/src/main/java/org/wikipedia/edit/db/EditSummary.kt
  app/src/main/java/org/wikipedia/edit/db/EditSummaryDao.kt
  app/src/main/java/org/wikipedia/edit/summaries/EditSummaryHandler.kt
Labels: Minor, Ready to merge

#4685 Follow-up to coroutines in EditSummary.
  app/src/main/java/org/wikipedia/edit/summaries/EditSummaryFragment.kt
  app/src/main/java/org/wikipedia/edit/summaries/EditSummaryHandler.kt
Labels: Minor

#4681 Fix: show top read title and description correctly for zhwiki
  app/src/main/java/org/wikipedia/dataclient/Service.kt
  app/src/main/java/org/wikipedia/feed/aggregated/AggregatedFeedContentClient.kt
Labels: Ready to merge

#4691 Further improve compatibility for devices without hardware GPS.
  app/src/main/AndroidManifest.xml
Labels: Minor, High Priority

#4689 Follow-up to coroutines in PageFragmentLoadState.
  app/src/main/java/org/wikipedia/page/PageFragment.kt
  app/src/main/java/org/wikipedia/page/PageFragmentLoadState.kt
  app/src/main/java/org/wikipedia/pageimages/db/PageImageDao.kt
  app/src/main/java/org/wikipedia/savedpages/SavedPageSyncService.kt
Labels: Minor

#4651 Hygiene: clean up code in PageAvailableOfflineHandler
  app/src/main/java/org/wikipedia/feed/view/ListCardItemView.kt
  app/src/main/java/org/wikipedia/feed/view/ListCardView.kt
  app/src/main/java/org/wikipedia/history/HistoryFragment.kt
  app/src/main/java/org/wikipedia/page/PageAvailableOfflineHandler.kt
  app/src/main/java/org/wikipedia/page/PageFragment.kt
  app/src/main/java/org/wikipedia/readinglist/ReadingListFragment.kt
  app/src/main/java/org/wikipedia/readinglist/ReadingListsFragment.kt
  app/src/main/java/org/wikipedia/readinglist/db/ReadingListPageDao.kt
Labels: Minor

#4690 Lazily load Read More items.
  app/src/main/java/org/wikipedia/bridge/JavaScriptActionHandler.kt
  app/src/main/java/org/wikipedia/page/PageFragment.kt
  app/src/main/java/org/wikipedia/page/PageViewModel.kt
Labels: Ready to merge

#4696 Fix: incorrect text alignment in Wikipedia languages screen
  app/src/main/java/org/wikipedia/settings/languages/WikipediaLanguagesItemView.kt
  app/src/main/res/layout/item_wikipedia_language.xml
Labels: Minor

#4698 Remove feature flag for Google Pay.
  app/src/main/java/org/wikipedia/donate/DonateViewModel.kt
Labels: Minor, High Priority

#4700 Follow-up to coroutines in SyntaxHighlighter.
  app/src/main/java/org/wikipedia/edit/richtext/SyntaxHighlighter.kt
Labels: Minor

#4711 Hygiene: remove unnecessary usages of withContext{}
  app/src/main/java/org/wikipedia/analytics/eventplatform/MachineGeneratedArticleDescriptionsAnalyticsHelper.kt
  app/src/main/java/org/wikipedia/readinglist/ReadingListFragment.kt
  app/src/main/java/org/wikipedia/talk/TalkReplyViewModel.kt
  app/src/main/java/org/wikipedia/talk/TalkTopicsViewModel.kt
  app/src/main/java/org/wikipedia/talk/template/TalkTemplatesViewModel.kt
  app/src/main/java/org/wikipedia/usercontrib/UserInformationDialogViewModel.kt
Labels: Minor
