Repository wikimedia/apps-android-wikipedia, pull requests merged in 2024-08, with the labels that each got.

#4849 Fix proper injection and hiding of context menu over WebView.
  app/src/main/java/org/wikipedia/page/PageActivity.kt
Labels: Minor, High Priority

#4840 Simplify MGAD analytics and rip out ABC test.
  app/src/main/java/org/wikipedia/analytics/eventplatform/MachineGeneratedArticleDescriptionABCTest.kt
  app/src/main/java/org/wikipedia/analytics/eventplatform/MachineGeneratedArticleDescriptionsAnalyticsHelper.kt
  app/src/main/java/org/wikipedia/descriptions/DescriptionEditActivity.kt
  app/src/main/java/org/wikipedia/descriptions/DescriptionEditFragment.kt
  app/src/main/java/org/wikipedia/descriptions/DescriptionEditTutorialActivity.kt
  app/src/main/java/org/wikipedia/descriptions/DescriptionEditView.kt
  app/src/main/java/org/wikipedia/edit/EditTags.kt
  app/src/main/java/org/wikipedia/settings/Prefs.kt
  app/src/main/res/values/preference_keys.xml
Labels: Ready to merge

#4852 Show "Talk" button in Diff view for all cases.
  app/src/main/java/org/wikipedia/diff/ArticleEditDetailsFragment.kt
  app/src/main/res/layout/fragment_article_edit_details.xml
Labels: Minor

#4856 Fix bottom scroll position in Diff view.
  app/src/main/res/layout/fragment_article_edit_details.xml
Labels: Minor

#4858 Add white background transformation to the artilce thumbnail in widget
  app/src/main/java/org/wikipedia/widgets/WidgetProviderFeaturedPage.kt
Labels: Minor

#4868 Improve/fix inputType of Report message for MGAD descriptions.
  app/src/main/res/layout/dialog_description_suggestion_report.xml
Labels: Minor

#4789 Show a snackbar message for places that do have articles nearby
  app/src/main/java/org/wikipedia/places/PlacesFragment.kt
  app/src/main/java/org/wikipedia/settings/DeveloperSettingsPreferenceLoader.kt
  app/src/main/java/org/wikipedia/settings/Prefs.kt
  app/src/main/res/values-qq/strings.xml
  app/src/main/res/values/dev_settings_strings.xml
  app/src/main/res/values/preference_keys.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/xml/developer_preferences.xml
Labels: Ready to merge

#4824 Add Explore Feed as an Entry point for Places
  app/src/main/java/org/wikipedia/feed/FeedContentType.kt
  app/src/main/java/org/wikipedia/feed/FeedCoordinatorBase.kt
  app/src/main/java/org/wikipedia/feed/model/CardType.kt
  app/src/main/java/org/wikipedia/feed/places/PlacesCard.kt
  app/src/main/java/org/wikipedia/feed/places/PlacesCardView.kt
  app/src/main/java/org/wikipedia/feed/places/PlacesFeedClient.kt
  app/src/main/java/org/wikipedia/history/HistoryEntry.kt
  app/src/main/java/org/wikipedia/readinglist/LongPressMenu.kt
  app/src/main/java/org/wikipedia/util/GeoUtil.kt
  app/src/main/java/org/wikipedia/views/ViewUtil.kt
  app/src/main/res/drawable/illustration_places_enable_location.xml
  app/src/main/res/layout/view_places_card.xml
  app/src/main/res/menu/menu_long_press.xml
  app/src/main/res/values-qq/strings.xml
  app/src/main/res/values/strings.xml
Labels: Ready to merge

#4877 Re-enable preBeta feature flag for MGAD.
  app/src/main/java/org/wikipedia/descriptions/DescriptionEditFragment.kt
  app/src/main/java/org/wikipedia/views/SuggestedArticleDescriptionsDialog.kt
Labels: Minor, High Priority

#4879 Add entry point event tracking for Explore Card entry in Places
  app/src/main/java/org/wikipedia/feed/places/PlacesCardView.kt
Labels: Minor, High Priority

#4883 Expand patrolling edits for Igbo Wikipedia.
  app/src/main/java/org/wikipedia/dataclient/Service.kt
  app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsTasksFragmentViewModel.kt
Labels: Minor

#4882 Fix blocked message in Suggested Edits, and use coroutines.
  app/src/main/java/org/wikipedia/dataclient/Service.kt
  app/src/main/java/org/wikipedia/dataclient/mwapi/MwServiceError.kt
  app/src/main/java/org/wikipedia/edit/EditSectionActivity.kt
  app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsTasksFragment.kt
  app/src/main/java/org/wikipedia/util/ThrowableUtil.kt
  app/src/test/java/org/wikipedia/login/UserExtendedInfoClientTest.kt
Labels: Minor

#4886 Hugely improve performance of finding text in editor window.
  app/src/main/java/org/wikipedia/edit/FindInEditorActionProvider.kt
Labels: Minor

#4888 Hygiene: clean up unused preferences and test group strings
  app/src/main/java/org/wikipedia/settings/Prefs.kt
  app/src/main/res/values/preference_keys.xml
  app/src/main/res/xml/developer_preferences.xml
Labels: Minor

#4890 Initial prep work for temporary accounts.
  app/src/main/java/org/wikipedia/auth/AccountUtil.kt
  app/src/main/java/org/wikipedia/csrf/CsrfTokenClient.kt
  app/src/main/java/org/wikipedia/dataclient/SharedPreferenceCookieManager.kt
  app/src/main/java/org/wikipedia/descriptions/DescriptionEditFragment.kt
  app/src/main/java/org/wikipedia/diff/ArticleEditDetailsFragment.kt
  app/src/main/java/org/wikipedia/edit/EditSectionActivity.kt
  app/src/main/java/org/wikipedia/feed/announcement/GeoIPCookieUnmarshaller.kt
  app/src/main/java/org/wikipedia/main/MainFragment.kt
  app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsRecentEditsFragment.kt
  app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsTasksFragment.kt
  app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsTasksFragmentViewModel.kt
  app/src/main/java/org/wikipedia/talk/NotificationDirectReplyHelper.kt
  app/src/main/java/org/wikipedia/talk/TalkReplyActivity.kt
Labels: Minor

#4895 Move language variant method to L10nUtil
  app/src/main/java/org/wikipedia/feed/aggregated/AggregatedFeedContentClient.kt
  app/src/main/java/org/wikipedia/util/L10nUtil.kt
Labels: Minor

#4894 Add ABC test and target languages logic for Recommended Content
  app/src/main/java/org/wikipedia/analytics/ABTest.kt
  app/src/main/java/org/wikipedia/analytics/metricsplatform/RecommendedContentABCTest.kt
  app/src/main/java/org/wikipedia/analytics/metricsplatform/RecommendedContentAnalyticsHelper.kt
  app/src/main/java/org/wikipedia/recommendedcontent/RecommendedContentFragment.kt
  app/src/main/java/org/wikipedia/search/RecentSearchesFragment.kt
  app/src/main/res/layout/fragment_recommended_content.xml
  app/src/main/res/xml/developer_preferences.xml
Labels: WIP

#4908 Use automatic resource management for Closables.
  app/src/main/java/org/wikipedia/alphaupdater/AlphaUpdateChecker.kt
  app/src/main/java/org/wikipedia/readinglist/ReadingListsFragment.kt
  app/src/main/java/org/wikipedia/savedpages/SavedPageSyncService.kt
  app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsImageRecsFragmentViewModel.kt
  app/src/main/java/org/wikipedia/util/FileUtil.kt
Labels: Minor

#4907 Plug our own HttpClient into Metrics library.
  app/src/main/java/org/wikipedia/analytics/metricsplatform/MetricsPlatform.kt
Labels: Minor
