Repository wikimedia/apps-android-wikipedia, pull requests merged in 2024-02, with the labels that each got.

#4432 Refactor and remove race condition from AppInteractionEvent instantiation.
  app/src/main/java/org/wikipedia/analytics/eventplatform/AppInteractionEvent.kt
  app/src/main/java/org/wikipedia/analytics/eventplatform/DonorExperienceEvent.kt
  app/src/main/java/org/wikipedia/analytics/eventplatform/PatrollerExperienceEvent.kt
Labels: Minor

#4436 Respect isImageDownloadedEnabled setting in Places
  app/src/main/java/org/wikipedia/places/PlacesFragment.kt
Labels: Minor

#4433 Fix: use null-safe for LinkPreviewDialog action menu options
  app/src/main/java/org/wikipedia/readinglist/LongPressMenu.kt
Labels: Minor

#4434 Fix: use lastKnownLocation instead of the last map location for distance
  app/src/main/java/org/wikipedia/places/PlacesFragment.kt
Labels: Minor

#4435 Fix: show the progressbar correctly in the diff view
  app/src/main/res/layout/fragment_article_edit_details.xml
Labels: Minor

#4437 Instrumentation updates for Widgets.
  app/src/main/java/org/wikipedia/widgets/WidgetProviderFeaturedPage.kt
Labels: Minor

#4442 Fix foreground color of MapView while loading.
  app/src/main/res/layout/fragment_places.xml
Labels: Minor

#4445 Fix: save lastKnowLocation in ViewModel to keep showing distance in list in Places
  app/src/main/java/org/wikipedia/places/PlacesFragment.kt
  app/src/main/java/org/wikipedia/places/PlacesFragmentViewModel.kt
Labels: High Priority

#4449 Fix/improve handling of insets in Places.
  app/src/main/java/org/wikipedia/places/PlacesFragment.kt
  app/src/main/res/layout/fragment_places.xml
Labels: Minor, High Priority

#4451 Places: Always recycle Bitmaps when clearing annotation cache.
  app/src/main/java/org/wikipedia/places/PlacesFragment.kt
  app/src/main/res/layout/fragment_places.xml
Labels: Minor, High Priority

#4454 Reset selected language if the previous selected language was deleted
  app/src/main/java/org/wikipedia/usercontrib/UserContribFilterActivity.kt
Labels: Minor

#4456 Update logic for Places survey.
  app/src/main/java/org/wikipedia/main/MainActivity.kt
  app/src/main/java/org/wikipedia/places/PlacesFragment.kt
  app/src/main/java/org/wikipedia/places/PlacesFragmentViewModel.kt
  app/src/main/res/xml/developer_preferences.xml
Labels: Minor, High Priority

#4461 Ensure that search bar hint is single-line.
  app/src/main/res/layout/activity_page.xml
Labels: Minor

#4463 Correctly handle WebView update exception.
  app/src/main/java/org/wikipedia/page/PageActivity.kt
Labels: Minor

#4472 Use proper hint for Search when entering from Places.
  app/src/main/java/org/wikipedia/search/SearchFragment.kt
Labels: Minor

#4473 Places: Translations update
  app/src/main/res/values-bn/strings.xml
  app/src/main/res/values-hi/strings.xml
  app/src/main/res/values-ur/strings.xml
Labels: High Priority

#4478 Fix possible crash when tapping on map markers with location permissions disabled.
  app/src/main/java/org/wikipedia/places/PlacesFragment.kt
Labels: Minor, High Priority

#4480 Perform full reading list sync if previous sync is too old.
  app/src/main/java/org/wikipedia/readinglist/sync/ReadingListSyncAdapter.kt
Labels: Minor

#4482 Prevent obscure race condition when querying Stream Configs.
  app/src/main/java/org/wikipedia/analytics/eventplatform/EventPlatformClient.kt
Labels: Minor

#4487 Places: Fix requiring permissions to go to article map marker.
  app/src/main/java/org/wikipedia/places/PlacesFragment.kt
Labels: Minor, High Priority

#4493 Possibly fix TransactionTooLarge crashes.
  app/src/main/java/org/wikipedia/random/RandomFragment.kt
Labels: Minor, High Priority

#4494 Further improve concurrency in EventPlatformClient.
  app/src/main/java/org/wikipedia/analytics/eventplatform/EventPlatformClient.kt
Labels: Minor, High Priority
