Repository wikimedia/apps-android-wikipedia, pull requests merged in 2024-11, with the labels that each got.

#5076 Add strings for Contributions Dashboard
  app/src/main/res/values-qq/strings.xml
  app/src/main/res/values/strings.xml
Labels: Ready to merge

#5074 Upgrade to SDK 35.
  app/build.gradle
  app/src/androidTest/java/org/wikipedia/database/UpgradeFromPreRoomTest.kt
  app/src/androidTest/java/org/wikipedia/main/LoggedInTests.kt
  app/src/androidTest/java/org/wikipedia/main/SmokeTests.kt
  app/src/main/java/org/wikipedia/database/AppDatabase.kt
  app/src/main/java/org/wikipedia/page/customize/CustomizeToolbarViewModel.kt
Labels: dependencies, Ready to merge

#5079 Mailto links bug
  app/src/main/java/org/wikipedia/page/LinkHandler.kt
  app/src/main/java/org/wikipedia/settings/SettingsPreferenceLoader.kt
  app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsImageRecsFragment.kt
  app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsRecentEditsFragment.kt
  app/src/main/java/org/wikipedia/util/FeedbackUtil.kt
Labels: Bug, Ready to merge

#5090 Display SVG files in correct language in Gallery.
  app/src/main/java/org/wikipedia/dataclient/Service.kt
  app/src/main/java/org/wikipedia/gallery/GalleryItemFragment.kt
  app/src/main/java/org/wikipedia/gallery/ImageInfo.kt
  app/src/main/java/org/wikipedia/util/ImageUrlUtil.kt
Labels: Minor

#5091 Minor: remove the redundant suppression in ImageInfo
  app/src/main/java/org/wikipedia/gallery/ImageInfo.kt
Labels: Minor

#5094 Fix: scroll to the selected language tab when back from the language list
  app/src/main/java/org/wikipedia/search/SearchFragment.kt
Labels: Minor

#5089 Fix: design signoff updates for Contribute Tab and Donor history
  app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsTasksFragment.kt
  app/src/main/res/layout/activity_donor_history.xml
  app/src/main/res/layout/fragment_suggested_edits_tasks.xml
  app/src/main/res/values/styles.xml
Labels: Ready to merge

#5096 Fix incorrectly formatted percent in string, causing crash (!).
  app/src/main/res/values-nl/strings.xml
Labels: Minor, High Priority

#5099 Apply theme-based background color to the swipeRefereshLayout progress spinner
  app/src/main/res/values/styles.xml
Labels: Ready to merge

#5103 Fix automatic re-logging-in of user in background.
  app/src/main/java/org/wikipedia/csrf/CsrfTokenClient.kt
  app/src/main/java/org/wikipedia/login/LoginFailedException.kt
Labels: Minor, High Priority

#5092 Clean up Recommended Content experiment code from the app
  app/src/main/java/org/wikipedia/Constants.kt
  app/src/main/java/org/wikipedia/analytics/metricsplatform/ArticleEvent.kt
  app/src/main/java/org/wikipedia/analytics/metricsplatform/RecommendedContentABCTest.kt
  app/src/main/java/org/wikipedia/analytics/metricsplatform/RecommendedContentAnalyticsHelper.kt
  app/src/main/java/org/wikipedia/history/HistoryEntry.kt
  app/src/main/java/org/wikipedia/page/PageFragment.kt
  app/src/main/java/org/wikipedia/recommendedcontent/RecommendedContentFragment.kt
  app/src/main/java/org/wikipedia/recommendedcontent/RecommendedContentSectionView.kt
  app/src/main/java/org/wikipedia/recommendedcontent/RecommendedContentViewModel.kt
  app/src/main/java/org/wikipedia/search/RecentSearchesFragment.kt
  app/src/main/java/org/wikipedia/search/SearchFragment.kt
  app/src/main/java/org/wikipedia/settings/Prefs.kt
  app/src/main/java/org/wikipedia/views/SurveyDialog.kt
  app/src/main/res/layout/fragment_recommended_content.xml
  app/src/main/res/layout/fragment_search_recent.xml
  app/src/main/res/layout/item_recommended_content_search_history.xml
  app/src/main/res/layout/item_recommended_content_section_text.xml
  app/src/main/res/values-qq/strings.xml
  app/src/main/res/values/preference_keys.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/xml/developer_preferences.xml
Labels: Ready to merge

#5095 Fix: Overflow menu design changes
  app/src/main/res/layout/view_donor_badge.xml
Labels: Ready to merge

#5106 Add string for the Contributions Dashboard
  app/src/main/res/values-qq/strings.xml
  app/src/main/res/values/strings.xml
Labels: Minor

#5112 Use article language for summary when adding/changing a description.
  app/src/main/java/org/wikipedia/descriptions/DescriptionEditViewModel.kt
Labels: Minor, Ready to merge

#5111 Strings for Rabbit Holes.
  app/src/main/res/values-qq/strings.xml
  app/src/main/res/values/strings.xml
Labels: Minor

#5110 A bit more cleanup from Recommended Content.
  app/src/main/java/org/wikipedia/analytics/metricsplatform/ArticleEvent.kt
  app/src/main/res/xml/developer_preferences.xml
Labels: Minor

#5113 Refine common model for error responses.
  app/src/extra/java/org/wikipedia/push/WikipediaFirebaseMessagingService.kt
  app/src/main/java/org/wikipedia/dataclient/ServiceError.kt
  app/src/main/java/org/wikipedia/dataclient/mwapi/MwException.kt
  app/src/main/java/org/wikipedia/dataclient/mwapi/MwResponse.kt
  app/src/main/java/org/wikipedia/dataclient/mwapi/MwServiceError.kt
  app/src/main/java/org/wikipedia/dataclient/mwapi/UserInfo.kt
  app/src/main/java/org/wikipedia/dataclient/okhttp/HttpStatusException.kt
  app/src/main/java/org/wikipedia/dataclient/restbase/RbServiceError.kt
  app/src/main/java/org/wikipedia/notifications/PollNotificationWorker.kt
  app/src/main/java/org/wikipedia/readinglist/sync/ReadingListClient.kt
  app/src/main/java/org/wikipedia/readinglist/sync/SyncedReadingLists.kt
Labels: Minor, Ready to merge

#5109 Use ShapeableImageView for rounding corners.
  app/src/main/java/org/wikipedia/captcha/CaptchaHandler.kt
  app/src/main/java/org/wikipedia/commons/FilePageView.kt
  app/src/main/java/org/wikipedia/edit/insertmedia/InsertMediaActivity.kt
  app/src/main/java/org/wikipedia/edit/insertmedia/InsertMediaSettingsFragment.kt
  app/src/main/java/org/wikipedia/feed/view/CardLargeHeaderView.kt
  app/src/main/java/org/wikipedia/feed/view/ListCardItemView.kt
  app/src/main/java/org/wikipedia/gallery/GalleryActivity.kt
  app/src/main/java/org/wikipedia/gallery/GalleryItemFragment.kt
  app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsImageRecsFragment.kt
  app/src/main/java/org/wikipedia/views/FaceAndColorDetectImageView.kt
  app/src/main/java/org/wikipedia/views/ViewUtil.kt
  app/src/main/res/layout/view_card_header_large.xml
  app/src/main/res/layout/view_list_card_item.xml
  app/src/main/res/values/styles.xml
Labels: Minor

#5116 [Contributions Dashboard] add isDonor preference for the optional donor info
  app/src/main/java/org/wikipedia/donate/DonorHistoryViewModel.kt
  app/src/main/java/org/wikipedia/donate/DonorStatus.kt
  app/src/main/java/org/wikipedia/settings/Prefs.kt
  app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsTasksFragment.kt
  app/src/main/res/values/preference_keys.xml
Labels: Ready to merge

#5119 Fix donor badge disable click state
  app/src/main/java/org/wikipedia/main/MainActivity.kt
  app/src/main/java/org/wikipedia/views/DonorBadgeView.kt
Labels: Ready to merge

#5086 Refining Espresso test
  app/src/androidTest/java/org/wikipedia/FakeData.kt
  app/src/androidTest/java/org/wikipedia/TestSuite.kt
  app/src/androidTest/java/org/wikipedia/base/BaseRobot.kt
  app/src/androidTest/java/org/wikipedia/base/BaseTest.kt
  app/src/androidTest/java/org/wikipedia/main/LoggedInTests.kt
  app/src/androidTest/java/org/wikipedia/main/SmokeTests.kt
  app/src/androidTest/java/org/wikipedia/robots/SystemRobot.kt
  app/src/androidTest/java/org/wikipedia/robots/ThemeRobot.kt
  app/src/androidTest/java/org/wikipedia/robots/feature/EditorRobot.kt
  app/src/androidTest/java/org/wikipedia/robots/feature/ExploreFeedRobot.kt
  app/src/androidTest/java/org/wikipedia/robots/feature/LoginRobot.kt
  app/src/androidTest/java/org/wikipedia/robots/feature/OnboardingRobot.kt
  app/src/androidTest/java/org/wikipedia/robots/feature/PageRobot.kt
  app/src/androidTest/java/org/wikipedia/robots/feature/SearchRobot.kt
  app/src/androidTest/java/org/wikipedia/robots/feature/SettingsRobot.kt
  app/src/androidTest/java/org/wikipedia/robots/navigation/BottomNavRobot.kt
  app/src/androidTest/java/org/wikipedia/robots/screen/ContributionScreenScreenRobot.kt
  app/src/androidTest/java/org/wikipedia/robots/screen/HistoryScreenRobot.kt
  app/src/androidTest/java/org/wikipedia/robots/screen/HomeScreenRobot.kt
  app/src/androidTest/java/org/wikipedia/robots/screen/NotificationScreenRobot.kt
  app/src/androidTest/java/org/wikipedia/robots/screen/SavedScreenRobot.kt
  app/src/androidTest/java/org/wikipedia/test/LoginTest.kt
  app/src/androidTest/java/org/wikipedia/test/loggedinuser/ContributionScreenTest.kt
  app/src/androidTest/java/org/wikipedia/test/loggedinuser/NotificationScreenTest.kt
  app/src/androidTest/java/org/wikipedia/test/loggedinuser/SuggestedEditCardTest.kt
  app/src/androidTest/java/org/wikipedia/test/loggedinuser/WatchListTest.kt
  app/src/androidTest/java/org/wikipedia/test/loggedoutuser/EditArticleTest.kt
  app/src/androidTest/java/org/wikipedia/test/loggedoutuser/ExploreFeedTest.kt
  app/src/androidTest/java/org/wikipedia/test/loggedoutuser/HistoryScreenTest.kt
  app/src/androidTest/java/org/wikipedia/test/loggedoutuser/HomeScreenTest.kt
  app/src/androidTest/java/org/wikipedia/test/loggedoutuser/OnboardingTest.kt
  app/src/androidTest/java/org/wikipedia/test/loggedoutuser/PageTest.kt
  app/src/androidTest/java/org/wikipedia/test/loggedoutuser/SavedScreenTest.kt
  app/src/androidTest/java/org/wikipedia/test/loggedoutuser/SettingsTest.kt
  app/src/androidTest/java/org/wikipedia/test/search/SearchExternalIntentTest.kt
  app/src/androidTest/java/org/wikipedia/test/search/SearchIntentTest.kt
  app/src/main/java/org/wikipedia/page/tabs/TabActivity.kt
  app/src/main/res/layout/fragment_suggested_edits_card_item.xml
Labels: Ready to merge

#5121 Fix: app icon "Donor Benefit" label border
  app/src/main/res/drawable/rounded_6dp_stroke_1dp.xml
  app/src/main/res/layout/dialog_app_icon.xml
Labels: Ready to merge

#5104 [Contributions Dashboard] Wire up the instrumentation
  app/src/main/java/org/wikipedia/analytics/eventplatform/ContributionsDashboardEvent.kt
  app/src/main/java/org/wikipedia/analytics/eventplatform/DonorExperienceEvent.kt
  app/src/main/java/org/wikipedia/donate/DonorHistoryActivity.kt
  app/src/main/java/org/wikipedia/main/MainActivity.kt
  app/src/main/java/org/wikipedia/main/MainFragment.kt
  app/src/main/java/org/wikipedia/navtab/MenuNavTabDialog.kt
  app/src/main/java/org/wikipedia/page/PageFragment.kt
  app/src/main/java/org/wikipedia/settings/AppIconDialog.kt
  app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsTasksFragment.kt
  app/src/main/java/org/wikipedia/usercontrib/ContributionsDashboardHelper.kt
  app/src/main/java/org/wikipedia/views/PageActionOverflowView.kt
Labels: Ready to merge

#5124 Adds missing string resource on Contribution Screen Test class
  app/src/androidTest/java/org/wikipedia/robots/screen/ContributionScreenScreenRobot.kt
Labels: Minor, Ready to merge

#5125 Convert FixedDrawerLayout to Kotlin
  app/src/main/java/androidx/drawerlayout/widget/FixedDrawerLayout.java
  app/src/main/java/androidx/drawerlayout/widget/FixedDrawerLayout.kt
Labels: Minor

#5126 Convert test classes to Kotlin
  app/src/test/java/org/wikipedia/test/ImmediateExecutor.java
  app/src/test/java/org/wikipedia/test/ImmediateExecutorService.java
  app/src/test/java/org/wikipedia/test/ImmediateExecutorService.kt
  app/src/test/java/org/wikipedia/test/TestFileUtil.java
  app/src/test/java/org/wikipedia/test/TestFileUtil.kt
  app/src/test/java/org/wikipedia/test/TestParcelUtil.java
  app/src/test/java/org/wikipedia/test/TestParcelUtil.kt
Labels: Minor

#5133 Roll back targeting of SDK 35 to 34.
  app/build.gradle
  gradle/libs.versions.toml
Labels: Minor, High Priority

#5138 Fix: instrumentation for Contributions Dashboard
  app/src/main/java/org/wikipedia/usercontrib/ContributionsDashboardHelper.kt
Labels: High Priority

#5140 Fix app icon missing from the app info screen
  app/src/main/AndroidManifest.xml
Labels: High Priority, Ready to merge

#5147 Fix updates survey form
  app/src/main/java/org/wikipedia/usercontrib/ContributionsDashboardHelper.kt
Labels: Ready to merge

#5143 Add <small> tag to support <sub> and <sup> HTML tags in TextView
  app/src/main/java/org/wikipedia/richtext/CustomHtmlParser.kt
Labels: Minor
