Repository wikimedia/apps-android-wikipedia, pull requests merged in 2024-10, with the labels that each got.

#4977 Use CoroutineWorker in SavedPageSyncService
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/wikipedia/dataclient/RestService.kt
  app/src/main/java/org/wikipedia/offline/db/OfflineObjectDao.kt
  app/src/main/java/org/wikipedia/savedpages/SavedPageSyncService.kt
Labels: Ready to merge

#4913 Refactoring CreateAccountActivity to use coroutine
  app/src/main/java/org/wikipedia/createaccount/CreateAccountActivity.kt
  app/src/main/java/org/wikipedia/createaccount/CreateAccountActivityViewModel.kt
  app/src/main/java/org/wikipedia/dataclient/Service.kt
  app/src/test/java/org/wikipedia/createaccount/CreateAccountClientTest.kt
  app/src/test/java/org/wikipedia/createaccount/CreateAccountInfoClientTest.kt
Labels: Ready to merge

#4982 Fix: potential crash in the OnOffsetChangedListener
  app/src/main/java/org/wikipedia/feed/news/NewsFragment.kt
  app/src/main/java/org/wikipedia/feed/onthisday/OnThisDayFragment.kt
Labels: Minor

#5000 Instrument donation results.
  app/src/extra/java/org/wikipedia/donate/GooglePayActivity.kt
  app/src/main/java/org/wikipedia/dataclient/donate/CampaignCollection.kt
  app/src/main/java/org/wikipedia/donate/DonationResult.kt
  app/src/main/java/org/wikipedia/page/PageActivity.kt
  app/src/main/java/org/wikipedia/settings/Prefs.kt
  app/src/main/res/values/preference_keys.xml
  app/src/main/res/xml/developer_preferences.xml
Labels: High Priority

#5002 Remove unused sharable readinglist survey strings
  app/src/main/res/values-ar/strings.xml
  app/src/main/res/values-b+sr+Latn/strings.xml
  app/src/main/res/values-b+tt+Cyrl/strings.xml
  app/src/main/res/values-ba/strings.xml
  app/src/main/res/values-be/strings.xml
  app/src/main/res/values-bew/strings.xml
  app/src/main/res/values-bn/strings.xml
  app/src/main/res/values-ca/strings.xml
  app/src/main/res/values-ckb/strings.xml
  app/src/main/res/values-dag/strings.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-dga/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fa/strings.xml
  app/src/main/res/values-fi/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-ha/strings.xml
  app/src/main/res/values-hi/strings.xml
  app/src/main/res/values-hu/strings.xml
  app/src/main/res/values-ia/strings.xml
  app/src/main/res/values-in/strings.xml
  app/src/main/res/values-io/strings.xml
  app/src/main/res/values-is/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values-iw/strings.xml
  app/src/main/res/values-ja/strings.xml
  app/src/main/res/values-ko/strings.xml
  app/src/main/res/values-krc/strings.xml
  app/src/main/res/values-lb/strings.xml
  app/src/main/res/values-lt/strings.xml
  app/src/main/res/values-mk/strings.xml
  app/src/main/res/values-nb/strings.xml
  app/src/main/res/values-nl/strings.xml
  app/src/main/res/values-nqo/strings.xml
  app/src/main/res/values-pt-rBR/strings.xml
  app/src/main/res/values-pt/strings.xml
  app/src/main/res/values-qq/strings.xml
  app/src/main/res/values-ru/strings.xml
  app/src/main/res/values-sd/strings.xml
  app/src/main/res/values-se/strings.xml
  app/src/main/res/values-sl/strings.xml
  app/src/main/res/values-sr/strings.xml
  app/src/main/res/values-sv/strings.xml
  app/src/main/res/values-tr/strings.xml
  app/src/main/res/values-uk/strings.xml
  app/src/main/res/values-ur/strings.xml
  app/src/main/res/values-uz/strings.xml
  app/src/main/res/values-zh-rTW/strings.xml
  app/src/main/res/values-zh/strings.xml
  app/src/main/res/values/strings.xml
Labels: Minor, Ready to merge

#5015 Fix crash when leaving NewsFragment.
  app/src/main/java/org/wikipedia/feed/news/NewsFragment.kt
Labels: Minor, High Priority

#5008 Add Places app shortcut to the app
  app/src/main/java/org/wikipedia/Constants.kt
  app/src/main/java/org/wikipedia/appshortcuts/AppShortcuts.kt
  app/src/main/java/org/wikipedia/main/MainFragment.kt
  app/src/main/res/drawable/appshortcut_ic_places.xml
  app/src/main/res/drawable/baseline_location_on_accent50.xml
  app/src/main/res/values-qq/strings.xml
  app/src/main/res/values/strings.xml
Labels: Ready to merge

#4956 Add is_temp field to legacy analytics, and bump schema versions.
  app/src/main/java/org/wikipedia/analytics/eventplatform/AppInteractionEvent.kt
  app/src/main/java/org/wikipedia/analytics/eventplatform/AppSessionEvent.kt
  app/src/main/java/org/wikipedia/analytics/eventplatform/BreadCrumbLogEvent.kt
  app/src/main/java/org/wikipedia/analytics/eventplatform/DailyStatsEvent.kt
  app/src/main/java/org/wikipedia/analytics/eventplatform/ImageRecommendationsEvent.kt
  app/src/main/java/org/wikipedia/analytics/eventplatform/InstallReferrerEvent.kt
  app/src/main/java/org/wikipedia/analytics/eventplatform/MobileAppsEvent.kt
  app/src/main/java/org/wikipedia/analytics/eventplatform/NotificationInteractionEvent.kt
  app/src/main/java/org/wikipedia/analytics/eventplatform/UserContributionEvent.kt
Labels: Ready to merge

#5018 Migrate top-level gradle files to KTS, and update syntax.
  build.gradle
  build.gradle.kts
  gradle/libs.versions.toml
  settings.gradle
  settings.gradle.kts
Labels: Minor, dependencies

#5022 Switch to updated (and maintained) PhotoView library.
  app/src/main/res/layout/fragment_gallery_item.xml
  gradle/libs.versions.toml
  settings.gradle.kts
Labels: Minor, dependencies

#5024 Send user_is_temp parameter in EditAttemptStep.
  app/src/main/java/org/wikipedia/analytics/eventplatform/EditAttemptStepEvent.kt
Labels: Minor

#5003 Use CoroutineWorker in ReadingListSyncAdapter
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/wikipedia/readinglist/sync/ReadingListSyncAdapter.kt
Labels: Ready to merge

#5026 Follow-up to Csrf worker updates.
  app/src/main/java/org/wikipedia/readinglist/sync/ReadingListSyncAdapter.kt
Labels: Minor

#5017 Remove dependency on WikimediaEditorTasks extension.
  app/src/main/java/org/wikipedia/dataclient/Service.kt
  app/src/main/java/org/wikipedia/dataclient/mwapi/EditorTaskCounts.kt
  app/src/main/java/org/wikipedia/dataclient/mwapi/MwQueryResult.kt
  app/src/main/java/org/wikipedia/feed/suggestededits/SuggestedEditsFeedClient.kt
  app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsTasksFragmentViewModel.kt
  app/src/main/java/org/wikipedia/usercontrib/UserContribStats.kt
Labels: Ready to merge

#5031 Add optional `formattedId` dynamic parameter to campaign URLs.
  app/src/main/java/org/wikipedia/dataclient/donate/Campaign.kt
  app/src/main/java/org/wikipedia/page/campaign/CampaignDialog.kt
  app/src/main/java/org/wikipedia/page/campaign/CampaignDialogView.kt
Labels: Minor

#4914 Temporary accounts.
  app/src/main/java/org/wikipedia/WikipediaApp.kt
  app/src/main/java/org/wikipedia/analytics/metricsplatform/MetricsEvent.kt
  app/src/main/java/org/wikipedia/auth/AccountUtil.kt
  app/src/main/java/org/wikipedia/createaccount/CreateAccountActivity.kt
  app/src/main/java/org/wikipedia/csrf/CsrfTokenClient.kt
  app/src/main/java/org/wikipedia/dataclient/Service.kt
  app/src/main/java/org/wikipedia/dataclient/mwapi/MwQueryPage.kt
  app/src/main/java/org/wikipedia/dataclient/mwapi/MwQueryResult.kt
  app/src/main/java/org/wikipedia/dataclient/restbase/EditCount.kt
  app/src/main/java/org/wikipedia/edit/EditSectionActivity.kt
  app/src/main/java/org/wikipedia/edit/EditSectionViewModel.kt
  app/src/main/java/org/wikipedia/edit/summaries/EditSummaryFragment.kt
  app/src/main/java/org/wikipedia/login/LoginActivity.kt
  app/src/main/java/org/wikipedia/navtab/MenuNavTabDialog.kt
  app/src/main/java/org/wikipedia/notifications/NotificationRepository.kt
  app/src/main/java/org/wikipedia/page/PageActivity.kt
  app/src/main/java/org/wikipedia/page/edithistory/EditHistoryItemView.kt
  app/src/main/java/org/wikipedia/page/edithistory/EditHistoryListViewModel.kt
  app/src/main/java/org/wikipedia/readinglist/ReadingListsFragment.kt
  app/src/main/java/org/wikipedia/readinglist/sync/ReadingListSyncAdapter.kt
  app/src/main/java/org/wikipedia/settings/LogoutPreference.kt
  app/src/main/java/org/wikipedia/settings/Prefs.kt
  app/src/main/java/org/wikipedia/settings/SiteInfo.kt
  app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsSnackbars.kt
  app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsTasksFragmentViewModel.kt
  app/src/main/java/org/wikipedia/talk/TalkReplyActivity.kt
  app/src/main/java/org/wikipedia/talk/TalkReplyViewModel.kt
  app/src/main/java/org/wikipedia/talk/TalkThreadItemView.kt
  app/src/main/java/org/wikipedia/talk/TalkTopicActivity.kt
  app/src/main/java/org/wikipedia/talk/TalkTopicsActivity.kt
  app/src/main/res/drawable/ic_anon_account.xml
  app/src/main/res/drawable/ic_temp_account.xml
  app/src/main/res/layout/activity_create_account.xml
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/activity_talk_reply.xml
  app/src/main/res/layout/fragment_preview_summary.xml
  app/src/main/res/layout/inflate_edit_account_footer.xml
  app/src/main/res/layout/inflate_login_and_account_creation_footer.xml
  app/src/main/res/layout/view_edit_history_filter_overflow.xml
  app/src/main/res/layout/view_main_drawer.xml
  app/src/main/res/layout/view_preference_logout.xml
  app/src/main/res/menu/menu_edit_section.xml
  app/src/main/res/values-qq/strings.xml
  app/src/main/res/values/preference_keys.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/strings_no_translate.xml
  app/src/main/res/values/styles.xml
  app/src/main/res/xml/developer_preferences.xml
Labels: Ready to merge

#5046 Revert "Fix: a possible crash about lateinit WikipediaApp instance has not en initialized"
  app/src/main/java/org/wikipedia/WikipediaApp.kt
Labels: Minor

#5045 [Contributions Dashboard] Create a donor badge view
  app/src/main/java/org/wikipedia/donate/DonorStatus.kt
  app/src/main/java/org/wikipedia/settings/Prefs.kt
  app/src/main/java/org/wikipedia/views/DonorBadgeView.kt
  app/src/main/res/drawable/ic_baseline_volunteer_activism_24.xml
  app/src/main/res/layout/view_donor_badge.xml
  app/src/main/res/values/preference_keys.xml
Labels: Ready to merge

#5047 Add a proper padding to the chip icon for smaller text for Donor badge
  app/src/main/java/org/wikipedia/views/DonorBadgeView.kt
  app/src/main/res/layout/view_donor_badge.xml
  app/src/main/res/values/styles.xml
Labels: Ready to merge

#5054 Add dialog message for donationResult preference
  app/src/main/res/xml/developer_preferences.xml
Labels: Ready to merge

#5060 Fix display of multiline usernames in TalkTopics.
  app/src/main/res/layout/item_talk_topic.xml
Labels: Minor

#5069 Follow up: survey dialog for Contributions Dashboard
  app/src/main/java/org/wikipedia/usercontrib/ContributionsDashboardHelper.kt
  app/src/main/res/values/strings_no_translate.xml
Labels: Ready to merge

#5021 [Contributions Dashboard] Donor History
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/wikipedia/dataclient/donate/CampaignCollection.kt
  app/src/main/java/org/wikipedia/donate/DonorHistoryActivity.kt
  app/src/main/java/org/wikipedia/donate/DonorHistoryViewModel.kt
  app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsTasksFragment.kt
  app/src/main/res/drawable/outline_repeat_24.xml
  app/src/main/res/drawable/outline_volunteer_activism_24.xml
  app/src/main/res/layout/activity_donor_history.xml
  app/src/main/res/layout/fragment_suggested_edits_tasks.xml
  app/src/main/res/values/strings_no_translate.xml
  app/src/main/res/values/styles.xml
Labels: Ready to merge

#5048 [Contributions Dashboard] Update contribute tab for donor history
  app/src/main/java/org/wikipedia/main/MainActivity.kt
  app/src/main/java/org/wikipedia/page/PageFragment.kt
  app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsTasksFragment.kt
  app/src/main/java/org/wikipedia/views/MessageCardView.kt
  app/src/main/java/org/wikipedia/views/SuggestedEditsStatsView.kt
  app/src/main/res/drawable/round_app_registration_24.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_suggested_edits_tasks.xml
  app/src/main/res/layout/view_donor_badge.xml
  app/src/main/res/layout/view_message_card.xml
  app/src/main/res/layout/view_suggested_edits_stats.xml
  app/src/main/res/values-sw600dp/dimens.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/styles.xml
Labels: Ready to merge

#5077 Update Donor Status logic for recurring donor option
  app/src/main/java/org/wikipedia/donate/DonorHistoryActivity.kt
  app/src/main/java/org/wikipedia/donate/DonorHistoryViewModel.kt
  app/src/main/java/org/wikipedia/donate/DonorStatus.kt
  app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsTasksFragment.kt
Labels: Ready to merge
