Repository wikimedia/apps-android-wikipedia, pull requests merged in 2024-06, with the labels that each got.

#4605 Hygiene: Remove useless constructor from Page, and improve ns detection.
  app/src/main/java/org/wikipedia/page/Page.kt
  app/src/main/java/org/wikipedia/page/PageProperties.kt
  app/src/test/java/org/wikipedia/descriptions/DescriptionEditClientTest.kt
  app/src/test/java/org/wikipedia/test/ParcelableTest.kt
Labels: Minor, Ready to merge

#4721 Hygiene: use registerForActivityResult for launching activities in SE tasks
  app/src/main/java/org/wikipedia/Constants.kt
  app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsTasksFragment.kt
  app/src/main/java/org/wikipedia/views/MessageCardView.kt
Labels: Minor

#4722 Fix tint and logic of Edit pencil in page toolbar.
  app/src/main/java/org/wikipedia/page/PageFragment.kt
Labels: Minor

#4723 Fix potential issue(s) with audio/video playback in WebView.
  app/src/main/java/org/wikipedia/dataclient/okhttp/AvailableInputStream.kt
  app/src/main/java/org/wikipedia/dataclient/okhttp/OkHttpWebViewClient.kt
  app/src/test/java/org/wikipedia/dataclient/okhttp/AvailableInputStreamTest.kt
Labels: Minor

#4724 Fix passing of userGroups to PCS when setting up.
  app/src/main/java/org/wikipedia/bridge/JavaScriptActionHandler.kt
Labels: Minor

#4727 Fix unintended parsing of language variant code from /w/ URLs.
  app/src/main/java/org/wikipedia/util/UriUtil.kt
Labels: Minor

#4730 Hygiene: Remove duplicated themed resource
  app/src/main/res/drawable/ic_share_material_secondary_themed.xml
  app/src/main/res/menu/menu_talk_thread_item.xml
Labels: Minor

#4734 Fix: remove toolbar space from first bitmap in TabsActivity
  app/src/main/java/org/wikipedia/page/PageActivity.kt
  app/src/main/java/org/wikipedia/page/tabs/TabActivity.kt
Labels: Minor

#4735 Hygiene: remove unused functions/variables and add suppress for unused paramteres
  app/src/main/java/org/wikipedia/gallery/ExtMetadata.kt
  app/src/main/java/org/wikipedia/gallery/GalleryActivity.kt
  app/src/main/java/org/wikipedia/gallery/GalleryItem.kt
  app/src/main/java/org/wikipedia/gallery/ImageInfo.kt
  app/src/main/java/org/wikipedia/gallery/ImageLicense.kt
  app/src/main/java/org/wikipedia/gallery/MediaListItem.kt
Labels: Minor

#4737 Revert "Do not reload the feed content onResume in FeedFragment"
  app/src/main/java/org/wikipedia/feed/FeedFragment.kt
Labels: Minor, High Priority

#4741 Remove unused ConfigurableTextView and update AppTextView
  app/src/main/java/org/wikipedia/views/AppTextView.kt
  app/src/main/java/org/wikipedia/views/ConfigurableTextView.kt
Labels: Minor

#4740 Move PagerTransformer to Random package
  app/src/main/java/org/wikipedia/random/PagerTransformer.kt
  app/src/main/java/org/wikipedia/random/RandomFragment.kt
  app/src/main/java/org/wikipedia/util/AnimationUtil.kt
Labels: Minor

#4742 Update list of languages and static data.
  app/src/main/java/org/wikipedia/staticdata/ContributionsNameData.kt
  app/src/main/java/org/wikipedia/staticdata/FileAliasData.kt
  app/src/main/java/org/wikipedia/staticdata/MainPageNameData.kt
  app/src/main/java/org/wikipedia/staticdata/SpecialAliasData.kt
  app/src/main/java/org/wikipedia/staticdata/TalkAliasData.kt
  app/src/main/java/org/wikipedia/staticdata/UserAliasData.kt
  app/src/main/java/org/wikipedia/staticdata/UserTalkAliasData.kt
  app/src/main/res/values/languages_list.xml
Labels: dependencies

#4744 Hygiene: reduce contructors in FrameLayoutNavMmenuTriggerer
  app/src/main/java/org/wikipedia/views/FrameLayoutNavMenuTriggerer.kt
Labels: Minor

#4747 Update gradle and dependencies.
  app/build.gradle
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
Labels: dependencies

#4716 Use Flow instead of RxJava for Bus functionality.
  app/src/main/java/org/wikipedia/WikipediaApp.kt
  app/src/main/java/org/wikipedia/activity/BaseActivity.kt
  app/src/main/java/org/wikipedia/analytics/InstallReferrerListener.kt
  app/src/main/java/org/wikipedia/concurrency/FlowEventBus.kt
  app/src/main/java/org/wikipedia/concurrency/RxBus.kt
  app/src/main/java/org/wikipedia/csrf/CsrfTokenClient.kt
  app/src/main/java/org/wikipedia/main/MainFragment.kt
  app/src/main/java/org/wikipedia/notifications/NotificationPollBroadcastReceiver.kt
  app/src/main/java/org/wikipedia/page/PageActivity.kt
  app/src/main/java/org/wikipedia/random/RandomFragment.kt
  app/src/main/java/org/wikipedia/readinglist/ReadingListFragment.kt
  app/src/main/java/org/wikipedia/readinglist/ReadingListSyncBehaviorDialogs.kt
  app/src/main/java/org/wikipedia/readinglist/ReadingListsFragment.kt
  app/src/main/java/org/wikipedia/readinglist/db/ReadingListPageDao.kt
  app/src/main/java/org/wikipedia/readinglist/sync/ReadingListSyncAdapter.kt
  app/src/main/java/org/wikipedia/savedpages/SavedPageSyncService.kt
  app/src/main/java/org/wikipedia/settings/SettingsFragment.kt
  app/src/main/java/org/wikipedia/theme/ThemeChooserDialog.kt
  app/src/main/java/org/wikipedia/theme/ThemeFittingRoomFragment.kt
  app/src/main/java/org/wikipedia/views/ObservableWebView.kt
Labels: Ready to merge

#4710 Use LiftWing service for machine-generated description suggestions.
  app/src/main/java/org/wikipedia/dataclient/liftwing/DescriptionSuggestion.kt
  app/src/main/java/org/wikipedia/dataclient/liftwing/LiftWingModelService.kt
  app/src/main/java/org/wikipedia/descriptions/DescriptionEditFragment.kt
  app/src/main/java/org/wikipedia/descriptions/DescriptionSuggestionResponse.kt
  app/src/main/java/org/wikipedia/descriptions/DescriptionSuggestionService.kt
Labels: Ready to merge

#4750 Follow up: use when() in FlowEvent conditions
  app/src/main/java/org/wikipedia/activity/BaseActivity.kt
  app/src/main/java/org/wikipedia/main/MainFragment.kt
  app/src/main/java/org/wikipedia/random/RandomFragment.kt
  app/src/main/java/org/wikipedia/readinglist/ReadingListFragment.kt
  app/src/main/java/org/wikipedia/readinglist/ReadingListsFragment.kt
  app/src/main/java/org/wikipedia/theme/ThemeChooserDialog.kt
  app/src/main/java/org/wikipedia/theme/ThemeFittingRoomFragment.kt
Labels: Minor

#4751 Use Coroutine in PageFramgent instead of RxJava
  app/src/main/java/org/wikipedia/dataclient/Service.kt
  app/src/main/java/org/wikipedia/page/PageFragment.kt
  app/src/main/java/org/wikipedia/readinglist/db/ReadingListPageDao.kt
Labels: Minor

#4748 Upgrade to Kotlin 2.
  app/build.gradle
  app/src/main/java/org/wikipedia/search/RecentSearchesFragment.kt
  build.gradle
Labels: dependencies

#4753 Refactor and simplify Edit Activity xml.
  app/src/main/java/org/wikipedia/edit/richtext/SyntaxHighlighter.kt
  app/src/main/res/layout/activity_edit_section.xml
  app/src/main/res/values/styles.xml
Labels: Minor

#4754 Potential fix(es) for incorrect sizing of fonts when editing.
  app/src/main/java/org/wikipedia/edit/SyntaxHighlightableEditText.kt
  app/src/main/java/org/wikipedia/edit/richtext/SyntaxHighlighter.kt
Labels: Minor

#4657 Migrate to MapLibre v11.
  app/build.gradle
  app/src/main/java/org/wikipedia/places/PlacesFragment.kt
  app/src/main/java/org/wikipedia/places/PlacesFragmentViewModel.kt
  app/src/main/res/layout/fragment_places.xml
Labels: dependencies, Ready to merge

#4757 Prevent possible silent errors in reading lists.
  app/src/main/java/org/wikipedia/readinglist/AddToReadingListDialog.kt
  app/src/main/java/org/wikipedia/readinglist/db/ReadingListDao.kt
Labels: Minor

#4758 Refactoring OnThisDayFragment to use coroutine and ViewModel
  app/src/main/java/org/wikipedia/dataclient/RestService.kt
  app/src/main/java/org/wikipedia/feed/onthisday/OnThisDay.kt
  app/src/main/java/org/wikipedia/feed/onthisday/OnThisDayFragment.kt
  app/src/main/java/org/wikipedia/feed/onthisday/OnThisDayViewModel.kt
  app/src/main/java/org/wikipedia/views/CustomDatePicker.kt
  app/src/main/res/layout/fragment_on_this_day.xml
Labels: Ready to merge

#4761 Fix: make sure edits in Edit Patrol are sorted by date in descending order
  app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsRecentEditsViewModel.kt
Labels: Minor
