Repository wikimedia/apps-android-wikipedia, pull requests merged in 2025-05, with the labels that each got.

#5514 Espresso Fix - Compose Support
  app/src/androidTest/java/org/wikipedia/base/BaseTest.kt
  app/src/androidTest/java/org/wikipedia/base/ComposeTestManager.kt
  app/src/androidTest/java/org/wikipedia/base/base/BaseRobot.kt
  app/src/androidTest/java/org/wikipedia/base/utils/ComposeTestExtensions.kt
  app/src/androidTest/java/org/wikipedia/robots/feature/PageRobot.kt
  app/src/androidTest/java/org/wikipedia/robots/feature/SettingsRobot.kt
  app/src/androidTest/java/org/wikipedia/robots/screen/LanguageListRobot.kt
  app/src/androidTest/java/org/wikipedia/tests/search/SearchExternalIntentTest.kt
  app/src/androidTest/java/org/wikipedia/tests/search/SearchIntentTest.kt
  app/src/androidTest/java/org/wikipedia/tests/settings/AboutSettingsTest.kt
  app/src/androidTest/java/org/wikipedia/tests/settings/ChangingLanguageTest.kt
  app/src/main/java/org/wikipedia/compose/components/SearchTopAppBar.kt
  app/src/main/java/org/wikipedia/language/addlanguages/AddLanguagesListScreen.kt
Labels: Minor

#5518 Removes duplicate BaseRobot file
  app/src/androidTest/java/org/wikipedia/base/BaseRobot.kt
  app/src/androidTest/java/org/wikipedia/base/base/BaseRobot.kt
  app/src/androidTest/java/org/wikipedia/robots/AppThemeRobot.kt
  app/src/androidTest/java/org/wikipedia/robots/DialogRobot.kt
  app/src/androidTest/java/org/wikipedia/robots/SystemRobot.kt
  app/src/androidTest/java/org/wikipedia/robots/feature/EditorRobot.kt
  app/src/androidTest/java/org/wikipedia/robots/feature/ExploreFeedRobot.kt
  app/src/androidTest/java/org/wikipedia/robots/feature/LicenseRobot.kt
  app/src/androidTest/java/org/wikipedia/robots/feature/LoginRobot.kt
  app/src/androidTest/java/org/wikipedia/robots/feature/MediaRobot.kt
  app/src/androidTest/java/org/wikipedia/robots/feature/OnboardingRobot.kt
  app/src/androidTest/java/org/wikipedia/robots/feature/PageActionItemRobot.kt
  app/src/androidTest/java/org/wikipedia/robots/feature/PageRobot.kt
  app/src/androidTest/java/org/wikipedia/robots/feature/ReadingListRobot.kt
  app/src/androidTest/java/org/wikipedia/robots/feature/SearchRobot.kt
  app/src/androidTest/java/org/wikipedia/robots/feature/SettingsRobot.kt
  app/src/androidTest/java/org/wikipedia/robots/feature/TabsRobot.kt
  app/src/androidTest/java/org/wikipedia/robots/navigation/BottomNavRobot.kt
  app/src/androidTest/java/org/wikipedia/robots/screen/HomeScreenRobot.kt
  app/src/androidTest/java/org/wikipedia/robots/screen/LanguageListRobot.kt
  app/src/androidTest/java/org/wikipedia/robots/screen/NotificationScreenRobot.kt
  app/src/androidTest/java/org/wikipedia/robots/screen/SavedScreenRobot.kt
  app/src/androidTest/java/org/wikipedia/robots/screen/SuggestedEditsScreenRobot.kt
Labels: Minor

#5473 Create a viewModel, API calls and DB queries - T390643
  app/src/main/java/org/wikipedia/dataclient/Service.kt
  app/src/main/java/org/wikipedia/history/db/HistoryEntryDao.kt
  app/src/main/java/org/wikipedia/yearinreview/YearInReviewActivity.kt
  app/src/main/java/org/wikipedia/yearinreview/YearInReviewScaffold.kt
  app/src/main/java/org/wikipedia/yearinreview/YearInReviewScreenData.kt
  app/src/main/java/org/wikipedia/yearinreview/YearInReviewViewModel.kt
  app/src/main/res/drawable/wyir_puzzle_2_v5.gif
  app/src/main/res/drawable/wyir_puzzle_3.gif
  app/src/main/res/values-qq/strings.xml
  app/src/main/res/values/strings.xml
Labels: Ready for Review

#5520 Follow-up: viewModel for YearInReview
  app/src/main/java/org/wikipedia/yearinreview/YearInReviewActivity.kt
  app/src/main/java/org/wikipedia/yearinreview/YearInReviewScreenData.kt
  app/src/main/java/org/wikipedia/yearinreview/YearInReviewViewModel.kt
Labels: Minor

#5501 Dev playground locally track categories
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/wikipedia/categories/db/CategoryDao.kt
  app/src/main/java/org/wikipedia/settings/SettingsFragment.kt
  app/src/main/java/org/wikipedia/settings/dev/DeveloperSettingsActivity.kt
  app/src/main/java/org/wikipedia/settings/dev/DeveloperSettingsFragment.kt
  app/src/main/java/org/wikipedia/settings/dev/DeveloperSettingsPreferenceLoader.kt
  app/src/main/java/org/wikipedia/settings/dev/playground/CategoryDeveloperPlayGround.kt
  app/src/main/java/org/wikipedia/settings/dev/playground/CategoryDeveloperPlayGroundViewModel.kt
  app/src/main/res/values/preference_keys.xml
  app/src/main/res/xml/developer_preferences.xml
Labels: Minor, Experimental

#5526 Follow up: Category dev playground
  app/src/main/java/org/wikipedia/settings/dev/playground/CategoryDeveloperPlayGroundActivity.kt
  app/src/main/java/org/wikipedia/settings/dev/playground/CategoryDeveloperPlayGroundViewModel.kt
Labels: Minor

#5528 Allow receiving callbacks for days clicked in MaterialDatePicker.
  app/src/main/java/org/wikipedia/games/onthisday/OnThisDayGameOnboardingFragment.kt
Labels: Minor

#5510 WikiGames: Database table for the game history
  app/schemas/org.wikipedia.database.AppDatabase/29.json
  app/src/main/java/org/wikipedia/database/AppDatabase.kt
  app/src/main/java/org/wikipedia/games/WikiGames.kt
  app/src/main/java/org/wikipedia/games/db/DailyGameHistory.kt
  app/src/main/java/org/wikipedia/games/db/DailyGameHistoryDao.kt
  app/src/main/java/org/wikipedia/games/onthisday/OnThisDayGameFinalFragment.kt
  app/src/main/java/org/wikipedia/games/onthisday/OnThisDayGameViewModel.kt
  app/src/main/java/org/wikipedia/settings/Prefs.kt
  app/src/main/res/values/preference_keys.xml
  app/src/main/res/xml/developer_preferences.xml
Labels: Ready to merge

#5489 locally track categories
  app/schemas/org.wikipedia.database.AppDatabase/29.json
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/wikipedia/categories/db/Category.kt
  app/src/main/java/org/wikipedia/categories/db/CategoryDao.kt
  app/src/main/java/org/wikipedia/database/AppDatabase.kt
  app/src/main/java/org/wikipedia/dataclient/Service.kt
  app/src/main/java/org/wikipedia/dataclient/mwapi/MwQueryPage.kt
  app/src/main/java/org/wikipedia/extensions/Long.kt
  app/src/main/java/org/wikipedia/games/WikiGames.kt
  app/src/main/java/org/wikipedia/games/db/DailyGameHistory.kt
  app/src/main/java/org/wikipedia/games/db/DailyGameHistoryDao.kt
  app/src/main/java/org/wikipedia/games/onthisday/OnThisDayGameFinalFragment.kt
  app/src/main/java/org/wikipedia/games/onthisday/OnThisDayGameViewModel.kt
  app/src/main/java/org/wikipedia/history/HistoryViewModel.kt
  app/src/main/java/org/wikipedia/page/PageFragmentLoadState.kt
  app/src/main/java/org/wikipedia/recurring/CategoriesTableCleanupTask.kt
  app/src/main/java/org/wikipedia/recurring/RecurringTask.kt
  app/src/main/java/org/wikipedia/recurring/RecurringTasksExecutor.kt
  app/src/main/java/org/wikipedia/settings/Prefs.kt
  app/src/main/java/org/wikipedia/settings/SettingsFragment.kt
  app/src/main/java/org/wikipedia/settings/dev/DeveloperSettingsActivity.kt
  app/src/main/java/org/wikipedia/settings/dev/DeveloperSettingsFragment.kt
  app/src/main/java/org/wikipedia/settings/dev/DeveloperSettingsPreferenceLoader.kt
  app/src/main/java/org/wikipedia/settings/dev/playground/CategoryDeveloperPlayGroundActivity.kt
  app/src/main/java/org/wikipedia/settings/dev/playground/CategoryDeveloperPlayGroundViewModel.kt
  app/src/main/java/org/wikipedia/util/DateUtil.kt
  app/src/main/res/values/preference_keys.xml
  app/src/main/res/xml/developer_preferences.xml
Labels: Ready to merge

#5522 Strings for WikiGames archive calendar
  app/src/main/res/values-qq/strings.xml
  app/src/main/res/values/strings.xml
Labels: Minor

#5529 Follow-up 1: some light cleanup of Category db table.
  app/src/androidTest/java/org/wikipedia/database/UpgradeFromPreRoomTest.kt
  app/src/main/java/org/wikipedia/categories/db/CategoryDao.kt
  app/src/main/java/org/wikipedia/dataclient/mwapi/MwQueryPage.kt
  app/src/main/java/org/wikipedia/extensions/Long.kt
  app/src/main/java/org/wikipedia/games/onthisday/OnThisDayGameViewModel.kt
  app/src/main/java/org/wikipedia/page/PageFragmentLoadState.kt
  app/src/main/java/org/wikipedia/recurring/CategoriesTableCleanupTask.kt
  app/src/main/java/org/wikipedia/settings/dev/playground/CategoryDeveloperPlayGroundActivity.kt
  app/src/main/java/org/wikipedia/settings/dev/playground/CategoryDeveloperPlayGroundViewModel.kt
  app/src/main/java/org/wikipedia/util/DateUtil.kt
  app/src/main/res/values/preference_keys.xml
Labels: Minor

#5531 Simplify and code clean up for ReadingList screen
  app/src/main/java/org/wikipedia/readinglist/AddToReadingListDialog.kt
  app/src/main/java/org/wikipedia/readinglist/ReadingListActivity.kt
  app/src/main/java/org/wikipedia/readinglist/ReadingListFragment.kt
  app/src/main/java/org/wikipedia/readinglist/ReadingListItemView.kt
Labels: Minor

#5497 WikiGames: enhanced sharing of game results
  app/src/main/java/org/wikipedia/games/onthisday/OnThisDayGameFinalFragment.kt
  app/src/main/java/org/wikipedia/games/onthisday/OnThisDayGameViewModel.kt
  app/src/main/res/layout/fragment_on_this_day_game_final.xml
  app/src/main/res/layout/item_on_this_day_game_share_topic.xml
  app/src/main/res/layout/view_on_this_day_game_share.xml
  app/src/main/res/values-qq/strings.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
Labels: Ready to merge

#5534 Fix: remove old dots after regenerating new screenshot for WikiGames
  app/src/main/java/org/wikipedia/games/onthisday/OnThisDayGameFinalFragment.kt
Labels: Minor

#5535 Follow-up 2 to sharing game screenshot.
  app/src/main/java/org/wikipedia/games/onthisday/OnThisDayGameFinalFragment.kt
Labels: Minor

#5530 Follow-up 2: Fetch categories along with Watched status when possible.
  app/src/main/java/org/wikipedia/dataclient/Service.kt
  app/src/main/java/org/wikipedia/page/PageFragmentLoadState.kt
Labels: Minor

#5506 WikiGames: Updated Score view design with new info icon
  app/src/main/java/org/wikipedia/games/onthisday/OnThisDayGameActivity.kt
  app/src/main/java/org/wikipedia/games/onthisday/ScoreView.kt
  app/src/main/res/layout/activity_on_this_day_game.xml
Labels: Ready to merge

#5532 Discover pre-work: change the icons location in the readinglist header item view
  app/src/main/res/layout/item_reading_list.xml
Labels: Minor, Ready to merge

#5536 strings for archive game
  app/src/main/res/values-qq/strings.xml
  app/src/main/res/values/strings.xml
Labels: Minor

#5542 Update languages for Game availability and release dates.
  app/src/main/java/org/wikipedia/games/onthisday/OnThisDayGameNotificationManager.kt
  app/src/main/java/org/wikipedia/games/onthisday/OnThisDayGameOnboardingFragment.kt
  app/src/main/java/org/wikipedia/games/onthisday/OnThisDayGameViewModel.kt
Labels: Minor

#5545 Make temp account status detection more explicit.
  app/src/main/java/org/wikipedia/auth/AccountUtil.kt
Labels: Minor, High Priority

#5550 updates strings for wikigames
  app/src/main/res/values-qq/strings.xml
  app/src/main/res/values/strings.xml
Labels: Minor

#5549 Fix: crash when adding articles from one reading list to another
  app/src/main/java/org/wikipedia/readinglist/ReadingListFragment.kt
Labels: Minor, High Priority

#5546 Wikigames sound menu option
  app/src/main/java/org/wikipedia/games/onthisday/OnThisDayGameActivity.kt
  app/src/main/java/org/wikipedia/games/onthisday/OnThisDayGameOnboardingFragment.kt
  app/src/main/java/org/wikipedia/settings/Prefs.kt
  app/src/main/res/drawable/volume_off_24dp.xml
  app/src/main/res/drawable/volume_up_24dp.xml
  app/src/main/res/layout/activity_on_this_day_game.xml
  app/src/main/res/menu/menu_on_this_day_game.xml
  app/src/main/res/values-qq/strings.xml
  app/src/main/res/values/preference_keys.xml
  app/src/main/res/values/strings.xml
Labels: Ready to merge

#5543 Hygiene: reading list code clean up and updates
  app/src/main/java/org/wikipedia/readinglist/AddToReadingListDialog.kt
  app/src/main/java/org/wikipedia/readinglist/LongPressMenu.kt
  app/src/main/java/org/wikipedia/readinglist/ReadingListBehaviorsUtil.kt
  app/src/main/java/org/wikipedia/readinglist/ReadingListFragment.kt
  app/src/main/java/org/wikipedia/readinglist/ReadingListHeaderView.kt
  app/src/main/java/org/wikipedia/readinglist/ReadingListItemView.kt
  app/src/main/java/org/wikipedia/readinglist/ReadingListPreviewSaveDialogView.kt
  app/src/main/java/org/wikipedia/readinglist/ReadingListTitleDialog.kt
  app/src/main/java/org/wikipedia/readinglist/ReadingListsFragment.kt
Labels: Minor

#5551 Further solidify detection of temp account name.
  app/src/main/java/org/wikipedia/auth/AccountUtil.kt
  app/src/test/java/org/wikipedia/util/AccountUtilTest.kt
Labels: Minor, High Priority

#5552 Add a `isPreBetaRelease` condition for the release date for WikiGames
  app/src/main/java/org/wikipedia/games/onthisday/OnThisDayGameViewModel.kt
Labels: Minor

#5544 Wikigames archive calendar
  app/src/main/java/org/wikipedia/games/onthisday/DateDecorator.kt
  app/src/main/java/org/wikipedia/games/onthisday/OnThisDayGameActivity.kt
  app/src/main/java/org/wikipedia/games/onthisday/OnThisDayGameOnboardingFragment.kt
  app/src/main/java/org/wikipedia/games/onthisday/OnThisDayGameViewModel.kt
  app/src/main/java/org/wikipedia/settings/Prefs.kt
  app/src/main/java/org/wikipedia/util/DateUtil.kt
  app/src/main/res/drawable/volume_off_24dp.xml
  app/src/main/res/drawable/volume_up_24dp.xml
  app/src/main/res/layout/activity_on_this_day_game.xml
  app/src/main/res/layout/fragment_on_this_day_game_onboarding.xml
  app/src/main/res/menu/menu_on_this_day_game.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/preference_keys.xml
  app/src/main/res/values/styles.xml
Labels: Design review, Ready for Review

#5537 Integrate DonateDialog class into YiR donate button - T393815
  app/src/main/java/org/wikipedia/yearinreview/YearInReviewActivity.kt
  app/src/main/java/org/wikipedia/yearinreview/YearInReviewScaffold.kt
Labels: Ready for Review

#5538 Strings for Recommended Reading list feature
  app/src/main/res/values-qq/strings.xml
  app/src/main/res/values/strings.xml
Labels: Minor, Ready to merge

#5554 Simplify and streamline game archive logic.
  app/src/main/java/org/wikipedia/games/onthisday/DateDecorator.kt
  app/src/main/java/org/wikipedia/games/onthisday/OnThisDayGameActivity.kt
  app/src/main/java/org/wikipedia/games/onthisday/OnThisDayGameOnboardingFragment.kt
  app/src/main/java/org/wikipedia/games/onthisday/OnThisDayGameViewModel.kt
  app/src/main/java/org/wikipedia/settings/Prefs.kt
  app/src/main/res/values/preference_keys.xml
Labels: High Priority

#5558 Update Game analytics to account for archived games.
  app/src/main/java/org/wikipedia/analytics/eventplatform/WikiGamesEvent.kt
  app/src/main/java/org/wikipedia/games/onthisday/OnThisDayGameActivity.kt
  app/src/main/java/org/wikipedia/games/onthisday/OnThisDayGameArticleBottomSheet.kt
  app/src/main/java/org/wikipedia/games/onthisday/OnThisDayGameFinalFragment.kt
  app/src/main/java/org/wikipedia/games/onthisday/OnThisDayGameOnboardingFragment.kt
  app/src/main/java/org/wikipedia/games/onthisday/OnThisDayGameViewModel.kt
Labels: High Priority

#5562 Fix: make sure to compare the correct value for updating the list in ReadingListsFragment
  app/src/main/java/org/wikipedia/readinglist/database/ReadingList.kt
Labels: Minor

#5563 Follow-up to final game Archive updates.
  app/src/main/java/org/wikipedia/games/onthisday/OnThisDayGameBaseFragment.kt
  app/src/main/java/org/wikipedia/games/onthisday/OnThisDayGameFinalFragment.kt
  app/src/main/java/org/wikipedia/games/onthisday/OnThisDayGameOnboardingFragment.kt
Labels: High Priority

#5565 minor string update
  app/src/main/res/values/strings.xml
Labels: Ready to merge

#5571 Fix minor potential crash in Final game screen.
  app/src/main/java/org/wikipedia/games/onthisday/OnThisDayGameFinalFragment.kt
Labels: High Priority

#5574 Add optional "New" dot over navigation tabs.
  app/src/main/java/org/wikipedia/navtab/NavTabLayout.kt
  app/src/main/res/values/ids.xml
Labels: Ready to merge

#5578 Discover settings missing strings
  app/src/main/res/values-qq/strings.xml
  app/src/main/res/values/strings.xml
Labels: Minor, Ready to merge

#5450 Implement Coil image loading library
  app/build.gradle
  app/proguard-rules.pro
  app/src/androidTest/java/org/wikipedia/base/utils/GifMatchers.kt
  app/src/main/java/org/wikipedia/WikipediaApp.kt
  app/src/main/java/org/wikipedia/commons/FilePageFragment.kt
  app/src/main/java/org/wikipedia/dataclient/okhttp/OkHttpGlideModule.kt
  app/src/main/java/org/wikipedia/edit/insertmedia/InsertMediaActivity.kt
  app/src/main/java/org/wikipedia/extensions/Bitmap.kt
  app/src/main/java/org/wikipedia/feed/view/CardLargeHeaderView.kt
  app/src/main/java/org/wikipedia/gallery/GalleryItemFragment.kt
  app/src/main/java/org/wikipedia/gallery/ImagePipelineBitmapGetter.kt
  app/src/main/java/org/wikipedia/games/onthisday/OnThisDayGameFinalFragment.kt
  app/src/main/java/org/wikipedia/main/MainFragment.kt
  app/src/main/java/org/wikipedia/places/PlacesFragment.kt
  app/src/main/java/org/wikipedia/richtext/CustomHtmlParser.kt
  app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsImageRecsFragment.kt
  app/src/main/java/org/wikipedia/util/CenterCropWithFaceTransformation.kt
  app/src/main/java/org/wikipedia/util/WhiteBackgroundTransformation.kt
  app/src/main/java/org/wikipedia/views/FaceAndColorDetectImageView.kt
  app/src/main/java/org/wikipedia/views/ViewUtil.kt
  app/src/main/java/org/wikipedia/views/imageservice/CenterCropWithFaceTransformation.kt
  app/src/main/java/org/wikipedia/views/imageservice/CoilImageServiceLoader.kt
  app/src/main/java/org/wikipedia/views/imageservice/ImageService.kt
  app/src/main/java/org/wikipedia/views/imageservice/ImageTransformer.kt
  app/src/main/java/org/wikipedia/views/imageservice/WhiteBackgroundTransformation.kt
  app/src/main/java/org/wikipedia/widgets/WidgetProviderFeaturedPage.kt
  app/src/main/res/layout/widget_featured_page.xml
  gradle/libs.versions.toml
Labels: Ready to merge

#5541 Add basic instrumentation to YiR screens - T392406
  app/src/main/java/org/wikipedia/yearinreview/YearInReviewActivity.kt
  app/src/main/java/org/wikipedia/yearinreview/YearInReviewScaffold.kt
Labels: Ready for Review

#5583 Create onboarding message card for Recommended Reading list
  app/src/main/java/org/wikipedia/readinglist/ReadingListsFragment.kt
  app/src/main/java/org/wikipedia/settings/Prefs.kt
  app/src/main/java/org/wikipedia/views/MessageCardView.kt
  app/src/main/res/layout/view_message_card.xml
  app/src/main/res/values/preference_keys.xml
  app/src/main/res/values/styles.xml
  app/src/main/res/xml/developer_preferences.xml
Labels: Ready to merge

#5587 Fix sequential parameters in new strings, and add tests.
  app/src/main/res/values-mk/strings.xml
  app/src/main/res/values-qq/strings.xml
  app/src/main/res/values/strings.xml
  app/src/test/java/org/wikipedia/language/TranslationTests.kt
Labels: Minor, High Priority

#5570 Create recurring task for Recommended Reading list
  app/src/main/java/org/wikipedia/dataclient/Service.kt
  app/src/main/java/org/wikipedia/history/db/HistoryEntryDao.kt
  app/src/main/java/org/wikipedia/readinglist/db/ReadingListPageDao.kt
  app/src/main/java/org/wikipedia/readinglist/db/RecommendedPageDao.kt
  app/src/main/java/org/wikipedia/readinglist/recommended/RecommendedReadingListViewModel.kt
  app/src/main/java/org/wikipedia/recurring/RecommendedReadingListTask.kt
  app/src/main/java/org/wikipedia/recurring/RecurringTasksExecutor.kt
  app/src/main/java/org/wikipedia/settings/Prefs.kt
  app/src/main/res/values/preference_keys.xml
Labels: Ready to merge

#5589 Follow-up to recurring task.
  app/src/main/java/org/wikipedia/recurring/RecommendedReadingListTask.kt
Labels: Minor

#5575 Follow-up to Coil, and increase default thumbnail size in lists, etc.
  app/src/main/java/org/wikipedia/captcha/CaptchaHandler.kt
  app/src/main/java/org/wikipedia/commons/FilePageFragment.kt
  app/src/main/java/org/wikipedia/commons/FilePageView.kt
  app/src/main/java/org/wikipedia/edit/insertmedia/InsertMediaActivity.kt
  app/src/main/java/org/wikipedia/edit/insertmedia/InsertMediaSettingsFragment.kt
  app/src/main/java/org/wikipedia/extensions/Bitmap.kt
  app/src/main/java/org/wikipedia/feed/view/CardLargeHeaderView.kt
  app/src/main/java/org/wikipedia/feed/view/ListCardItemView.kt
  app/src/main/java/org/wikipedia/gallery/GalleryItemFragment.kt
  app/src/main/java/org/wikipedia/games/onthisday/OnThisDayGameFinalFragment.kt
  app/src/main/java/org/wikipedia/main/MainFragment.kt
  app/src/main/java/org/wikipedia/places/PlacesFragment.kt
  app/src/main/java/org/wikipedia/readinglist/ReadingListFragment.kt
  app/src/main/java/org/wikipedia/readinglist/ReadingListPreviewSaveDialogView.kt
  app/src/main/java/org/wikipedia/readinglist/ReadingListsFragment.kt
  app/src/main/java/org/wikipedia/richtext/CustomHtmlParser.kt
  app/src/main/java/org/wikipedia/search/SearchResultsFragment.kt
  app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsImageRecsFragment.kt
  app/src/main/java/org/wikipedia/theme/ThemeFittingRoomFragment.kt
  app/src/main/java/org/wikipedia/views/FaceAndColorDetectImageView.kt
  app/src/main/java/org/wikipedia/views/PageItemView.kt
  app/src/main/java/org/wikipedia/views/ViewUtil.kt
  app/src/main/java/org/wikipedia/views/imageservice/CoilImageServiceLoader.kt
  app/src/main/java/org/wikipedia/views/imageservice/DimImageTransformation.kt
  app/src/main/java/org/wikipedia/views/imageservice/FaceDetectTransformation.kt
  app/src/main/java/org/wikipedia/views/imageservice/ImageService.kt
  app/src/main/java/org/wikipedia/views/imageservice/WhiteBackgroundTransformation.kt
  app/src/main/java/org/wikipedia/widgets/WidgetProviderFeaturedPage.kt
  app/src/main/res/drawable/button_shape_gray.xml
  app/src/main/res/layout/dialog_add_to_reading_list.xml
  app/src/main/res/layout/dialog_link_preview.xml
  app/src/main/res/layout/fragment_insert_media_settings.xml
  app/src/main/res/layout/fragment_theme_fitting_room.xml
  app/src/main/res/layout/item_insert_media.xml
  app/src/main/res/layout/item_on_this_day_game_share_topic.xml
  app/src/main/res/layout/item_page_list_entry.xml
  app/src/main/res/layout/item_reading_list.xml
  app/src/main/res/layout/item_reading_list_preview_save_select_item.xml
  app/src/main/res/layout/item_search_result.xml
  app/src/main/res/layout/view_horizontal_scroll_list_item_card.xml
  app/src/main/res/layout/view_list_card_item.xml
  app/src/main/res/layout/view_page_header.xml
  app/src/main/res/layout/view_wiki_article_card.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/styles.xml
Labels: Ready to merge

#5481 Breadcrumbs in Compose.
  app/src/main/java/org/wikipedia/analytics/eventplatform/BreadCrumbLogEvent.kt
  app/src/main/java/org/wikipedia/compose/components/SearchTopAppBar.kt
  app/src/main/java/org/wikipedia/compose/components/WikiTopAppBar.kt
  app/src/main/java/org/wikipedia/compose/components/error/ComposeWikiErrorView.kt
  app/src/main/java/org/wikipedia/language/addlanguages/AddLanguagesListScreen.kt
  app/src/main/java/org/wikipedia/wiktionary/WiktionaryDialogScreen.kt
Labels: Ready to merge

#5597 Simplify detection of Dark theme in WikiCard composable.
  app/src/main/java/org/wikipedia/compose/components/WikiCard.kt
  app/src/main/java/org/wikipedia/compose/theme/WikipediaColor.kt
Labels: Minor

#5598 Provide a default ripple effect for all Composables.
  app/src/main/java/org/wikipedia/compose/components/WikiCard.kt
  app/src/main/java/org/wikipedia/compose/theme/WikipediaTheme.kt
  app/src/main/java/org/wikipedia/language/LangLinksScreen.kt
  app/src/main/java/org/wikipedia/language/addlanguages/AddLanguagesListScreen.kt
Labels: Minor

#5595 Update the logic of showing onboarding card for Recommended reading list
  app/src/main/java/org/wikipedia/readinglist/ReadingListsFragment.kt
Labels: Ready to merge

#5594 Delete categories in batches
  app/src/main/java/org/wikipedia/categories/db/CategoryDao.kt
  app/src/main/java/org/wikipedia/recurring/CategoriesTableCleanupTask.kt
  app/src/main/java/org/wikipedia/settings/dev/playground/CategoryDeveloperPlayGroundViewModel.kt
Labels: Minor

#5602 Follow-up: Discover settings for Recommended reading list
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/wikipedia/compose/components/WikipediaAlertDialog.kt
  app/src/main/java/org/wikipedia/readinglist/recommended/RecommendedReadingListOnboardingActivity.kt
  app/src/main/java/org/wikipedia/readinglist/recommended/RecommendedReadingListOptions.kt
  app/src/main/java/org/wikipedia/readinglist/recommended/RecommendedReadingListSettingsActivity.kt
  app/src/main/java/org/wikipedia/readinglist/recommended/RecommendedReadingListSettingsScreen.kt
  app/src/main/java/org/wikipedia/readinglist/recommended/RecommendedReadingListSettingsViewModel.kt
  app/src/main/java/org/wikipedia/readinglist/recommended/RecommendedReadingListSourceFragment.kt
  app/src/main/java/org/wikipedia/settings/SettingsPreferenceLoader.kt
  app/src/main/res/values/preference_keys.xml
  app/src/main/res/xml/preferences.xml
Labels: Minor, Ready to merge

#5603 Minor follow up RRL
  app/src/main/java/org/wikipedia/readinglist/recommended/RecommendedReadingListSettingsActivity.kt
  app/src/main/java/org/wikipedia/readinglist/recommended/RecommendedReadingListSettingsScreen.kt
Labels: Minor, Ready to merge
