Repository wikimedia/apps-android-wikipedia, pull requests merged in 2025-01, with the labels that each got.

#5191 Compose Library Implementation
  app/build.gradle
  build.gradle.kts
  gradle/libs.versions.toml
Labels: Ready to merge

#5186 Espresso Deep Linking Test
  app/src/androidTest/java/org/wikipedia/base/BaseTest.kt
  app/src/androidTest/java/org/wikipedia/robots/feature/PageRobot.kt
  app/src/androidTest/java/org/wikipedia/tests/DeepLinkingTest.kt
  app/src/androidTest/java/org/wikipedia/testsuites/TestSuite.kt
Labels: Ready to merge

#5202 Fix/remove unnecessary parameter during page->gallery transition.
  app/src/main/java/org/wikipedia/bridge/JavaScriptActionHandler.kt
  app/src/main/java/org/wikipedia/gallery/GalleryActivity.kt
  app/src/main/java/org/wikipedia/page/leadimages/LeadImagesHandler.kt
  app/src/main/java/org/wikipedia/page/linkpreview/LinkPreviewDialog.kt
Labels: Minor

#5203 Fix potential issues due to duplicate Result codes in SearchActivity.
  app/src/main/java/org/wikipedia/search/SearchActivity.kt
  app/src/main/java/org/wikipedia/search/SearchFragment.kt
Labels: Minor, High Priority

#5197 Bug - Animated images stop animating after viewing the image
  app/src/main/java/org/wikipedia/page/PageFragment.kt
  app/src/main/java/org/wikipedia/util/ImageUrlUtil.kt
  app/src/test/java/org/wikipedia/util/ImageUrlUtilTest.kt
Labels: Ready to merge

#5205 Fix issues with Snackbar action after completing SE Feed items.
  app/src/main/java/org/wikipedia/feed/suggestededits/SuggestedEditsCardItemFragment.kt
  app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsSnackbars.kt
Labels: Minor, High Priority

#5207 Use local language names instead of canonical names where appropriate.
  app/src/main/java/org/wikipedia/feed/suggestededits/SuggestedEditsCardItemFragment.kt
  app/src/main/java/org/wikipedia/language/LangLinksActivity.kt
  app/src/main/java/org/wikipedia/notifications/NotificationFilterItemView.kt
  app/src/main/java/org/wikipedia/places/PlacesFilterActivity.kt
  app/src/main/java/org/wikipedia/settings/languages/WikipediaLanguagesFragment.kt
  app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsRecentEditsFilterItemView.kt
  app/src/main/java/org/wikipedia/views/LanguageScrollView.kt
  app/src/main/java/org/wikipedia/watchlist/WatchlistFilterItemView.kt
Labels: Minor

#5192 Cleanup Contribution Dashboard
  app/src/androidTest/java/org/wikipedia/robots/navigation/BottomNavRobot.kt
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/wikipedia/LauncherController.kt
  app/src/main/java/org/wikipedia/activity/BaseActivity.kt
  app/src/main/java/org/wikipedia/analytics/eventplatform/ContributionsDashboardEvent.kt
  app/src/main/java/org/wikipedia/dataclient/donate/CampaignCollection.kt
  app/src/main/java/org/wikipedia/donate/DonorHistoryActivity.kt
  app/src/main/java/org/wikipedia/donate/DonorHistoryViewModel.kt
  app/src/main/java/org/wikipedia/donate/DonorStatus.kt
  app/src/main/java/org/wikipedia/main/MainActivity.kt
  app/src/main/java/org/wikipedia/navtab/MenuNavTabDialog.kt
  app/src/main/java/org/wikipedia/navtab/NavTab.kt
  app/src/main/java/org/wikipedia/page/PageFragment.kt
  app/src/main/java/org/wikipedia/page/action/PageActionItem.kt
  app/src/main/java/org/wikipedia/page/campaign/CampaignDialog.kt
  app/src/main/java/org/wikipedia/settings/AppIconDialog.kt
  app/src/main/java/org/wikipedia/settings/Prefs.kt
  app/src/main/java/org/wikipedia/settings/SettingsActivity.kt
  app/src/main/java/org/wikipedia/settings/SettingsFragment.kt
  app/src/main/java/org/wikipedia/settings/SettingsPreferenceLoader.kt
  app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsTasksFragment.kt
  app/src/main/java/org/wikipedia/usercontrib/ContributionsDashboardHelper.kt
  app/src/main/java/org/wikipedia/views/DonorBadgeView.kt
  app/src/main/java/org/wikipedia/views/PageActionOverflowView.kt
  app/src/main/res/drawable/ic_launcher_donor_benefit_foreground.xml
  app/src/main/res/layout/activity_donor_history.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/dialog_app_icon.xml
  app/src/main/res/layout/fragment_suggested_edits_tasks.xml
  app/src/main/res/layout/view_donor_badge.xml
  app/src/main/res/layout/view_page_action_overflow.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher_donor_benefit.xml
  app/src/main/res/mipmap-hdpi/ic_launcher_donor_benefit.webp
  app/src/main/res/mipmap-mdpi/ic_launcher_donor_benefit.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher_donor_benefit.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher_donor_benefit.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_donor_benefit.webp
  app/src/main/res/values-qq/strings.xml
  app/src/main/res/values/preference_keys.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/xml/developer_preferences.xml
  app/src/main/res/xml/preferences.xml
Labels: Ready to merge

#5209 Update Edits sequential tooltips's target and orders
  app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsTasksFragment.kt
  app/src/main/java/org/wikipedia/views/SuggestedEditsStatsView.kt
Labels: Minor

#5210 Do not block the Edits screen if the primary language is `test`
  app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsTasksFragment.kt
Labels: Minor

#5211 Follow up: show localized name in the Contributions filter screen
  app/src/main/java/org/wikipedia/language/AppLanguageState.kt
Labels: Minor

#5213 Simplify: remove old way of making circular images.
  app/src/main/java/org/wikipedia/feed/places/PlacesCardView.kt
  app/src/main/java/org/wikipedia/places/PlacesFragment.kt
  app/src/main/java/org/wikipedia/views/ViewUtil.kt
  app/src/main/res/layout/item_places_list.xml
  app/src/main/res/layout/view_places_card.xml
Labels: Minor

#5212 Separates XML layout of SuggestedEditsTasksFragment
  app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsTasksFragment.kt
  app/src/main/res/layout/fragment_suggested_edits_tasks.xml
  app/src/main/res/layout/suggested_edits_tasks_container.xml
  app/src/main/res/layout/suggested_edits_tasks_contribution_container.xml
Labels: Minor

#5206 Cleanup from Rabbit Holes
  app/src/main/java/org/wikipedia/Constants.kt
  app/src/main/java/org/wikipedia/analytics/eventplatform/RabbitHolesEvent.kt
  app/src/main/java/org/wikipedia/analytics/metricsplatform/RabbitHolesABCTest.kt
  app/src/main/java/org/wikipedia/analytics/metricsplatform/RabbitHolesAnalyticsHelper.kt
  app/src/main/java/org/wikipedia/history/HistoryEntry.kt
  app/src/main/java/org/wikipedia/history/db/HistoryEntryDao.kt
  app/src/main/java/org/wikipedia/page/PageActivity.kt
  app/src/main/java/org/wikipedia/readinglist/ReadingListActivity.kt
  app/src/main/java/org/wikipedia/readinglist/ReadingListFragment.kt
  app/src/main/java/org/wikipedia/readinglist/ReadingListItemView.kt
  app/src/main/java/org/wikipedia/readinglist/ReadingListPreviewSaveDialogView.kt
  app/src/main/java/org/wikipedia/readinglist/ReadingListsFragment.kt
  app/src/main/java/org/wikipedia/search/RecentSearchesFragment.kt
  app/src/main/java/org/wikipedia/search/SearchActivity.kt
  app/src/main/java/org/wikipedia/search/SearchFragment.kt
  app/src/main/java/org/wikipedia/settings/Prefs.kt
  app/src/main/java/org/wikipedia/views/CabSearchView.kt
  app/src/main/java/org/wikipedia/views/SurveyDialog.kt
  app/src/main/res/drawable/experiment_chip_background.xml
  app/src/main/res/drawable/shape_suggested_search_term.xml
  app/src/main/res/layout/item_reading_list.xml
  app/src/main/res/values-qq/strings.xml
  app/src/main/res/values/preference_keys.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/strings_no_translate.xml
  app/src/main/res/xml/developer_preferences.xml
Labels: Ready to merge

#5218 Expresso code fixes
  app/src/androidTest/java/org/wikipedia/robots/SystemRobot.kt
  app/src/androidTest/java/org/wikipedia/robots/feature/ReadingListRobot.kt
  app/src/androidTest/java/org/wikipedia/robots/feature/SearchRobot.kt
  app/src/androidTest/java/org/wikipedia/robots/screen/SuggestedEditsScreenRobot.kt
  app/src/androidTest/java/org/wikipedia/tests/DeepLinkingTest.kt
  app/src/androidTest/java/org/wikipedia/tests/SuggestedEditScreenTest.kt
  app/src/androidTest/java/org/wikipedia/tests/settings/ChangingLanguageTest.kt
  app/src/androidTest/java/org/wikipedia/tests/settings/CollapseTablesTest.kt
  app/src/androidTest/java/org/wikipedia/tests/settings/DownloadReadingListTest.kt
  app/src/androidTest/java/org/wikipedia/tests/settings/LinkPreviewTest.kt
  app/src/androidTest/java/org/wikipedia/tests/settings/ReadingFocusModeTest.kt
Labels: Ready to merge

#5142 Espresso search test
  app/src/androidTest/java/org/wikipedia/base/BaseRobot.kt
  app/src/androidTest/java/org/wikipedia/base/BaseTest.kt
  app/src/androidTest/java/org/wikipedia/robots/feature/SearchRobot.kt
  app/src/androidTest/java/org/wikipedia/robots/screen/HistoryScreenRobot.kt
  app/src/androidTest/java/org/wikipedia/tests/SearchTest.kt
  app/src/androidTest/java/org/wikipedia/testsuites/TestSuite.kt
Labels: Ready to merge

#5198 Compose Convert the base color styles
  app/src/main/java/org/wikipedia/compose/WikipediaColor.kt
  app/src/main/java/org/wikipedia/compose/WikipediaTheme.kt
  app/src/main/java/org/wikipedia/theme/ThemeColors.kt
Labels: Ready to merge

#5223 Follow-up to zh variant fixes.
  app/src/main/java/org/wikipedia/WikipediaApp.kt
  app/src/main/java/org/wikipedia/dataclient/okhttp/OkHttpWebViewClient.kt
  app/src/main/java/org/wikipedia/language/AcceptLanguageUtil.kt
  app/src/main/java/org/wikipedia/savedpages/SavedPageSyncService.kt
  app/src/test/java/org/wikipedia/language/LanguageVariantTest.kt
Labels: Minor

#5224 Hygiene: remove unnecessary string function.
  app/src/main/java/org/wikipedia/commons/FilePageView.kt
  app/src/main/java/org/wikipedia/descriptions/DescriptionEditView.kt
  app/src/main/java/org/wikipedia/gallery/GalleryActivity.kt
  app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsCardsItemFragment.kt
  app/src/main/java/org/wikipedia/util/StringUtil.kt
  app/src/test/java/org/wikipedia/util/StringUtilTest.kt
Labels: Minor

#5227 Follow-up to offline state tracking.
  app/src/main/java/org/wikipedia/connectivity/ConnectionStateMonitor.kt
Labels: Minor

#5231 Espresso article test fix
  app/src/androidTest/java/org/wikipedia/testsuites/ArticlesTestSuite.kt
Labels: Minor

#5239 Streamline calls to PageSummary and MediaList.
  app/src/main/java/org/wikipedia/dataclient/RestService.kt
  app/src/main/java/org/wikipedia/descriptions/DescriptionEditViewModel.kt
  app/src/main/java/org/wikipedia/edit/EditSectionViewModel.kt
  app/src/main/java/org/wikipedia/page/PageFragmentLoadState.kt
  app/src/main/java/org/wikipedia/savedpages/SavedPageSyncService.kt
  app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsImageRecsFragmentViewModel.kt
  app/src/main/java/org/wikipedia/suggestededits/provider/EditingSuggestionsProvider.kt
  app/src/main/java/org/wikipedia/util/L10nUtil.kt
  app/src/main/java/org/wikipedia/widgets/WidgetFeaturedPageWorker.kt
Labels: Minor

#5238 Fix a couple of issues when invoking Gallery from Suggested Edits.
  app/src/main/java/org/wikipedia/dataclient/RestService.kt
  app/src/main/java/org/wikipedia/descriptions/DescriptionEditViewModel.kt
  app/src/main/java/org/wikipedia/edit/EditSectionViewModel.kt
  app/src/main/java/org/wikipedia/feed/suggestededits/SuggestedEditsCardItemFragment.kt
  app/src/main/java/org/wikipedia/gallery/GalleryActivity.kt
  app/src/main/java/org/wikipedia/gallery/GalleryViewModel.kt
  app/src/main/java/org/wikipedia/page/PageActivity.kt
  app/src/main/java/org/wikipedia/page/PageFragmentLoadState.kt
  app/src/main/java/org/wikipedia/page/linkpreview/LinkPreviewDialog.kt
  app/src/main/java/org/wikipedia/page/linkpreview/LinkPreviewViewModel.kt
  app/src/main/java/org/wikipedia/savedpages/SavedPageSyncService.kt
  app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsImageRecsFragmentViewModel.kt
  app/src/main/java/org/wikipedia/suggestededits/provider/EditingSuggestionsProvider.kt
  app/src/main/java/org/wikipedia/util/L10nUtil.kt
  app/src/main/java/org/wikipedia/widgets/WidgetFeaturedPageWorker.kt
Labels: Minor, High Priority

#5226 Convert XML styles to Compose
  app/src/main/java/org/wikipedia/compose/components/WikiButtons.kt
  app/src/main/java/org/wikipedia/compose/components/WikiSnackbar.kt
  app/src/main/java/org/wikipedia/compose/components/WikiTopAppBar.kt
  app/src/main/java/org/wikipedia/compose/theme/WikipediaTheme.kt
  app/src/main/java/org/wikipedia/compose/theme/WikipediaTypography.kt
  app/src/main/res/values/styles.xml
Labels: Ready to merge

#5240 Add `pilicense=any` for prop=pageimages API calls
  app/src/main/java/org/wikipedia/dataclient/Service.kt
Labels: Minor

#5241 Image recs on dewiki: restrict to CC-licensed images.
  app/src/main/java/org/wikipedia/suggestededits/provider/EditingSuggestionsProvider.kt
Labels: Minor

#5242 Compose state
  app/src/main/java/org/wikipedia/compose/components/WikiButtons.kt
Labels: Ready to merge

#5254 Prevent possible crash due to post-ing on a View.
  app/src/main/java/org/wikipedia/feed/announcement/AnnouncementCardView.kt
Labels: Minor, High Priority

#5256 [WikiGames] Strings for entry dialog
  app/src/main/res/values-qq/strings.xml
  app/src/main/res/values/strings.xml
Labels: Ready to merge

#5257 WikiGames: strings for main gameplay.
  app/src/main/res/values-qq/strings.xml
  app/src/main/res/values/strings.xml
Labels: Ready to merge

#5252 [WikiGames] entry dialog
  app/src/main/java/org/wikipedia/activity/BaseActivity.kt
  app/src/main/java/org/wikipedia/feed/FeedFragment.kt
  app/src/main/java/org/wikipedia/games/onthisday/OnThisDayGameViewModel.kt
  app/src/main/java/org/wikipedia/page/PageFragment.kt
  app/src/main/java/org/wikipedia/settings/Prefs.kt
  app/src/main/res/layout/dialog_on_this_day_game.xml
  app/src/main/res/values/preference_keys.xml
  app/src/main/res/xml/developer_preferences.xml
Labels: Ready to merge

#5258 [Wikigames] feed entry strings
  app/src/main/res/values-qq/strings.xml
  app/src/main/res/values/strings.xml
Labels: Ready to merge

#5260 Follow-up: move developer settings search into toolbar.
  app/src/main/java/org/wikipedia/settings/DeveloperSettingsFragment.kt
  app/src/main/java/org/wikipedia/settings/DeveloperSettingsPreferenceLoader.kt
  app/src/main/res/menu/menu_developer_settings.xml
  app/src/main/res/values/dev_settings_strings.xml
  app/src/main/res/values/preference_keys.xml
  app/src/main/res/xml/developer_preferences.xml
Labels: Minor

#5262 Minor update for the wiki game final screen string
  app/src/main/res/values/strings.xml
Labels: Minor

#5263 Remove outdated mentions of `page/related` endpoint.
  app/src/main/java/org/wikipedia/dataclient/ServiceFactory.kt
  app/src/main/java/org/wikipedia/feed/becauseyouread/BecauseYouReadClient.kt
Labels: Minor

#5264 Periodic update of static language data.
  app/src/main/java/org/wikipedia/staticdata/ContributionsNameData.kt
  app/src/main/java/org/wikipedia/staticdata/FileAliasData.kt
  app/src/main/java/org/wikipedia/staticdata/MainPageNameData.kt
  app/src/main/java/org/wikipedia/staticdata/SpecialAliasData.kt
  app/src/main/java/org/wikipedia/staticdata/TalkAliasData.kt
  app/src/main/java/org/wikipedia/staticdata/UserAliasData.kt
  app/src/main/java/org/wikipedia/staticdata/UserTalkAliasData.kt
  app/src/main/res/values/languages_list.xml
  scripts/generate_wiki_languages.py
Labels: Minor

#5267 Add strings for Wikigame final screen
  app/src/main/res/values-qq/strings.xml
  app/src/main/res/values/strings.xml
Labels: Minor

#5261 [Wikigames] game entry card
  app/src/main/java/org/wikipedia/feed/FeedContentType.kt
  app/src/main/java/org/wikipedia/feed/configure/ConfigureViewModel.kt
  app/src/main/java/org/wikipedia/feed/model/CardType.kt
  app/src/main/java/org/wikipedia/feed/wikigames/WikiGamesCard.kt
  app/src/main/java/org/wikipedia/feed/wikigames/WikiGamesCardClient.kt
  app/src/main/java/org/wikipedia/feed/wikigames/WikiGamesCardView.kt
  app/src/main/res/drawable/ic_wiki_games_events.xml
  app/src/main/res/layout/view_wiki_games_card.xml
Labels: Ready to merge

#5270 Add strings for wikigame final screen bottom sheet
  app/src/main/res/values-qq/strings.xml
  app/src/main/res/values/strings.xml
Labels: Minor

#5273 Update strings for the wikigame final screen
  app/src/main/res/values-qq/strings.xml
  app/src/main/res/values/strings.xml
Labels: Minor

#5275 Remove unused Contributions Dashboard url
  app/src/main/res/values/strings_no_translate.xml
Labels: Minor

#5274 Update strings for wiki game final result screen
  app/src/main/res/values-qq/strings.xml
  app/src/main/res/values/strings.xml
Labels: Minor

#5277 [Wikigames] Updated strings for notification
  app/src/main/res/values-qq/strings.xml
  app/src/main/res/values/strings.xml
Labels: Minor

#5251 Show warning if edited article description exceeds 90 chars.
  app/src/main/java/org/wikipedia/descriptions/DescriptionEditView.kt
  app/src/main/res/values-qq/strings.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
Labels: Ready to merge

#5279 [WIkigames] notification string update
  app/src/main/res/values-qq/strings.xml
  app/src/main/res/values/strings.xml
Labels: Minor

#5255 WikiGames: the final result screen
  app/src/main/java/org/wikipedia/games/onthisday/OnThisDayGameActivity.kt
  app/src/main/java/org/wikipedia/games/onthisday/OnThisDayGameFinalFragment.kt
  app/src/main/java/org/wikipedia/games/onthisday/WeeklyActivityView.kt
  app/src/main/res/drawable/baseline_info_24.xml
  app/src/main/res/drawable/outline_notification_add_24.xml
  app/src/main/res/layout/activity_on_this_day_game.xml
  app/src/main/res/layout/fragment_on_this_day_game_final.xml
  app/src/main/res/layout/item_on_this_day_game_topic.xml
  app/src/main/res/layout/view_game_weekly_activity.xml
  app/src/main/res/menu/menu_on_this_day_game.xml
  app/src/main/res/values/strings_no_translate.xml
  app/src/main/res/values/styles.xml
Labels: Ready to merge

#5283 [WikiGames] strings for Pause dialog.
  app/src/main/res/values-qq/strings.xml
  app/src/main/res/values/strings.xml
Labels: Minor
