Repository wikimedia/apps-android-wikipedia, pull requests merged in 2025-06, with the labels that each got.

#5610 Default RRL notification Preference should be false
  app/src/main/java/org/wikipedia/settings/Prefs.kt
Labels: Minor, Ready to merge

#5611 Make text in the About screen highlightable and copyable.
  app/src/main/java/org/wikipedia/settings/AboutActivity.kt
Labels: Minor

#5613 Follow-up to Coil: expose getRequest() for use in AsyncImage.
  app/src/main/java/org/wikipedia/views/imageservice/CoilImageServiceLoader.kt
  app/src/main/java/org/wikipedia/views/imageservice/ImageService.kt
Labels: Minor

#5609 Design follow up
  app/src/main/java/org/wikipedia/readinglist/recommended/RecommendedReadingListSettingsScreen.kt
  app/src/main/res/values/strings.xml
Labels: Ready to merge

#5581 Notification Recommended reading list
  app/src/main/java/org/wikipedia/notifications/NotificationPollBroadcastReceiver.kt
  app/src/main/java/org/wikipedia/notifications/NotificationPresenter.kt
  app/src/main/java/org/wikipedia/readinglist/recommended/RecommendedReadingListSettingsActivity.kt
  app/src/main/java/org/wikipedia/settings/RecommendedReadingListNotificationManager.kt
  app/src/main/java/org/wikipedia/settings/dev/DeveloperSettingsPreferenceLoader.kt
  app/src/main/res/values/preference_keys.xml
  app/src/main/res/xml/developer_preferences.xml
Labels: Ready to merge

#5626 Fix tinting of menu items in Talk topics.
  app/src/main/java/org/wikipedia/talk/TalkThreadItemView.kt
Labels: Minor, High Priority

#5596 Create Discover page for the Recommended Reading list
  app/src/main/java/org/wikipedia/page/PageActivity.kt
  app/src/main/java/org/wikipedia/page/PageAvailableOfflineHandler.kt
  app/src/main/java/org/wikipedia/readinglist/ReadingListActivity.kt
  app/src/main/java/org/wikipedia/readinglist/ReadingListFragment.kt
  app/src/main/java/org/wikipedia/readinglist/ReadingListFragmentViewModel.kt
  app/src/main/java/org/wikipedia/readinglist/ReadingListItemView.kt
  app/src/main/java/org/wikipedia/readinglist/ReadingListMode.kt
  app/src/main/java/org/wikipedia/readinglist/ReadingListPreviewSaveDialogView.kt
  app/src/main/java/org/wikipedia/readinglist/ReadingListsFragment.kt
  app/src/main/java/org/wikipedia/readinglist/db/RecommendedPageDao.kt
  app/src/main/java/org/wikipedia/readinglist/recommended/RecommendedReadingListHelper.kt
  app/src/main/java/org/wikipedia/readinglist/recommended/RecommendedReadingListSettingsActivity.kt
  app/src/main/java/org/wikipedia/readinglist/recommended/RecommendedReadingListSourceFragment.kt
  app/src/main/java/org/wikipedia/readinglist/recommended/RecommendedReadingListViewModel.kt
  app/src/main/java/org/wikipedia/recurring/RecommendedReadingListTask.kt
  app/src/main/java/org/wikipedia/settings/Prefs.kt
  app/src/main/java/org/wikipedia/settings/RecommendedReadingListNotificationManager.kt
  app/src/main/java/org/wikipedia/views/PageItemView.kt
  app/src/main/res/layout/fragment_reading_list.xml
  app/src/main/res/layout/item_reading_list.xml
  app/src/main/res/menu/menu_recommended_reading_list_item.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/strings_no_translate.xml
Labels: Ready to merge

#5627 Follow-up: the interests screen for Recommended reading list
  app/src/main/java/org/wikipedia/readinglist/recommended/RecommendedReadingListInterestsFragment.kt
Labels: Minor

#5629 Source Screen backHandler
  app/src/main/java/org/wikipedia/readinglist/recommended/RecommendedReadingListSourceScreen.kt
Labels: Minor

#5631 Show a confirm dialog when adjust source from settings
  app/src/main/java/org/wikipedia/readinglist/recommended/RecommendedReadingListSourceFragment.kt
  app/src/main/java/org/wikipedia/readinglist/recommended/RecommendedReadingListViewModel.kt
Labels: Minor

#5632 Optimize the way of re-generating new list from Settings
  app/src/main/java/org/wikipedia/readinglist/ReadingListFragment.kt
  app/src/main/java/org/wikipedia/readinglist/ReadingListFragmentViewModel.kt
  app/src/main/java/org/wikipedia/readinglist/db/RecommendedPageDao.kt
  app/src/main/java/org/wikipedia/readinglist/recommended/RecommendedReadingListHelper.kt
  app/src/main/java/org/wikipedia/readinglist/recommended/RecommendedReadingListSettingsActivity.kt
  app/src/main/java/org/wikipedia/readinglist/recommended/RecommendedReadingListSettingsViewModel.kt
  app/src/main/java/org/wikipedia/recurring/RecommendedReadingListTask.kt
  app/src/main/java/org/wikipedia/settings/Prefs.kt
  app/src/main/res/values/preference_keys.xml
Labels: High Priority, Ready to merge

#5630 Instrumentation for the Recommended reading list
  app/src/main/java/org/wikipedia/analytics/eventplatform/RecommendedReadingListEvent.kt
  app/src/main/java/org/wikipedia/history/HistoryEntry.kt
  app/src/main/java/org/wikipedia/readinglist/ReadingListFragment.kt
  app/src/main/java/org/wikipedia/readinglist/ReadingListItemView.kt
  app/src/main/java/org/wikipedia/readinglist/ReadingListSyncBehaviorDialogs.kt
  app/src/main/java/org/wikipedia/readinglist/ReadingListsFragment.kt
  app/src/main/java/org/wikipedia/readinglist/recommended/RecommendedReadingListInterestsFragment.kt
  app/src/main/java/org/wikipedia/readinglist/recommended/RecommendedReadingListInterestsViewModel.kt
  app/src/main/java/org/wikipedia/readinglist/recommended/RecommendedReadingListOptions.kt
  app/src/main/java/org/wikipedia/readinglist/recommended/RecommendedReadingListSettingsActivity.kt
  app/src/main/java/org/wikipedia/readinglist/recommended/RecommendedReadingListSettingsScreen.kt
  app/src/main/java/org/wikipedia/readinglist/recommended/RecommendedReadingListSourceFragment.kt
  app/src/main/java/org/wikipedia/readinglist/recommended/RecommendedReadingListSourceScreen.kt
  app/src/main/java/org/wikipedia/readinglist/recommended/RecommendedReadingListSourceViewModel.kt
  app/src/main/java/org/wikipedia/settings/SettingsPreferenceLoader.kt
Labels: Ready to merge

#5633 Use text instead of prefixedText for generating RRL
  app/src/main/java/org/wikipedia/readinglist/recommended/RecommendedReadingListHelper.kt
Labels: Ready to merge

#5636 Design tweaks for Interests selection screen.
  app/src/main/java/org/wikipedia/readinglist/recommended/RecommendedReadingListInterestsFragment.kt
  app/src/main/java/org/wikipedia/readinglist/recommended/RecommendedReadingListInterestsViewModel.kt
Labels: Minor, High Priority

#5638 Bold full user name
  app/src/main/java/org/wikipedia/readinglist/ReadingListsFragment.kt
  app/src/main/java/org/wikipedia/readinglist/RecommendedReadingListDiscoverCardView.kt
Labels: Ready to merge

#5640 Reading List whole screen scrollable
  app/src/main/java/org/wikipedia/readinglist/RecommendedReadingListDiscoverCardView.kt
  app/src/main/res/layout/fragment_reading_lists.xml
Labels: High Priority, Ready to merge

#5615 Expose Year in Review in the developer settings - T394547
  app/src/main/java/org/wikipedia/navtab/MenuNavTabDialog.kt
  app/src/main/java/org/wikipedia/settings/Prefs.kt
  app/src/main/res/layout/view_main_drawer.xml
  app/src/main/res/values/preference_keys.xml
  app/src/main/res/xml/developer_preferences.xml
Labels: Ready for Review

#5614 Add additional pages to YiR screen deck - T396044
  app/src/main/java/org/wikipedia/yearinreview/YearInReviewActivity.kt
  app/src/main/java/org/wikipedia/yearinreview/YearInReviewScaffold.kt
  app/src/main/java/org/wikipedia/yearinreview/YearInReviewScreenData.kt
  app/src/main/java/org/wikipedia/yearinreview/YearInReviewViewModel.kt
  app/src/main/res/drawable/english_slide_01_and_non_english_slide_05.png
  app/src/main/res/drawable/english_slide_05.png
  app/src/main/res/drawable/globe.xml
  app/src/main/res/drawable/ic_wikipedia_b.xml
  app/src/main/res/drawable/non_english_slide_01.png
  app/src/main/res/drawable/personal_slide_00.png
  app/src/main/res/drawable/personal_slide_01.png
  app/src/main/res/values-qq/strings.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/strings_no_translate.xml
Labels: Ready for Review

#5641 Optimize the algorithm of generating recommendations
  app/src/main/java/org/wikipedia/readinglist/db/RecommendedPageDao.kt
  app/src/main/java/org/wikipedia/readinglist/recommended/RecommendedReadingListHelper.kt
Labels: Minor, High Priority

#5645 Fix: notifications and error logic handling
  app/src/main/java/org/wikipedia/notifications/NotificationPollBroadcastReceiver.kt
  app/src/main/java/org/wikipedia/readinglist/ReadingListActivity.kt
  app/src/main/java/org/wikipedia/readinglist/ReadingListFragment.kt
  app/src/main/java/org/wikipedia/readinglist/recommended/RecommendedReadingListHelper.kt
  app/src/main/java/org/wikipedia/readinglist/recommended/RecommendedReadingListNotificationManager.kt
  app/src/main/java/org/wikipedia/settings/dev/DeveloperSettingsPreferenceLoader.kt
Labels: Minor, High Priority

#5642 Follow-up: dev settings for YiR
  app/src/main/java/org/wikipedia/navtab/MenuNavTabDialog.kt
  app/src/main/res/xml/developer_preferences.xml
Labels: Minor

#5647 Rip out ABC test for the Game.
  app/src/main/java/org/wikipedia/feed/wikigames/WikiGamesCardClient.kt
  app/src/main/java/org/wikipedia/games/onthisday/OnThisDayGameABCTest.kt
  app/src/main/java/org/wikipedia/games/onthisday/OnThisDayGameOnboardingFragment.kt
  app/src/main/java/org/wikipedia/recurring/DailyEventTask.kt
  app/src/main/res/xml/developer_preferences.xml
Labels: Minor, High Priority

#5650 Refresh screen
  app/src/main/java/org/wikipedia/readinglist/ReadingListFragment.kt
  app/src/main/java/org/wikipedia/readinglist/ReadingListsFragment.kt
  app/src/main/java/org/wikipedia/readinglist/recommended/RecommendedReadingListHelper.kt
  app/src/main/java/org/wikipedia/readinglist/recommended/RecommendedReadingListSettingsViewModel.kt
Labels: Ready to merge

#5521 Create and integrate a functionality for the YiR share icon entry point - T393224
  app/src/main/java/org/wikipedia/yearinreview/YearInReviewActivity.kt
  app/src/main/java/org/wikipedia/yearinreview/YearInReviewScaffold.kt
Labels: Ready for Review

#5655 Fix StackOverflow when pressing Back from Interests selection.
  app/src/main/java/org/wikipedia/readinglist/recommended/RecommendedReadingListInterestsFragment.kt
Labels: Minor, High Priority

#5661 Fix: remove the inccorect value for RRL event
  app/src/main/java/org/wikipedia/recurring/DailyEventTask.kt
Labels: Minor, High Priority

#5667 Use correct help URL for Short Descriptions in enwiki.
  app/src/main/java/org/wikipedia/descriptions/DescriptionEditView.kt
  app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsCardsFragment.kt
  app/src/main/res/values/strings_no_translate.xml
Labels: Minor

#5669 Add background color to the reading lists recyclerview
  app/src/main/res/layout/fragment_reading_lists.xml
Labels: Minor

#5672 Yir survey dialog follow up
  app/src/main/java/org/wikipedia/yearinreview/YearInReviewActivity.kt
  app/src/main/java/org/wikipedia/yearinreview/YearInReviewScaffold.kt
  app/src/main/java/org/wikipedia/yearinreview/YearInReviewViewModel.kt
Labels: Minor

#5676 Adjust the A/B test logic from PreBetaRelease to DevRelease for Recommended Reading List
  app/src/main/java/org/wikipedia/readinglist/recommended/RecommendedReadingListAbTest.kt
Labels: Minor, High Priority

#5685 Follow-up to Material typography.
  app/src/main/java/org/wikipedia/compose/components/LicenseLinkText.kt
  app/src/main/java/org/wikipedia/compose/components/WikiButtons.kt
  app/src/main/java/org/wikipedia/compose/components/WikiCard.kt
  app/src/main/java/org/wikipedia/compose/components/WikiSnackbar.kt
  app/src/main/java/org/wikipedia/readinglist/recommended/RecommendedReadingListInterestsFragment.kt
  app/src/main/java/org/wikipedia/settings/AboutActivity.kt
Labels: Minor

#5695 Fix: should use hard-coded text for the event in RRL
  app/src/main/java/org/wikipedia/readinglist/recommended/RecommendedReadingListSettingsActivity.kt
Labels: Minor, High Priority

#5701 Suggested task edits espresso test fix
  app/src/androidTest/java/org/wikipedia/base/actions/ListActions.kt
  app/src/androidTest/java/org/wikipedia/robots/screen/SuggestedEditsScreenRobot.kt
  app/src/androidTest/java/org/wikipedia/tests/SuggestedEditScreenTest.kt
Labels: Minor, Ready to merge

#5692 Add support for captcha when logging in.
  app/src/main/java/org/wikipedia/captcha/CaptchaHandler.kt
  app/src/main/java/org/wikipedia/dataclient/Service.kt
  app/src/main/java/org/wikipedia/login/LoginActivity.kt
  app/src/main/java/org/wikipedia/login/LoginClient.kt
  app/src/main/java/org/wikipedia/login/ResetPasswordActivity.kt
  app/src/main/res/layout/activity_create_account.xml
  app/src/main/res/layout/activity_edit_section.xml
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/group_captcha.xml
  app/src/main/res/layout/view_description_edit.xml
  app/src/main/res/values-qq/strings.xml
  app/src/main/res/values/strings.xml
Labels: Ready to merge

#5713 Fix coroutine cancellation handling in SavedPageSyncService.
  app/src/main/java/org/wikipedia/savedpages/SavedPageSyncService.kt
Labels: Minor, High Priority

#5716 Fix (temporarily) brute-force syncing of reading lists.
  app/src/main/java/org/wikipedia/readinglist/ReadingListsFragment.kt
  app/src/main/java/org/wikipedia/readinglist/sync/ReadingListSyncAdapter.kt
Labels: Minor, High Priority

#5710 Espresso Fixes and optimize FeedScreen test
  app/src/androidTest/java/org/wikipedia/base/BaseTest.kt
  app/src/androidTest/java/org/wikipedia/base/utils/GifMatchers.kt
  app/src/androidTest/java/org/wikipedia/robots/feature/ExploreFeedRobot.kt
  app/src/androidTest/java/org/wikipedia/robots/feature/LoginRobot.kt
  app/src/androidTest/java/org/wikipedia/tests/SearchTest.kt
  app/src/androidTest/java/org/wikipedia/tests/articles/TableOfContentsTest.kt
  app/src/androidTest/java/org/wikipedia/tests/explorefeed/FeedScreenSearchTest.kt
  app/src/androidTest/java/org/wikipedia/tests/explorefeed/FeedScreenSuggestedEditTest.kt
  app/src/androidTest/java/org/wikipedia/tests/explorefeed/FeedScreenTest.kt
  app/src/androidTest/java/org/wikipedia/tests/settings/CustomizeExploreFeedTest.kt
Labels: Minor

#5726 Update AppDatabase class to clean up IDE warnings and todo stuff
  app/src/main/java/org/wikipedia/database/AppDatabase.kt
Labels: Minor

#5727 Fix: Send the correct value for INTENT_EXTRA_GO_TO_MAIN_TAB in RRL
  app/src/main/java/org/wikipedia/readinglist/ReadingListActivity.kt
Labels: Minor

#5729 Fix: correctly update the red dot after generating a new list
  app/src/main/java/org/wikipedia/readinglist/ReadingListFragment.kt
Labels: Minor
