Repository wikimedia/apps-android-wikipedia, pull requests merged in 2025-03, with the labels that each got.

#5341 Fix: sned the proper WikiSite for the snackbar error messages when posting description
  app/src/main/java/org/wikipedia/descriptions/DescriptionEditFragment.kt
Labels: Minor

#5335 Fix: talk page title does not display properly when topic is missing
  app/src/main/java/org/wikipedia/talk/TalkTopicsActivity.kt
Labels: Minor

#5360 Wikigames: add a language check for the wikigames entry dialog in articles screen
  app/src/main/java/org/wikipedia/games/onthisday/OnThisDayGameOnboardingFragment.kt
  app/src/main/java/org/wikipedia/page/PageFragment.kt
Labels: Minor

#5369 Follow-up 2: Keep Game dialog language logic a bit more self-contained.
  app/src/main/java/org/wikipedia/feed/FeedFragment.kt
  app/src/main/java/org/wikipedia/games/onthisday/OnThisDayGameOnboardingFragment.kt
  app/src/main/java/org/wikipedia/page/PageFragment.kt
Labels: Minor

#5367 Follow-up 1: loading state for Game ViewModel.
  app/src/main/java/org/wikipedia/games/onthisday/OnThisDayGameViewModel.kt
Labels: Minor

#5366 Possibly (?) resolve obscure lateinit UninitializedProperty crashes.
  app/src/main/java/org/wikipedia/activity/BaseActivity.kt
  app/src/main/java/org/wikipedia/activity/SingleFragmentActivity.kt
  app/src/main/java/org/wikipedia/main/MainActivity.kt
  app/src/main/java/org/wikipedia/notifications/NotificationPollBroadcastReceiver.kt
  app/src/main/java/org/wikipedia/page/PageActivity.kt
  app/src/main/java/org/wikipedia/util/DeviceUtil.kt
Labels: Minor

#5344 Espresso fixes
  app/src/androidTest/java/org/wikipedia/base/BaseTest.kt
  app/src/androidTest/java/org/wikipedia/base/actions/ListActions.kt
  app/src/androidTest/java/org/wikipedia/robots/feature/ExploreFeedRobot.kt
  app/src/androidTest/java/org/wikipedia/robots/feature/LoginRobot.kt
  app/src/androidTest/java/org/wikipedia/robots/feature/ReadingListRobot.kt
  app/src/androidTest/java/org/wikipedia/tests/SearchTest.kt
  app/src/androidTest/java/org/wikipedia/tests/SuggestedEditScreenTest.kt
  app/src/androidTest/java/org/wikipedia/tests/articles/ArticlePageActionItemTest.kt
  app/src/androidTest/java/org/wikipedia/tests/articles/ArticleSectionsTest.kt
  app/src/androidTest/java/org/wikipedia/tests/articles/LeadNonLeadImageAndPreviewLinkTest.kt
  app/src/androidTest/java/org/wikipedia/tests/settings/DownloadReadingListTest.kt
  app/src/androidTest/java/org/wikipedia/tests/settings/ShowImageTest.kt
  app/src/androidTest/java/org/wikipedia/testsuites/SettingsTestSuite.kt
Labels: Ready to merge

#5343 [espresso] More menu
  app/src/androidTest/java/org/wikipedia/robots/SystemRobot.kt
  app/src/androidTest/java/org/wikipedia/robots/feature/MoreMenuRobot.kt
  app/src/androidTest/java/org/wikipedia/robots/feature/SettingsRobot.kt
  app/src/androidTest/java/org/wikipedia/tests/explorefeed/MoreMenuTest.kt
Labels: Ready to merge

#5376 compose base theme fix
  app/src/main/java/org/wikipedia/compose/theme/WikipediaTheme.kt
Labels: Ready to merge

#5378 Disable Delete button when only Default reading list selected.
  app/src/main/java/org/wikipedia/readinglist/ReadingListsFragment.kt
Labels: Minor

#5386 Fix: do not show empty definitions in the WiktionaryDialog
  app/src/main/java/org/wikipedia/wiktionary/WiktionaryDialog.kt
Labels: Minor

#5246 Compose About Activity conversion
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/wikipedia/compose/components/HtmlText.kt
  app/src/main/java/org/wikipedia/compose/components/LicenseLinkText.kt
  app/src/main/java/org/wikipedia/compose/components/WikiSnackbar.kt
  app/src/main/java/org/wikipedia/compose/components/WikiTopAppBar.kt
  app/src/main/java/org/wikipedia/compose/theme/WikipediaTheme.kt
  app/src/main/java/org/wikipedia/compose/theme/WikipediaTypography.kt
  app/src/main/java/org/wikipedia/settings/AboutActivity.kt
  app/src/main/java/org/wikipedia/settings/LicenseActivity.kt
  app/src/main/res/layout/activity_about.xml
  app/src/main/res/layout/activity_license.xml
Labels: Ready to merge

#5393 Periodic update of languages and static data.
  app/src/main/java/org/wikipedia/staticdata/ContributionsNameData.kt
  app/src/main/java/org/wikipedia/staticdata/FileAliasData.kt
  app/src/main/java/org/wikipedia/staticdata/MainPageNameData.kt
  app/src/main/java/org/wikipedia/staticdata/SpecialAliasData.kt
  app/src/main/java/org/wikipedia/staticdata/TalkAliasData.kt
  app/src/main/java/org/wikipedia/staticdata/UserAliasData.kt
  app/src/main/java/org/wikipedia/staticdata/UserTalkAliasData.kt
  app/src/main/res/values/languages_list.xml
Labels: Minor

#5397 For Compose HtmlText, use our custom html TagHandler.
  app/src/main/java/org/wikipedia/compose/components/HtmlText.kt
  app/src/main/java/org/wikipedia/compose/extensions/Html.kt
  app/src/main/java/org/wikipedia/richtext/CustomHtmlParser.kt
Labels: Minor

#5395 Fix previews in some Compose components.
  app/src/main/java/org/wikipedia/compose/components/WikiButtons.kt
  app/src/main/java/org/wikipedia/compose/extensions/Modifier.kt
  app/src/main/java/org/wikipedia/settings/AboutActivity.kt
Labels: Minor

#5400 Add linkInteractionListener to the HtmlText method
  app/src/main/java/org/wikipedia/compose/components/HtmlText.kt
Labels: Minor

#5396 Make Compose Snackbar support Html, too.
  app/src/main/java/org/wikipedia/compose/components/HtmlText.kt
  app/src/main/java/org/wikipedia/compose/components/WikiSnackbar.kt
  app/src/main/java/org/wikipedia/settings/AboutActivity.kt
Labels: Minor

#5391 Prepare HistoryEntry and PageImage tables for updates.
  app/schemas/org.wikipedia.database.AppDatabase/27.json
  app/src/androidTest/java/org/wikipedia/database/UpgradeFromPreRoomTest.kt
  app/src/main/java/org/wikipedia/database/AppDatabase.kt
  app/src/main/java/org/wikipedia/history/HistoryEntry.kt
  app/src/main/java/org/wikipedia/history/db/HistoryEntryDao.kt
  app/src/main/java/org/wikipedia/history/db/HistoryEntryWithImage.kt
  app/src/main/java/org/wikipedia/history/db/HistoryEntryWithImageDao.kt
  app/src/main/java/org/wikipedia/page/PageFragment.kt
  app/src/main/java/org/wikipedia/page/PageFragmentLoadState.kt
  app/src/main/java/org/wikipedia/pageimages/db/PageImage.kt
  app/src/main/java/org/wikipedia/pageimages/db/PageImageDao.kt
  app/src/main/java/org/wikipedia/savedpages/SavedPageSyncService.kt
  app/src/test/java/org/wikipedia/history/HistoryEntryTest.kt
  app/src/test/java/org/wikipedia/test/ParcelableTest.kt
Labels: Ready to merge

#5399 History Screen filter logic update
  app/src/main/java/org/wikipedia/history/HistoryFragment.kt
  app/src/main/java/org/wikipedia/history/HistoryViewModel.kt
  app/src/main/java/org/wikipedia/history/db/HistoryEntryWithImageDao.kt
Labels: Ready to merge

#5388 Refactor and simplify Watchlist messages.
  app/src/main/java/org/wikipedia/dataclient/Service.kt
  app/src/main/java/org/wikipedia/diff/ArticleEditDetailsFragment.kt
  app/src/main/java/org/wikipedia/diff/ArticleEditDetailsViewModel.kt
  app/src/main/java/org/wikipedia/page/PageFragment.kt
  app/src/main/java/org/wikipedia/page/linkpreview/LinkPreviewDialog.kt
  app/src/main/java/org/wikipedia/page/linkpreview/LinkPreviewViewModel.kt
  app/src/main/java/org/wikipedia/page/linkpreview/LinkPreviewViewState.kt
  app/src/main/java/org/wikipedia/talk/TalkTopicsActivity.kt
  app/src/main/java/org/wikipedia/talk/TalkTopicsViewModel.kt
  app/src/main/java/org/wikipedia/watchlist/WatchlistExpiryDialog.kt
  app/src/main/java/org/wikipedia/watchlist/WatchlistExpiryDialogViewModel.kt
  app/src/main/java/org/wikipedia/watchlist/WatchlistViewModel.kt
  app/src/main/res/values-qq/strings.xml
  app/src/main/res/values/strings.xml
Labels: Ready to merge

#5403 accessibility text for clear icon
  app/src/main/res/values-qq/strings.xml
  app/src/main/res/values/strings.xml
Labels: Minor, Ready to merge

#5407 Correctly calculate size of initial revision of an article.
  app/src/main/java/org/wikipedia/page/edithistory/EditHistoryListViewModel.kt
Labels: Minor

#5410 Fix: remove timeSpentSec variable in the toHistoryEntry method
  app/src/main/java/org/wikipedia/history/db/HistoryEntryWithImageDao.kt
Labels: Minor, High Priority

#5404 Locally track rabbit holes for YiR
  app/src/main/java/org/wikipedia/Constants.kt
  app/src/main/java/org/wikipedia/LongPressHandler.kt
  app/src/main/java/org/wikipedia/history/HistoryEntry.kt
  app/src/main/java/org/wikipedia/history/db/HistoryEntryDao.kt
  app/src/main/java/org/wikipedia/language/LangLinksActivity.kt
  app/src/main/java/org/wikipedia/language/LangLinksViewModel.kt
  app/src/main/java/org/wikipedia/page/PageActivity.kt
  app/src/main/java/org/wikipedia/page/PageContainerLongPressHandler.kt
  app/src/main/java/org/wikipedia/page/PageFragment.kt
  app/src/main/java/org/wikipedia/page/PageFragmentLoadState.kt
Labels: Ready to merge

#5408 Temp accounts: explicitly set expiry to 90 days.
  app/src/main/java/org/wikipedia/auth/AccountUtil.kt
  app/src/main/java/org/wikipedia/dataclient/SharedPreferenceCookieManager.kt
  app/src/main/java/org/wikipedia/settings/LogoutPreference.kt
  app/src/main/java/org/wikipedia/settings/Prefs.kt
  app/src/main/res/values/preference_keys.xml
  app/src/main/res/xml/developer_preferences.xml
Labels: Minor, High Priority

#5380 Compose top bar with search
  app/src/main/java/org/wikipedia/compose/components/SearchTopAppBar.kt
  app/src/main/java/org/wikipedia/compose/components/WikiTopAppBar.kt
  app/src/main/java/org/wikipedia/compose/components/WikiTopAppBarWithSearch.kt
Labels: Ready to merge

#5413 Follow-up: Compose topbar with search
  app/src/main/java/org/wikipedia/compose/components/SearchTopAppBar.kt
  app/src/main/java/org/wikipedia/compose/components/WikiTopAppBar.kt
  app/src/main/java/org/wikipedia/compose/components/WikiTopAppBarWithSearch.kt
  app/src/main/res/values-ar/strings.xml
  app/src/main/res/values-bn/strings.xml
  app/src/main/res/values-ckb/strings.xml
  app/src/main/res/values-et/strings.xml
  app/src/main/res/values-fa/strings.xml
  app/src/main/res/values-fi/strings.xml
  app/src/main/res/values-hi/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values-iw/strings.xml
  app/src/main/res/values-ko/strings.xml
  app/src/main/res/values-lb/strings.xml
  app/src/main/res/values-mk/strings.xml
  app/src/main/res/values-pa/strings.xml
  app/src/main/res/values-qq/strings.xml
  app/src/main/res/values-sl/strings.xml
  app/src/main/res/values-sr/strings.xml
  app/src/main/res/values-sv/strings.xml
  app/src/main/res/values-tcy/strings.xml
  app/src/main/res/values-uk/strings.xml
  app/src/main/res/values/strings.xml
Labels: Minor

#5425 Improve performance of filtering History entries.
  app/src/main/java/org/wikipedia/history/db/HistoryEntryWithImageDao.kt
Labels: Minor, High Priority

#5424 Introduce indexes to db tables, greatly improving performance.
  app/schemas/org.wikipedia.database.AppDatabase/28.json
  app/src/androidTest/java/org/wikipedia/database/UpgradeFromPreRoomTest.kt
  app/src/main/java/org/wikipedia/database/AppDatabase.kt
  app/src/main/java/org/wikipedia/history/HistoryEntry.kt
  app/src/main/java/org/wikipedia/pageimages/db/PageImage.kt
Labels: High Priority

#5428 Correctly set Temp Account expiry day upon receipt of POST response.
  app/src/main/java/org/wikipedia/WikipediaApp.kt
  app/src/main/java/org/wikipedia/auth/AccountUtil.kt
  app/src/main/java/org/wikipedia/dataclient/mwapi/MwPostResponse.kt
  app/src/main/java/org/wikipedia/login/LoginActivity.kt
Labels: Minor, High Priority

#5427 follow up compose wiktionary dialog
  app/src/main/java/org/wikipedia/wiktionary/WiktionaryDialogScreen.kt
  app/src/main/java/org/wikipedia/wiktionary/WiktionaryViewModel.kt
Labels: Minor, Ready to merge

#5430 Update migration query to also insert missing PageImage rows.
  app/src/main/java/org/wikipedia/database/AppDatabase.kt
Labels: Minor, High Priority, Ready to merge

#5432 Final, ultimate fixes for db migration.
  app/src/main/java/org/wikipedia/database/AppDatabase.kt
  app/src/main/java/org/wikipedia/history/db/HistoryEntryWithImageDao.kt
Labels: Minor, High Priority

#5440 Compose Test Support
  app/build.gradle
  app/src/androidTest/java/org/wikipedia/base/BaseTest.kt
  app/src/androidTest/java/org/wikipedia/robots/feature/SettingsRobot.kt
  app/src/androidTest/java/org/wikipedia/tests/settings/AboutSettingsTest.kt
  gradle/libs.versions.toml
Labels: Minor, Ready to merge

#5441 Make View.setLayoutDirection into an extension function.
  app/src/main/java/org/wikipedia/categories/CategoryDialog.kt
  app/src/main/java/org/wikipedia/commons/FilePageFragment.kt
  app/src/main/java/org/wikipedia/commons/ImagePreviewDialog.kt
  app/src/main/java/org/wikipedia/descriptions/DescriptionEditBottomBarView.kt
  app/src/main/java/org/wikipedia/descriptions/DescriptionEditReviewView.kt
  app/src/main/java/org/wikipedia/descriptions/DescriptionEditView.kt
  app/src/main/java/org/wikipedia/diff/ArticleEditDetailsFragment.kt
  app/src/main/java/org/wikipedia/edit/EditSectionActivity.kt
  app/src/main/java/org/wikipedia/edit/summaries/EditSummaryHandler.kt
  app/src/main/java/org/wikipedia/extensions/View.kt
  app/src/main/java/org/wikipedia/feed/news/NewsFragment.kt
  app/src/main/java/org/wikipedia/feed/suggestededits/SuggestedEditsCardItemFragment.kt
  app/src/main/java/org/wikipedia/feed/suggestededits/SuggestedEditsCardView.kt
  app/src/main/java/org/wikipedia/feed/topread/TopReadFragment.kt
  app/src/main/java/org/wikipedia/feed/view/CardHeaderView.kt
  app/src/main/java/org/wikipedia/feed/view/CardLargeHeaderView.kt
  app/src/main/java/org/wikipedia/feed/view/DefaultFeedCardView.kt
  app/src/main/java/org/wikipedia/notifications/NotificationActivity.kt
  app/src/main/java/org/wikipedia/page/SidePanelHandler.kt
  app/src/main/java/org/wikipedia/page/linkpreview/LinkPreviewDialog.kt
  app/src/main/java/org/wikipedia/page/references/ReferenceDialog.kt
  app/src/main/java/org/wikipedia/random/RandomItemFragment.kt
  app/src/main/java/org/wikipedia/search/SearchResultsFragment.kt
  app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsCardsItemFragment.kt
  app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsImageTagsFragment.kt
  app/src/main/java/org/wikipedia/talk/TalkReplyActivity.kt
  app/src/main/java/org/wikipedia/talk/TalkTopicActivity.kt
  app/src/main/java/org/wikipedia/talk/TalkTopicsActivity.kt
  app/src/main/java/org/wikipedia/util/L10nUtil.kt
  app/src/main/java/org/wikipedia/views/WikiArticleCardView.kt
  app/src/main/java/org/wikipedia/watchlist/WatchlistItemView.kt
  app/src/main/java/org/wikipedia/wiktionary/WiktionaryDialog.kt
Labels: Minor

#5444 Update the default visibility of recent search container to "gone"
  app/src/main/res/layout/fragment_search_recent.xml
Labels: Minor

#5443 Follow-up of ReadingListFramgent to use viewModel
  app/src/main/java/org/wikipedia/readinglist/ReadingListFragmentViewModel.kt
Labels: Minor

#5423 Build a template for a Year in Review screen
  app/src/main/java/org/wikipedia/yearinreview/YearInReviewActivity.kt
  app/src/main/java/org/wikipedia/yearinreview/YearInReviewNavigation.kt
  app/src/main/java/org/wikipedia/yearinreview/YearInReviewScaffold.kt
  app/src/main/java/org/wikipedia/yearinreview/YearInReviewScreenData.kt
  app/src/main/res/drawable/wyir_block_5_resize.gif
  app/src/main/res/drawable/wyir_bytes.gif
  app/src/main/res/drawable/year_in_review_block_10_resize.gif
  app/src/main/res/drawable/year_in_review_puzzle_pieces.png
  app/src/main/res/values-qq/strings.xml
  app/src/main/res/values/strings.xml
Labels: Ready to merge
