Repository wikimedia/apps-android-wikipedia, pull requests merged in 2025-04, with the labels that each got.

#5448 Follow up: Year-in-review code format optimization
  app/src/main/java/org/wikipedia/yearinreview/YearInReviewActivity.kt
  app/src/main/java/org/wikipedia/yearinreview/YearInReviewScaffold.kt
Labels: Minor

#5446 Compose Language List experimentation
  app/src/main/java/org/wikipedia/language/addlanguages/AddLanguagesListActivity.kt
  app/src/main/java/org/wikipedia/language/addlanguages/AddLanguagesListScreen.kt
  app/src/main/java/org/wikipedia/language/addlanguages/AddLanguagesViewModel.kt
Labels: Minor

#5452 Hygiene: remove unused variables and update code format
  app/src/main/java/org/wikipedia/dataclient/page/PageSummary.kt
  app/src/main/java/org/wikipedia/page/PageFragmentLoadState.kt
  app/src/main/java/org/wikipedia/page/PageProperties.kt
Labels: Minor

#5454 Pass login UI messages through parser.
  app/src/main/java/org/wikipedia/login/LoginActivity.kt
  app/src/main/java/org/wikipedia/login/LoginClient.kt
  app/src/main/java/org/wikipedia/util/FeedbackUtil.kt
  app/src/main/res/layout/activity_login.xml
Labels: Minor, High Priority

#5460 compose SearchEmptyView
  app/src/main/java/org/wikipedia/compose/components/SearchEmptyView.kt
Labels: Ready to merge

#5456 Convert WikiCardView to use Compose
  app/src/main/java/org/wikipedia/compose/components/WikiCard.kt
Labels: Ready to merge

#5457 Enable EmailAuth support.
  app/src/main/java/org/wikipedia/csrf/CsrfTokenClient.kt
  app/src/main/java/org/wikipedia/dataclient/Service.kt
  app/src/main/java/org/wikipedia/dataclient/SharedPreferenceCookieManager.kt
  app/src/main/java/org/wikipedia/dataclient/okhttp/CommonHeaderRequestInterceptor.kt
  app/src/main/java/org/wikipedia/login/LoginActivity.kt
  app/src/main/java/org/wikipedia/login/LoginClient.kt
  app/src/main/java/org/wikipedia/login/LoginEmailAuthResult.kt
  app/src/main/java/org/wikipedia/login/LoginResponse.kt
  app/src/main/java/org/wikipedia/login/ResetPasswordActivity.kt
  app/src/main/java/org/wikipedia/settings/Prefs.kt
  app/src/main/java/org/wikipedia/views/NonEmptyValidator.kt
  app/src/main/res/layout/activity_reset_password.xml
  app/src/main/res/values-qq/strings.xml
  app/src/main/res/values/preference_keys.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/xml/developer_preferences.xml
Labels: High Priority

#5447 Create and add pagination indicator to the BottomAppBar - T387941
  app/build.gradle
  app/src/main/java/org/wikipedia/yearinreview/YearInReviewActivity.kt
  app/src/main/java/org/wikipedia/yearinreview/YearInReviewScaffold.kt
  gradle/libs.versions.toml
Labels: Ready for Review

#5462 [Compose] Make the search field to single line
  app/src/main/java/org/wikipedia/compose/components/SearchTopAppBar.kt
Labels: Minor

#5461 Follow-up: YiR pagination and code formats update
  app/src/main/java/org/wikipedia/yearinreview/YearInReviewScaffold.kt
Labels: Minor, Ready to merge

#5377 [Compose] Convert WiktionaryDialog to use Compose
  app/src/main/java/org/wikipedia/wiktionary/WiktionaryDialog.kt
  app/src/main/java/org/wikipedia/wiktionary/WiktionaryDialogScreen.kt
  app/src/main/java/org/wikipedia/wiktionary/WiktionaryViewModel.kt
  app/src/main/res/layout/dialog_wiktionary.xml
  app/src/main/res/layout/item_wiktionary_definition_with_examples.xml
  app/src/main/res/layout/item_wiktionary_definitions_list.xml
  app/src/main/res/layout/item_wiktionary_example.xml
Labels: Ready to merge

#5464 When clearing all History, also clear PageImage table.
  app/src/main/java/org/wikipedia/history/HistoryFragment.kt
  app/src/main/java/org/wikipedia/history/HistoryViewModel.kt
  app/src/main/java/org/wikipedia/pageimages/db/PageImageDao.kt
Labels: Minor

#5375 Compose language list design
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/wikipedia/compose/theme/WikipediaTypography.kt
  app/src/main/java/org/wikipedia/language/LanguagesListActivity.kt
  app/src/main/java/org/wikipedia/language/LanguagesListViewModel.kt
  app/src/main/java/org/wikipedia/language/addlanguages/AddLanguagesListActivity.kt
  app/src/main/java/org/wikipedia/language/addlanguages/AddLanguagesListScreen.kt
  app/src/main/java/org/wikipedia/language/addlanguages/AddLanguagesViewModel.kt
  app/src/main/java/org/wikipedia/settings/languages/WikipediaLanguagesFragment.kt
  app/src/main/java/org/wikipedia/util/Resource.kt
  app/src/main/res/layout/activity_languages_list.xml
Labels: Ready to merge

#5442 Introduce Context extensions for getting string resources.
  app/src/main/java/org/wikipedia/bridge/JavaScriptActionHandler.kt
  app/src/main/java/org/wikipedia/descriptions/DescriptionEditViewModel.kt
  app/src/main/java/org/wikipedia/edit/summaries/EditSummaryFragment.kt
  app/src/main/java/org/wikipedia/extensions/Context.kt
  app/src/main/java/org/wikipedia/feed/becauseyouread/BecauseYouReadCard.kt
  app/src/main/java/org/wikipedia/feed/featured/FeaturedArticleCard.kt
  app/src/main/java/org/wikipedia/feed/image/FeaturedImageCard.kt
  app/src/main/java/org/wikipedia/feed/mainpage/MainPageCardView.kt
  app/src/main/java/org/wikipedia/feed/news/NewsCard.kt
  app/src/main/java/org/wikipedia/feed/onthisday/OnThisDayCard.kt
  app/src/main/java/org/wikipedia/feed/onthisday/OnThisDayCardView.kt
  app/src/main/java/org/wikipedia/feed/onthisday/OnThisDayFragment.kt
  app/src/main/java/org/wikipedia/feed/places/PlacesCard.kt
  app/src/main/java/org/wikipedia/feed/random/RandomCard.kt
  app/src/main/java/org/wikipedia/feed/suggestededits/SuggestedEditsCard.kt
  app/src/main/java/org/wikipedia/feed/topread/TopReadListCard.kt
  app/src/main/java/org/wikipedia/feed/wikigames/WikiGamesCardView.kt
  app/src/main/java/org/wikipedia/gallery/MediaDownloadReceiver.kt
  app/src/main/java/org/wikipedia/language/AppLanguageState.kt
  app/src/main/java/org/wikipedia/page/SidePanelHandler.kt
  app/src/main/java/org/wikipedia/page/linkpreview/LinkPreviewContents.kt
  app/src/main/java/org/wikipedia/page/linkpreview/LinkPreviewDialog.kt
  app/src/main/java/org/wikipedia/readinglist/ReadingListFragmentViewModel.kt
  app/src/main/java/org/wikipedia/readinglist/database/ReadingList.kt
  app/src/main/java/org/wikipedia/readinglist/db/ReadingListDao.kt
  app/src/main/java/org/wikipedia/talk/template/TalkTemplatesViewModel.kt
  app/src/main/java/org/wikipedia/util/DateUtil.kt
  app/src/main/java/org/wikipedia/util/L10nUtil.kt
  app/src/main/java/org/wikipedia/views/NotificationActionsOverflowView.kt
  app/src/main/java/org/wikipedia/watchlist/WatchlistViewModel.kt
Labels: Ready to merge

#5459 Remove outdated analytics code
  app/src/main/java/org/wikipedia/activity/BaseActivity.kt
  app/src/main/java/org/wikipedia/analytics/eventplatform/CustomizeToolbarEvent.kt
  app/src/main/java/org/wikipedia/analytics/eventplatform/EditHistoryInteractionEvent.kt
  app/src/main/java/org/wikipedia/analytics/eventplatform/NotificationInteractionEvent.kt
  app/src/main/java/org/wikipedia/analytics/eventplatform/UserContributionEvent.kt
  app/src/main/java/org/wikipedia/diff/ArticleEditDetailsFragment.kt
  app/src/main/java/org/wikipedia/diff/UndoEditDialog.kt
  app/src/main/java/org/wikipedia/notifications/NotificationActivity.kt
  app/src/main/java/org/wikipedia/notifications/NotificationPollBroadcastReceiver.kt
  app/src/main/java/org/wikipedia/notifications/NotificationViewModel.kt
  app/src/main/java/org/wikipedia/page/customize/CustomizeToolbarFragment.kt
  app/src/main/java/org/wikipedia/page/edithistory/EditHistoryListActivity.kt
  app/src/main/java/org/wikipedia/settings/DeveloperSettingsPreferenceLoader.kt
  app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsTasksFragment.kt
  app/src/main/java/org/wikipedia/talk/UserTalkPopupHelper.kt
  app/src/main/java/org/wikipedia/views/NotificationActionsOverflowView.kt
  app/src/main/res/values/preference_keys.xml
  app/src/main/res/xml/developer_preferences.xml
Labels: Minor

#5476 Add preview for AddLanguagesListScreen.
  app/src/main/java/org/wikipedia/language/addlanguages/AddLanguagesListScreen.kt
  app/src/main/java/org/wikipedia/language/addlanguages/AddLanguagesViewModel.kt
Labels: Minor

#5477 Expand preview of Wiktionary dialog.
  app/src/main/java/org/wikipedia/wiktionary/WiktionaryDialogScreen.kt
Labels: Minor

#5465 Build a BottomSheet for the Explore Screen and add it the navigation path - T390121
  app/src/main/java/org/wikipedia/main/MainFragment.kt
  app/src/main/java/org/wikipedia/yearinreview/BottomSheetScaffold.kt
  app/src/main/java/org/wikipedia/yearinreview/YearInReviewDialog.kt
  app/src/main/java/org/wikipedia/yearinreview/YearInReviewScaffold.kt
  app/src/main/res/drawable/wyir_puzzle_4_v2.gif
  app/src/main/res/values-qq/strings.xml
  app/src/main/res/values/strings.xml
Labels: Ready for Review

#5478 Compose: simplify WikiErrorView and context handling.
  app/src/main/java/org/wikipedia/compose/components/error/ComposeWikiErrorView.kt
  app/src/main/java/org/wikipedia/compose/components/error/ComposeWikiErrorViewModel.kt
  app/src/main/java/org/wikipedia/language/addlanguages/AddLanguagesListScreen.kt
  app/src/main/java/org/wikipedia/settings/AboutActivity.kt
Labels: Minor

#5479 Follow-up: YiR entry dialog code optimization
  app/src/main/java/org/wikipedia/main/MainFragment.kt
  app/src/main/java/org/wikipedia/yearinreview/YearInReviewEntryDialog.kt
  app/src/main/java/org/wikipedia/yearinreview/YearInReviewEntryDialogScreen.kt
  app/src/main/res/values-qq/strings.xml
  app/src/main/res/values/strings.xml
Labels: Minor

#5482 Correctly show/hide wikitext toolbar based on IME state.
  app/src/main/java/org/wikipedia/edit/EditSectionActivity.kt
  app/src/main/java/org/wikipedia/edit/SyntaxHighlightViewAdapter.kt
  app/src/main/java/org/wikipedia/talk/TalkReplyActivity.kt
  app/src/main/res/layout/activity_edit_section.xml
Labels: Minor, High Priority

#5484 Updates edits requirement to show Article Description
  app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsTasksFragment.kt
Labels: Ready to merge

#5488 Fix/improve logic for checking Watched status of Talk page.
  app/src/main/java/org/wikipedia/talk/TalkTopicsViewModel.kt
Labels: Minor

#5458 Convert MessageCardView to use Compose
  app/src/main/java/org/wikipedia/compose/components/WikiCard.kt
Labels: Ready to merge

#5387 Compose langslink Screen
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/wikipedia/language/LangLinksActivity.kt
  app/src/main/java/org/wikipedia/language/LangLinksScreen.kt
  app/src/main/java/org/wikipedia/language/LangLinksViewModel.kt
  app/src/main/res/layout/activity_langlinks.xml
Labels: Ready to merge

#5495 Correctly render BC dates in OnThisDay.
  app/src/main/java/org/wikipedia/util/DateUtil.kt
Labels: Minor

#5493 Hygiene: remove unused code and simplify abstract class
  app/src/main/java/org/wikipedia/page/LinkHandler.kt
  app/src/main/java/org/wikipedia/usercontrib/UserContribListActivity.kt
  app/src/main/java/org/wikipedia/watchlist/WatchlistFilterTypes.kt
Labels: Minor

#5500 Fix crash when long-pressing to open from Places Search.
  app/src/main/java/org/wikipedia/search/SearchFragment.kt
Labels: Minor, High Priority

#5499 Fix potential crash(es) due to coroutine without exception handler.
  app/src/main/java/org/wikipedia/page/PageFragmentLoadState.kt
  app/src/main/java/org/wikipedia/talk/TalkTopicHolder.kt
Labels: Minor, High Priority

#5502 Rename string item and move it to a proper location
  app/src/androidTest/java/org/wikipedia/robots/feature/SettingsRobot.kt
  app/src/main/java/org/wikipedia/settings/AboutActivity.kt
  app/src/main/res/values-ar/strings.xml
  app/src/main/res/values-az/strings.xml
  app/src/main/res/values-da/strings.xml
  app/src/main/res/values-fi/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values-iw/strings.xml
  app/src/main/res/values-mk/strings.xml
  app/src/main/res/values-nl/strings.xml
  app/src/main/res/values-qq/strings.xml
  app/src/main/res/values-sl/strings.xml
  app/src/main/res/values-sv/strings.xml
  app/src/main/res/values-uk/strings.xml
  app/src/main/res/values-zh-rTW/strings.xml
  app/src/main/res/values-zh/strings.xml
  app/src/main/res/values/strings.xml
Labels: Minor

#5507 Fix edits requirements update
  app/src/main/java/org/wikipedia/feed/suggestededits/SuggestedEditsCardView.kt
  app/src/main/java/org/wikipedia/feed/suggestededits/SuggestedEditsFeedClient.kt
Labels: Ready to merge
