Repository wikimedia/apps-android-wikipedia, pull requests merged in 2025-02, with the labels that each got.

#5287 [Wikigames] string for share-link
  app/src/main/res/values-qq/strings.xml
  app/src/main/res/values/strings.xml
Labels: Minor

#5281 WikiGames: build bottom sheet popup for final screen
  app/src/main/java/org/wikipedia/games/onthisday/OnThisDayGameActivity.kt
  app/src/main/java/org/wikipedia/games/onthisday/OnThisDayGameFinalFragment.kt
  app/src/main/res/layout/activity_on_this_day_game.xml
  app/src/main/res/layout/dialog_on_this_day_game_article.xml
Labels: Ready to merge

#5291 puts credits.xml back
  app/src/main/res/values/credits.xml
Labels: High Priority

#5230 WikiGames (feature branch)
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/wikipedia/Constants.kt
  app/src/main/java/org/wikipedia/feed/FeedContentType.kt
  app/src/main/java/org/wikipedia/feed/FeedFragment.kt
  app/src/main/java/org/wikipedia/feed/configure/ConfigureViewModel.kt
  app/src/main/java/org/wikipedia/feed/configure/FeedAvailability.kt
  app/src/main/java/org/wikipedia/feed/model/CardType.kt
  app/src/main/java/org/wikipedia/feed/onthisday/OnThisDay.kt
  app/src/main/java/org/wikipedia/feed/wikigames/WikiGamesCard.kt
  app/src/main/java/org/wikipedia/feed/wikigames/WikiGamesCardClient.kt
  app/src/main/java/org/wikipedia/feed/wikigames/WikiGamesCardView.kt
  app/src/main/java/org/wikipedia/games/onthisday/OnThisDayGameActivity.kt
  app/src/main/java/org/wikipedia/games/onthisday/OnThisDayGameFinalFragment.kt
  app/src/main/java/org/wikipedia/games/onthisday/OnThisDayGameOnboardingFragment.kt
  app/src/main/java/org/wikipedia/games/onthisday/OnThisDayGameViewModel.kt
  app/src/main/java/org/wikipedia/history/HistoryEntry.kt
  app/src/main/java/org/wikipedia/page/PageFragment.kt
  app/src/main/java/org/wikipedia/settings/DeveloperSettingsPreferenceLoader.kt
  app/src/main/java/org/wikipedia/settings/Prefs.kt
  app/src/main/java/org/wikipedia/views/ViewUtil.kt
  app/src/main/java/org/wikipedia/views/WikiCardView.kt
  app/src/main/res/drawable/baseline_info_24.xml
  app/src/main/res/drawable/check_circle_24px.xml
  app/src/main/res/drawable/game_card_background.xml
  app/src/main/res/drawable/game_date_background_correct.xml
  app/src/main/res/drawable/game_date_background_incorrect.xml
  app/src/main/res/drawable/game_date_background_neutral.xml
  app/src/main/res/drawable/ic_cancel_24px.xml
  app/src/main/res/drawable/ic_circle_outline_24.xml
  app/src/main/res/drawable/ic_horizontal_rule_24.xml
  app/src/main/res/drawable/ic_pause_filled_24.xml
  app/src/main/res/drawable/ic_time_24.xml
  app/src/main/res/drawable/ic_today_24px.xml
  app/src/main/res/drawable/ic_wiki_games_events.xml
  app/src/main/res/drawable/illustration_trivia_game.xml
  app/src/main/res/drawable/illustration_trivia_game_splash.xml
  app/src/main/res/drawable/outline_notification_add_24.xml
  app/src/main/res/layout/activity_on_this_day_game.xml
  app/src/main/res/layout/dialog_on_this_day_game.xml
  app/src/main/res/layout/dialog_on_this_day_game_article.xml
  app/src/main/res/layout/fragment_on_this_day_game_final.xml
  app/src/main/res/layout/fragment_on_this_day_game_onboarding.xml
  app/src/main/res/layout/item_on_this_day_game_topic.xml
  app/src/main/res/layout/view_wiki_games_card.xml
  app/src/main/res/menu/menu_on_this_day_game.xml
  app/src/main/res/raw/sound_completion.ogg
  app/src/main/res/raw/sound_logo.ogg
  app/src/main/res/values-qq/strings.xml
  app/src/main/res/values/preference_keys.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/strings_no_translate.xml
  app/src/main/res/values/styles.xml
  app/src/main/res/xml/developer_preferences.xml
Labels: Ready to merge

#5286 [Wikigames] sharing link
  app/src/main/java/org/wikipedia/games/onthisday/OnThisDayGameFinalFragment.kt
  app/src/main/res/values/strings_no_translate.xml
Labels: Ready to merge

#5298 Remove empty item from talk page list for incorrect header
  app/src/main/java/org/wikipedia/talk/TalkTopicsViewModel.kt
Labels: Minor

#5269 [Wikigames] daily notification
  app/src/main/java/org/wikipedia/ActivityLifecycleHandler.kt
  app/src/main/java/org/wikipedia/WikipediaApp.kt
  app/src/main/java/org/wikipedia/games/onthisday/OnThisDayGameActivity.kt
  app/src/main/java/org/wikipedia/games/onthisday/OnThisDayGameDialogs.kt
  app/src/main/java/org/wikipedia/games/onthisday/OnThisDayGameNotificationManager.kt
  app/src/main/java/org/wikipedia/notifications/NotificationPollBroadcastReceiver.kt
  app/src/main/java/org/wikipedia/notifications/NotificationPresenter.kt
  app/src/main/java/org/wikipedia/settings/DeveloperSettingsPreferenceLoader.kt
  app/src/main/java/org/wikipedia/settings/Prefs.kt
  app/src/main/res/drawable/outline_notifications_active_24.xml
  app/src/main/res/drawable/outline_notifications_off_24.xml
  app/src/main/res/values/dev_settings_strings.xml
  app/src/main/res/values/preference_keys.xml
  app/src/main/res/xml/developer_preferences.xml
Labels: Ready to merge

#5300 Update texts color for Wikigame
  app/src/main/res/layout/activity_on_this_day_game.xml
  app/src/main/res/layout/fragment_on_this_day_game_final.xml
Labels: Minor

#5297 Wikigame: remove visibility set for bookmark icon and change image loading function
  app/src/main/java/org/wikipedia/games/onthisday/OnThisDayGameFinalFragment.kt
Labels: Minor

#5301 Quick followup: simplify ActivityLifecycleHandler changes.
  app/src/main/java/org/wikipedia/ActivityLifecycleHandler.kt
  app/src/main/java/org/wikipedia/WikipediaApp.kt
  app/src/main/java/org/wikipedia/games/onthisday/OnThisDayGameNotificationManager.kt
  app/src/main/java/org/wikipedia/notifications/NotificationPollBroadcastReceiver.kt
Labels: Minor

#5302 Follow-up: simplify and tighten OnThisGameNotificationManager.
  app/src/main/java/org/wikipedia/games/onthisday/OnThisDayGameActivity.kt
  app/src/main/java/org/wikipedia/games/onthisday/OnThisDayGameDialogs.kt
  app/src/main/java/org/wikipedia/games/onthisday/OnThisDayGameNotificationManager.kt
Labels: Minor

#5303 WikiGames: snackbar at end of game.
  app/src/main/java/org/wikipedia/feed/wikigames/WikiGamesCardView.kt
  app/src/main/java/org/wikipedia/games/onthisday/OnThisDayGameActivity.kt
  app/src/main/java/org/wikipedia/games/onthisday/OnThisDayGameFinalFragment.kt
  app/src/main/java/org/wikipedia/games/onthisday/OnThisDayGameOnboardingFragment.kt
  app/src/main/java/org/wikipedia/page/PageActivity.kt
  app/src/main/res/values-qq/strings.xml
  app/src/main/res/values/strings.xml
Labels: Minor, High Priority

#5299 Expresso fixes
  app/src/androidTest/java/org/wikipedia/base/BaseRobot.kt
  app/src/androidTest/java/org/wikipedia/robots/feature/ExploreFeedRobot.kt
  app/src/androidTest/java/org/wikipedia/tests/settings/CustomizeExploreFeedTest.kt
Labels: Minor

#5304 WikiGames: Design tweaks.
  app/src/main/java/org/wikipedia/games/onthisday/OnThisDayGameActivity.kt
  app/src/main/java/org/wikipedia/games/onthisday/OnThisDayGameOnboardingFragment.kt
  app/src/main/res/layout/activity_on_this_day_game.xml
  app/src/main/res/layout/fragment_on_this_day_game_onboarding.xml
  app/src/main/res/raw/sound_error.ogg
  app/src/main/res/raw/sound_logo.ogg
Labels: High Priority

#5307 WikiGames: Update logic to reset unconditionally when new day starts.
  app/src/main/java/org/wikipedia/games/onthisday/OnThisDayGameViewModel.kt
Labels: Minor, High Priority

#5294 [WikiGames] Analytics
  app/src/main/java/org/wikipedia/analytics/eventplatform/WikiGamesEvent.kt
  app/src/main/java/org/wikipedia/feed/wikigames/WikiGamesCardView.kt
  app/src/main/java/org/wikipedia/games/onthisday/OnThisDayGameActivity.kt
  app/src/main/java/org/wikipedia/games/onthisday/OnThisDayGameFinalFragment.kt
  app/src/main/java/org/wikipedia/games/onthisday/OnThisDayGameNotificationManager.kt
  app/src/main/java/org/wikipedia/games/onthisday/OnThisDayGameOnboardingFragment.kt
  app/src/main/java/org/wikipedia/games/onthisday/OnThisDayGameViewModel.kt
Labels: Ready to merge

#5306 WikiGames: survey.
  app/src/main/java/org/wikipedia/activity/BaseActivity.kt
  app/src/main/java/org/wikipedia/games/onthisday/OnThisDayGameActivity.kt
  app/src/main/java/org/wikipedia/games/onthisday/OnThisDayGameFinalFragment.kt
  app/src/main/java/org/wikipedia/page/PageActivity.kt
  app/src/main/java/org/wikipedia/settings/Prefs.kt
  app/src/main/res/layout/fragment_on_this_day_game_onboarding.xml
  app/src/main/res/values-qq/strings.xml
  app/src/main/res/values/preference_keys.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/xml/developer_preferences.xml
Labels: High Priority

#5311 Hygiene: remove unused strings
  app/src/main/res/values/strings.xml
Labels: Minor

#5316 Use correct WikiSite for final screen interactions.
  app/src/main/java/org/wikipedia/games/onthisday/OnThisDayGameArticleBottomSheet.kt
  app/src/main/java/org/wikipedia/games/onthisday/OnThisDayGameFinalFragment.kt
Labels: Minor, High Priority

#5326 Prevent possible crash when exiting game during loading.
  app/src/main/java/org/wikipedia/games/onthisday/OnThisDayGameActivity.kt
  app/src/main/java/org/wikipedia/games/onthisday/OnThisDayGameViewModel.kt
Labels: Minor, High Priority

#5320 strings for about screen
  app/src/main/res/values-qq/strings.xml
  app/src/main/res/values/strings.xml
Labels: Minor

#5328 Wikigames: remove unused and duplicated strings
  app/src/main/res/values-qq/strings.xml
  app/src/main/res/values/strings.xml
Labels: Minor

#5329 Fix race condition when sending events after initial install.
  app/src/main/java/org/wikipedia/analytics/eventplatform/EventPlatformClient.kt
Labels: Minor, High Priority

#5327 Refine game-related analytics.
  app/src/main/java/org/wikipedia/games/onthisday/OnThisDayGameActivity.kt
  app/src/main/java/org/wikipedia/games/onthisday/OnThisDayGameOnboardingFragment.kt
  app/src/main/java/org/wikipedia/games/onthisday/OnThisDayGameViewModel.kt
Labels: Minor, High Priority

#5331 Final, ultimate, definitely for real, design tweaks to the game.
  app/src/main/java/org/wikipedia/games/onthisday/OnThisDayGameActivity.kt
  app/src/main/java/org/wikipedia/games/onthisday/OnThisDayGameViewModel.kt
  app/src/main/res/layout/activity_on_this_day_game.xml
Labels: Minor, High Priority

#5333 Show snackbar over BottomSheet only if allowed.
  app/src/main/java/org/wikipedia/games/onthisday/OnThisDayGameArticleBottomSheet.kt
  app/src/main/java/org/wikipedia/util/FeedbackUtil.kt
  app/src/main/java/org/wikipedia/views/AllowSnackbarOverBottomSheet.kt
Labels: Minor, High Priority

#5332 Minor Wikigame design change
  app/src/main/res/layout/view_wiki_games_card.xml
Labels: Minor

#5247 Convert animation resources to use Compose
  app/src/main/java/org/wikipedia/compose/extensions/Modifier.kt
Labels: Ready to merge

#5339 Fix potential crash when zooming images with ImageZoomHelper.
  app/src/main/java/org/wikipedia/views/ImageZoomHelper.kt
Labels: Minor, High Priority

#5336 Fix: show/hide the edit button properly in the Talk Templates
  app/src/main/java/org/wikipedia/talk/template/TalkTemplatesFragment.kt
Labels: Minor

#5345 Wikigames: Hide next question button after clicking on it
  app/src/main/java/org/wikipedia/games/onthisday/OnThisDayGameActivity.kt
Labels: Minor

#5348 Fix wiki game uninitialized currentState
  app/src/main/java/org/wikipedia/games/onthisday/OnThisDayGameViewModel.kt
Labels: Bug, Ready to merge

#5351 Follow up: code format update and remove unused methods
  app/src/main/java/org/wikipedia/games/onthisday/OnThisDayGameViewModel.kt
Labels: Minor

#5346 Disable the item long click when the action mode is on
  app/src/main/java/org/wikipedia/history/HistoryFragment.kt
  app/src/main/java/org/wikipedia/notifications/NotificationActivity.kt
Labels: Minor
