Repository wikimedia/apps-android-wikipedia, pull requests merged in 2025-07, with the labels that each got.

#5737 Update mediawiki URL for help with edit summaries.
  app/src/main/res/values/strings_no_translate.xml
Labels: Minor

#5738 Remove extra language variants code and add an extra parameter to featured endpoint
  app/src/main/java/org/wikipedia/dataclient/RestService.kt
  app/src/main/java/org/wikipedia/feed/aggregated/AggregatedFeedContentClient.kt
  app/src/main/java/org/wikipedia/games/onthisday/OnThisDayGameViewModel.kt
  app/src/main/java/org/wikipedia/widgets/WidgetFeaturedPageWorker.kt
Labels: Ready to merge

#5742 Streamline and improve background re-login workflow.
  app/src/main/java/org/wikipedia/WikipediaApp.kt
  app/src/main/java/org/wikipedia/csrf/CsrfTokenClient.kt
  app/src/main/java/org/wikipedia/login/LoginClient.kt
Labels: Minor, High Priority

#5752 Fix: set the width correctly for the WikiGames feed card view
  app/src/main/res/layout/view_wiki_games_card.xml
Labels: Minor, High Priority

#5753 No longer use WebView in LinkPreviewDialog.
  app/src/main/java/org/wikipedia/bridge/JavaScriptActionHandler.kt
  app/src/main/java/org/wikipedia/page/linkpreview/LinkPreviewDialog.kt
  app/src/main/res/layout/dialog_link_preview.xml
Labels: High Priority, Ready to merge

#5743 WatchlistExpiryDialog to compose
  app/src/main/java/org/wikipedia/diff/ArticleEditDetailsFragment.kt
  app/src/main/java/org/wikipedia/watchlist/WatchlistExpiry.kt
  app/src/main/java/org/wikipedia/watchlist/WatchlistExpiryDialog.kt
  app/src/main/java/org/wikipedia/watchlist/WatchlistExpiryDialogViewModel.kt
  app/src/main/java/org/wikipedia/watchlist/WatchlistViewModel.kt
  app/src/main/res/layout/dialog_watchlist_expiry.xml
Labels: Ready to merge, Design review

#5690 automatically converting Codex color tokens to Compose color values
  scripts/generate-codex-colors.py
Labels: Ready to merge

#5756 Clear WebView cache when explicitly refreshing page.
  app/src/main/java/org/wikipedia/page/PageFragment.kt
Labels: Minor

#5765 Initialize fastlane.
  Gemfile
  Gemfile.lock
  fastlane/Appfile
  fastlane/Fastfile
Labels: Minor, dependencies

#5768 Fix listing of language variants where the first variant is the code.
  app/src/main/java/org/wikipedia/language/AppLanguageLookUpTable.kt
  app/src/main/java/org/wikipedia/language/LangLinksViewModel.kt
Labels: Minor, High Priority

#5740 On this day game code structure refactor
  app/src/main/java/org/wikipedia/activity/BaseActivity.kt
  app/src/main/java/org/wikipedia/feed/FeedFragment.kt
  app/src/main/java/org/wikipedia/games/onthisday/OnThisDayGameActivity.kt
  app/src/main/java/org/wikipedia/games/onthisday/OnThisDayGameMainMenuFragment.kt
  app/src/main/java/org/wikipedia/games/onthisday/OnThisDayGameNotificationManager.kt
  app/src/main/java/org/wikipedia/games/onthisday/OnThisDayGamePlayFragment.kt
  app/src/main/java/org/wikipedia/games/onthisday/OnThisDayGameResultFragment.kt
  app/src/main/java/org/wikipedia/page/PageFragment.kt
  app/src/main/res/layout/activity_on_this_day_game.xml
  app/src/main/res/layout/fragment_on_this_day_game_main_menu.xml
  app/src/main/res/layout/fragment_on_this_day_game_play.xml
  app/src/main/res/layout/fragment_on_this_day_game_result.xml
Labels: Minor, Ready for Review

#5723 Espresso Editing Test
  app/build.gradle
  app/src/androidTest/java/org/wikipedia/FakeData.kt
  app/src/androidTest/java/org/wikipedia/base/BaseTest.kt
  app/src/androidTest/java/org/wikipedia/base/actions/InputActions.kt
  app/src/androidTest/java/org/wikipedia/base/actions/VerificationActions.kt
  app/src/androidTest/java/org/wikipedia/robots/feature/EditorRobot.kt
  app/src/androidTest/java/org/wikipedia/robots/feature/PageRobot.kt
  app/src/androidTest/java/org/wikipedia/robots/feature/ReadingListRobot.kt
  app/src/androidTest/java/org/wikipedia/robots/feature/SearchRobot.kt
  app/src/androidTest/java/org/wikipedia/tests/editing/ArticleEditingTest.kt
  app/src/main/res/layout/view_wikitext_keyboard_formatting.xml
Labels: Ready to merge

#5766 Offline test workflow
  .github/workflows/android_offline_test.yml
  app/src/androidTest/java/org/wikipedia/robots/feature/ExploreFeedRobot.kt
Labels: Minor, Ready to merge

#5778 Don't use scaled versions of Gifs when loading in Gallery.
  app/src/main/java/org/wikipedia/gallery/GalleryItemFragment.kt
Labels: Minor

#5779 Include user-agent when posting with GitHubPRBot.
  .github/workflows/android_phab.yml
Labels: Minor

#5782 Edit Patrol Feedback dialog bug fix
  app/src/main/java/org/wikipedia/views/SurveyDialog.kt
Labels: Minor, Ready to merge
