Repository wikimedia/apps-android-wikipedia, pull requests merged in 2025-09, with the labels that each got.

#5886 Consolidate ActivityTabModules and ModuleType classes
  app/src/main/java/org/wikipedia/activitytab/ActivityTabCustomizationActivity.kt
  app/src/main/java/org/wikipedia/activitytab/ActivityTabModules.kt
Labels: Minor

#5863 Activity tab timeline
  app/build.gradle
  app/src/main/java/org/wikipedia/activitytab/ActivityTabFragment.kt
  app/src/main/java/org/wikipedia/activitytab/ActivityTabViewModel.kt
  app/src/main/java/org/wikipedia/activitytab/timeline/TimelineModule.kt
  app/src/main/java/org/wikipedia/activitytab/timeline/TimelinePagingSource.kt
  app/src/main/java/org/wikipedia/activitytab/timeline/TimelineRepository.kt
  app/src/main/java/org/wikipedia/dataclient/Service.kt
  app/src/main/java/org/wikipedia/extensions/Date.kt
  app/src/main/java/org/wikipedia/history/db/HistoryEntryWithImage.kt
  app/src/main/java/org/wikipedia/history/db/HistoryEntryWithImageDao.kt
  app/src/main/java/org/wikipedia/readinglist/db/ReadingListPageDao.kt
  app/src/main/java/org/wikipedia/util/DateUtil.kt
  app/src/main/res/drawable/outline_difference_24.xml
  app/src/main/res/values-qq/strings.xml
  app/src/main/res/values/strings.xml
  gradle/libs.versions.toml
Labels: Ready for Review

#5894 Update Contributions this month logic for design updates
  app/src/main/java/org/wikipedia/activitytab/EditingInsightsModule.kt
  app/src/main/res/values/strings.xml
Labels: Minor

#5895 Update WikiGames entry button for the Game module
  app/src/main/java/org/wikipedia/activitytab/ActivityTabFragment.kt
  app/src/main/java/org/wikipedia/activitytab/WikiGamesModule.kt
  app/src/main/res/values-qq/strings.xml
  app/src/main/res/values/strings.xml
Labels: Minor

#5883 Activity tab onboarding
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/wikipedia/activitytab/ActivityTabOnboardingActivity.kt
  app/src/main/java/org/wikipedia/main/MainFragment.kt
  app/src/main/java/org/wikipedia/settings/Prefs.kt
  app/src/main/res/drawable/ic_outline_lock_24.xml
  app/src/main/res/drawable/ic_outline_stadia_controller_24.xml
  app/src/main/res/values-qq/strings.xml
  app/src/main/res/values/preference_keys.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/xml/developer_preferences.xml
Labels: Ready to merge

#5896 Fix fdroid build (from Donation Reminder work).
  app/src/fdroid/java/org/wikipedia/donate/GooglePayComponent.kt
Labels: Minor, High Priority

#5898 Rename wikiSite to wikiSiteForTimeline for the specific usage
  app/src/main/java/org/wikipedia/activitytab/ActivityTabFragment.kt
  app/src/main/java/org/wikipedia/activitytab/ActivityTabViewModel.kt
  app/src/main/java/org/wikipedia/activitytab/timeline/TimelineRepository.kt
Labels: Minor

#5905 When injecting red overlay dot, use grandparent view instead of parent.
  app/src/main/java/org/wikipedia/navtab/NavTabLayout.kt
Labels: High Priority

#5904 Activity tab shimmer loading
  app/src/main/java/org/wikipedia/activitytab/ActivityTabFragment.kt
  app/src/main/java/org/wikipedia/activitytab/ActivityTabViewModel.kt
  app/src/main/java/org/wikipedia/activitytab/DonationModule.kt
  app/src/main/java/org/wikipedia/activitytab/EditingInsightsModule.kt
  app/src/main/java/org/wikipedia/activitytab/ImpactModule.kt
  app/src/main/java/org/wikipedia/activitytab/ReadingHistoryModule.kt
  app/src/main/java/org/wikipedia/activitytab/WikiGamesModule.kt
  app/src/main/java/org/wikipedia/activitytab/timeline/TimelineRepository.kt
  app/src/main/java/org/wikipedia/compose/extensions/Modifier.kt
  app/src/main/java/org/wikipedia/compose/theme/WikipediaColor.kt
Labels: Minor, Ready to merge

#5906 Add support for selectable TOTP auth module.
  app/src/main/java/org/wikipedia/dataclient/Service.kt
  app/src/main/java/org/wikipedia/login/LoginActivity.kt
  app/src/main/java/org/wikipedia/login/LoginClient.kt
  app/src/main/java/org/wikipedia/login/LoginModuleSelectResult.kt
  app/src/main/java/org/wikipedia/login/LoginOATHResult.kt
  app/src/main/java/org/wikipedia/login/LoginResponse.kt
  app/src/main/java/org/wikipedia/login/ResetPasswordActivity.kt
Labels: Minor

#5908 Dismiss the more menu dialog and refresh the content after logged out
  app/src/main/java/org/wikipedia/main/MainFragment.kt
Labels: Minor

#5919 Activity Tab crash fix
  app/src/main/java/org/wikipedia/activitytab/timeline/TimelineRepository.kt
Labels: Ready to merge

#5934 Prevent possible ANRs from serializing stream configs.
  app/src/main/java/org/wikipedia/analytics/eventplatform/EventPlatformClient.kt
Labels: Minor

#5938 Activity Tab: tweak verbiage in Edits screen.
  app/src/main/java/org/wikipedia/suggestededits/SuggestedEditsTasksFragment.kt
  app/src/main/res/layout/suggested_edits_tasks_container.xml
  app/src/main/res/values-qq/strings.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/strings_no_translate.xml
Labels: Minor, High Priority

#5936 Activity Tab: don't show Game module if unavailable in current language.
  app/src/main/java/org/wikipedia/activitytab/ActivityTabCustomizationActivity.kt
  app/src/main/java/org/wikipedia/activitytab/ActivityTabFragment.kt
  app/src/main/java/org/wikipedia/activitytab/ActivityTabModules.kt
  app/src/main/java/org/wikipedia/language/AppLanguageState.kt
Labels: Minor, High Priority

#5942 Hygiene: rewrite http->https scheme in both Beta and Prod.
  app/src/main/java/org/wikipedia/page/PageActivity.kt
Labels: Minor

#5944 Fix for Timeline items not updating the history entry table on click
  app/src/main/java/org/wikipedia/activitytab/timeline/TimelineRepository.kt
Labels: Ready to merge

#5945 Activity Tab: simplify timeline item and use correct source for HistoryEntry
  app/src/main/java/org/wikipedia/activitytab/ActivityTabFragment.kt
  app/src/main/java/org/wikipedia/activitytab/timeline/TimelineModule.kt
  app/src/main/java/org/wikipedia/activitytab/timeline/TimelineRepository.kt
Labels: Minor

#5952 Fix login flow when both Captcha and EmailAuth requested.
  app/src/main/java/org/wikipedia/login/LoginActivity.kt
  app/src/main/java/org/wikipedia/login/LoginClient.kt
Labels: Minor, High Priority

#5928 Activity tab timeline scroll jump fix
  app/src/main/java/org/wikipedia/activitytab/ActivityTabFragment.kt
  app/src/main/java/org/wikipedia/activitytab/ActivityTabViewModel.kt
  app/src/main/java/org/wikipedia/activitytab/EditingInsightsModule.kt
  app/src/main/java/org/wikipedia/activitytab/ImpactModule.kt
  app/src/main/java/org/wikipedia/activitytab/ReadingHistoryModule.kt
  app/src/main/java/org/wikipedia/activitytab/WikiGamesModule.kt
Labels: Minor
