Repository wikimedia/apps-android-wikipedia, pull requests merged in 2025-08, with the labels that each got.

#5812 Strings for donation reminders
  app/src/main/res/values-qq/strings.xml
  app/src/main/res/values/strings.xml
Labels: Ready to merge

#5814 Strings for the Donation Reminders
  app/src/main/res/values-qq/strings.xml
  app/src/main/res/values/strings.xml
Labels: Minor

#5786 Donation reminder set-up form
  app/src/extra/java/org/wikipedia/donate/GooglePayActivity.kt
  app/src/extra/java/org/wikipedia/donate/GooglePayViewModel.kt
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/wikipedia/compose/components/TextWithInlineElement.kt
  app/src/main/java/org/wikipedia/donate/DonateUtil.kt
  app/src/main/java/org/wikipedia/donate/donationreminder/DonationReminderActivity.kt
  app/src/main/java/org/wikipedia/donate/donationreminder/DonationReminderHelper.kt
  app/src/main/java/org/wikipedia/donate/donationreminder/DonationReminderScreen.kt
  app/src/main/java/org/wikipedia/donate/donationreminder/DonationReminderViewModel.kt
  app/src/main/java/org/wikipedia/settings/SettingsFragment.kt
  app/src/main/java/org/wikipedia/settings/SettingsPreferenceLoader.kt
  app/src/main/res/drawable/credit_card_heart_24.xml
  app/src/main/res/values/preference_keys.xml
  app/src/main/res/values/strings_no_translate.xml
  app/src/main/res/xml/preferences.xml
Labels: Ready for Review

#5817 Add strings for Donation Reminder error messages
  app/src/main/res/values-qq/strings.xml
  app/src/main/res/values/strings.xml
Labels: Minor

#5818 Fix: null from lateinit causes crash in DescriptionEditView
  app/src/main/java/org/wikipedia/descriptions/DescriptionEditView.kt
Labels: Minor

#5787 Donation reminder: In-article prompt
  app/src/extra/java/org/wikipedia/donate/GooglePayActivity.kt
  app/src/extra/java/org/wikipedia/donate/GooglePayComponent.kt
  app/src/extra/java/org/wikipedia/donate/GooglePayViewModel.kt
  app/src/main/java/org/wikipedia/bridge/CommunicationBridge.kt
  app/src/main/java/org/wikipedia/bridge/JavaScriptActionHandler.kt
  app/src/main/java/org/wikipedia/donate/DonateDialog.kt
  app/src/main/java/org/wikipedia/donate/donationreminder/DonationReminderActivity.kt
  app/src/main/java/org/wikipedia/donate/donationreminder/DonationReminderCardView.kt
  app/src/main/java/org/wikipedia/donate/donationreminder/DonationReminderHelper.kt
  app/src/main/java/org/wikipedia/donate/donationreminder/DonationReminderScreen.kt
  app/src/main/java/org/wikipedia/donate/donationreminder/DonationReminderViewModel.kt
  app/src/main/java/org/wikipedia/edit/preview/EditPreviewFragment.kt
  app/src/main/java/org/wikipedia/page/PageActivity.kt
  app/src/main/java/org/wikipedia/page/PageFragment.kt
  app/src/main/java/org/wikipedia/page/leadimages/LeadImagesHandler.kt
  app/src/main/java/org/wikipedia/page/leadimages/PageHeaderView.kt
  app/src/main/java/org/wikipedia/util/DimenUtil.kt
  app/src/main/java/org/wikipedia/views/LinearLayoutOverWebView.kt
  app/src/main/java/org/wikipedia/views/WikiArticleCardView.kt
  app/src/main/res/layout/dialog_donate.xml
  app/src/main/res/layout/view_donation_reminder_card.xml
  app/src/main/res/layout/view_page_header.xml
  app/src/main/res/values-qq/strings.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/xml/developer_preferences.xml
Labels: Ready for Review

#5826 Fix potential NPE when tapping on Licence icon in Gallery.
  app/src/main/java/org/wikipedia/gallery/GalleryActivity.kt
Labels: Minor

#5827 On This day game crash fixes
  app/src/main/java/org/wikipedia/games/onthisday/OnThisDayGamePlayFragment.kt
Labels: Ready to merge

#5822 Donation Reminders Instrumentation
  app/src/main/java/org/wikipedia/analytics/eventplatform/DonorExperienceEvent.kt
  app/src/main/java/org/wikipedia/donate/DonateDialog.kt
  app/src/main/java/org/wikipedia/donate/donationreminder/DonationReminderActivity.kt
  app/src/main/java/org/wikipedia/donate/donationreminder/DonationReminderHelper.kt
  app/src/main/java/org/wikipedia/donate/donationreminder/DonationReminderScreen.kt
  app/src/main/java/org/wikipedia/donate/donationreminder/DonationReminderViewModel.kt
  app/src/main/java/org/wikipedia/page/leadimages/LeadImagesHandler.kt
  app/src/main/java/org/wikipedia/page/leadimages/PageHeaderView.kt
Labels: Ready for Review

#5835 Survey Instrumentation Donation Reminders
  app/src/main/java/org/wikipedia/analytics/eventplatform/DonorExperienceEvent.kt
  app/src/main/java/org/wikipedia/donate/donationreminder/DonationReminderHelper.kt
Labels: Ready to merge

#5836 Fill description to the summary view in the article bottomsheet for WikiGames
  app/src/main/java/org/wikipedia/games/onthisday/OnThisDayGameArticleBottomSheet.kt
Labels: Minor

#5838 Activity tab to remove UI state proposal
  app/src/main/java/org/wikipedia/activitytab/ActivityTabFragment.kt
  app/src/main/java/org/wikipedia/activitytab/ActivityTabViewModel.kt
Labels: Minor

#5843 Donation reminder UI fixes
  app/src/main/java/org/wikipedia/donate/donationreminder/DonationReminderHelper.kt
  app/src/main/java/org/wikipedia/donate/donationreminder/DonationReminderScreen.kt
  app/src/main/java/org/wikipedia/donate/donationreminder/DonationReminderViewModel.kt
  app/src/main/java/org/wikipedia/settings/SettingsFragment.kt
  app/src/main/java/org/wikipedia/util/FeedbackUtil.kt
  app/src/main/res/values/strings.xml
Labels: Ready to merge

#5857 Follow-up to DAO updates.
  app/src/main/java/org/wikipedia/extensions/Activity.kt
  app/src/main/java/org/wikipedia/readinglist/ReadingListBehaviorsUtil.kt
  app/src/main/java/org/wikipedia/readinglist/ReadingListPreviewSaveDialogView.kt
Labels: Minor

#5877 Improve and streamline edit preview API call.
  app/src/main/java/org/wikipedia/dataclient/RestService.kt
  app/src/main/java/org/wikipedia/dataclient/restbase/PreviewRequest.kt
  app/src/main/java/org/wikipedia/edit/preview/EditPreviewFragment.kt
Labels: Minor

#5880 Adds an onClick parameter for WikiCard to avoid ripple animation issue
  app/src/main/java/org/wikipedia/compose/components/WikiCard.kt
  app/src/main/java/org/wikipedia/readinglist/recommended/RecommendedReadingListInterestsFragment.kt
Labels: Minor

#5882 Use WikiCard for ReadingHistoryModule cards and consolidate layouts
  app/src/main/java/org/wikipedia/activitytab/EditingInsightsModule.kt
  app/src/main/java/org/wikipedia/activitytab/ReadingHistoryModule.kt
  app/src/main/java/org/wikipedia/activitytab/TopCategoriesView.kt
Labels: Minor

#5881 Fix: use distinctBy to avoid showing duplicated articles in the interests screen
  app/src/main/java/org/wikipedia/readinglist/recommended/RecommendedReadingListInterestsViewModel.kt
Labels: Minor
